package com.readyroad.readyroadbackend.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import com.readyroad.readyroadbackend.domain.entity.Notification;
import com.readyroad.readyroadbackend.domain.entity.NotificationType;
import com.readyroad.readyroadbackend.domain.repository.NotificationRepository;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@Testcontainers
class LearningNotificationOutboxPostgreSqlIntegrationTest {
    @Container static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:17-alpine");
    JdbcTemplate jdbc;
    TransactionTemplate tx;
    LearningNotificationOutbox outbox;
    LearningNotificationWorker worker;
    NotificationRepository notifications;
    LearningNotificationTransport transport;

    @BeforeEach
    void setUp() {
        var dataSource = new DriverManagerDataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("DROP SCHEMA public CASCADE");
        jdbc.execute("CREATE SCHEMA public");
        jdbc.execute("CREATE TABLE users(id BIGINT PRIMARY KEY, email_verified BOOLEAN, is_active BOOLEAN, role VARCHAR(20))");
        // Match the existing V1 notification ownership constraint.
        jdbc.execute("CREATE TABLE notifications(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE)");
        new ResourceDatabasePopulator(new ClassPathResource(
                "db/migration-postgresql/V65__Add_Learning_Notification_Outbox.sql")).execute(dataSource);
        jdbc.update("INSERT INTO users VALUES (1, TRUE, TRUE, 'USER')");
        var transactions = new DataSourceTransactionManager(dataSource);
        tx = new TransactionTemplate(transactions);
        outbox = new LearningNotificationOutbox(jdbc);
        notifications = mock(NotificationRepository.class);
        transport = mock(LearningNotificationTransport.class);
        when(notifications.saveAndFlush(any())).thenAnswer(call -> {
            Notification notification = call.getArgument(0);
            notification.setId(jdbc.queryForObject("INSERT INTO notifications(user_id) VALUES (?) RETURNING id",
                    Long.class, notification.getUserId()));
            return notification;
        });
        worker = new LearningNotificationWorker(jdbc, notifications, transport, transactions);
    }

    Notification reminder() {
        return Notification.builder().userId(1L).type(NotificationType.STUDY_REMINDER).title("Study")
                .message("Time to learn").messageKey("notif.msg.study_reminder").messageParams("{\"days\":1}")
                .link("/practice").createdAt(Instant.now()).build();
    }
    UUID enqueue() {
        tx.executeWithoutResult(status -> outbox.enqueue(reminder()));
        return jdbc.queryForObject("SELECT id FROM learning_notification_outbox", UUID.class);
    }
    @Test
    void rollbackDoesNotLeaveAnOrphanNotificationIntent() {
        tx.executeWithoutResult(status -> { outbox.enqueue(reminder()); status.setRollbackOnly(); });
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM learning_notification_outbox", Integer.class)).isZero();
    }
    @Test
    void notificationQueuesDoNotPreventDeletingAnAccount() {
        UUID id = enqueue();
        worker.materialize(id);
        jdbc.update("DELETE FROM users WHERE id = 1");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM learning_notification_outbox", Integer.class)).isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Integer.class)).isZero();
    }
    @Test
    void concurrentRemindersAreDeduplicatedEvenBeforeMaterialization() throws Exception {
        try (var executor = java.util.concurrent.Executors.newFixedThreadPool(2)) {
            var first = executor.submit(() -> tx.executeWithoutResult(status -> outbox.enqueue(reminder())));
            var second = executor.submit(() -> tx.executeWithoutResult(status -> outbox.enqueue(reminder())));
            first.get(); second.get();
        }
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM learning_notification_outbox", Integer.class)).isEqualTo(1);
    }
    @Test
    void retriesFailedPersistenceAndMaterializesExactlyOnce() {
        UUID id = enqueue();
        doThrow(new IllegalStateException("test persistence outage")).when(notifications).saveAndFlush(any());
        worker.materialize(id);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Integer.class)).isZero();
        assertThat(jdbc.queryForObject("SELECT attempts FROM learning_notification_outbox", Integer.class)).isEqualTo(1);
        doAnswer(call -> {
            Notification n = call.getArgument(0);
            n.setId(jdbc.queryForObject("INSERT INTO notifications(user_id) VALUES (1) RETURNING id", Long.class));
            return n;
        }).when(notifications).saveAndFlush(any());
        jdbc.update("UPDATE learning_notification_outbox SET next_attempt_at = CURRENT_TIMESTAMP");
        worker.materialize(id);
        worker.materialize(id);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Integer.class)).isEqualTo(1);
    }
    @Test
    void emailFailureDoesNotReplaySuccessfulPushOrInAppNotification() {
        jdbc.update("INSERT INTO learning_notification_preferences(user_id, email_enabled) VALUES (1, TRUE)");
        UUID subscriptionId = UUID.randomUUID();
        jdbc.update("""
                INSERT INTO learning_push_subscriptions(id,user_id,endpoint,endpoint_hash,p256dh,auth_secret)
                VALUES (?,1,'https://fcm.googleapis.com/test','test-hash','test-only','test-only')
                """, subscriptionId);
        UUID id = enqueue();
        worker.materialize(id);
        var emailId = jdbc.queryForObject("SELECT id FROM learning_notification_deliveries WHERE channel='EMAIL'", Long.class);
        var pushId = jdbc.queryForObject("SELECT id FROM learning_notification_deliveries WHERE channel='PUSH'", Long.class);
        when(transport.send(eq("EMAIL"), isNull(), any())).thenThrow(new IllegalStateException("test mail outage")).thenReturn(true);
        when(transport.send(eq("PUSH"), eq(subscriptionId), any())).thenReturn(true);
        worker.deliver(emailId); worker.deliver(pushId); worker.deliver(pushId);
        assertThat(jdbc.queryForObject("SELECT status FROM learning_notification_deliveries WHERE id = ?", String.class, emailId)).isEqualTo("PENDING");
        jdbc.update("UPDATE learning_notification_deliveries SET next_attempt_at = CURRENT_TIMESTAMP WHERE id = ?", emailId);
        worker.deliver(emailId);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM learning_notification_deliveries WHERE status='SENT'", Integer.class)).isEqualTo(2);
        verify(transport, times(1)).send(eq("PUSH"), eq(subscriptionId), any());
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Integer.class)).isEqualTo(1);
    }
}
