-- 2 more EASY questions (need 20 total, have 18)
INSERT INTO quiz_questions (question_en, question_ar, question_nl, question_fr, question_type, difficulty_level, category_id, explanation_en, explanation_ar, explanation_nl, explanation_fr, is_active, status, published_at) VALUES
('What shape is a danger sign in Belgium?', 'ما هو شكل علامة الخطر في بلجيكا؟', 'Welke vorm heeft een gevaarsbord in België?', 'Quelle est la forme d''un panneau de danger en Belgique?', 'MULTIPLE_CHOICE', 'EASY', 1, 'Danger signs in Belgium are triangular with a red border.', 'علامات الخطر في بلجيكا مثلثة الشكل ذات حدود حمراء.', 'Gevaarsborden in België zijn driehoekig met een rode rand.', 'Les panneaux de danger en Belgique sont triangulaires avec un bord rouge.', 1, 'PUBLISHED', NOW()),
('What colour is the background of a priority road sign?', 'ما هو لون خلفية علامة طريق الأولوية؟', 'Welke kleur heeft de achtergrond van het bord voorrangsweg?', 'Quelle est la couleur du fond du panneau route prioritaire?', 'MULTIPLE_CHOICE', 'EASY', 2, 'The priority road sign has a yellow background with a white border.', 'علامة طريق الأولوية لها خلفية صفراء وحدود بيضاء.', 'Het bord voorrangsweg heeft een gele achtergrond met een witte rand.', 'Le panneau route prioritaire a un fond jaune avec un bord blanc.', 1, 'PUBLISHED', NOW());

-- 9 more MEDIUM questions (need 18 total, have 9)
INSERT INTO quiz_questions (question_en, question_ar, question_nl, question_fr, question_type, difficulty_level, category_id, explanation_en, explanation_ar, explanation_nl, explanation_fr, is_active, status, published_at) VALUES
('What is the maximum speed in a built-up area in Belgium?', 'ما هي السرعة القصوى داخل التجمعات السكانية في بلجيكا؟', 'Wat is de maximumsnelheid in een bebouwde kom in België?', 'Quelle est la vitesse maximale en agglomeration en Belgique?', 'MULTIPLE_CHOICE', 'MEDIUM', 6, 'The maximum speed in a built-up area in Belgium is 50 km/h unless otherwise indicated.', 'السرعة القصوى داخل التجمعات السكانية في بلجيكا هي 50 كم/ساعة ما لم تشر إشارة أخرى لخلاف ذلك.', 'De maximumsnelheid in een bebouwde kom in België is 50 km/u tenzij anders aangegeven.', 'La vitesse maximale en agglomeration en Belgique est de 50 km/h sauf indication contraire.', 1, 'PUBLISHED', NOW()),
('At an unmarked intersection in Belgium, who has right of way?', 'عند تقاطع غير معلَّم في بلجيكا، من له الأولوية؟', 'Wie heeft voorrang op een ongemarkeerd kruispunt in België?', 'A une intersection non marquee en Belgique, qui a la priorite?', 'MULTIPLE_CHOICE', 'MEDIUM', 2, 'At an unmarked intersection, the vehicle coming from the right has right of way.', 'عند التقاطع غير المعلَّم، المركبة القادمة من اليمين لها الأولوية.', 'Op een ongemarkeerd kruispunt heeft het voertuig van rechts voorrang.', 'A une intersection non marquee, le vehicule venant de droite a la priorite.', 1, 'PUBLISHED', NOW()),
('What does a solid white line in the middle of the road mean?', 'ماذا تعني الخط الأبيض الصلب في وسط الطريق؟', 'Wat betekent een doorgetrokken witte streep in het midden van de weg?', 'Que signifie une ligne blanche continue au milieu de la route?', 'MULTIPLE_CHOICE', 'MEDIUM', 3, 'A solid white line means you must not cross it. Overtaking is forbidden.', 'الخط الأبيض الصلب يعني أنه لا يجوز تخطيه. التجاوز ممنوع.', 'Een doorgetrokken streep mag niet worden overschreden. Inhalen is verboden.', 'Une ligne blanche continue ne doit pas etre franchie. Le depassement est interdit.', 1, 'PUBLISHED', NOW()),
('What must you do when you see a STOP sign?', 'ماذا يجب أن تفعل عندما ترى علامة قف؟', 'Wat moet je doen als je een STOP-bord ziet?', 'Que devez-vous faire lorsque vous voyez un panneau STOP?', 'MULTIPLE_CHOICE', 'MEDIUM', 2, 'At a STOP sign you must come to a complete stop before the stop line and give way to all traffic.', 'عند علامة قف يجب التوقف الكامل قبل خط الوقوف وتقديم الأولوية لجميع المركبات.', 'Bij een STOP-bord moet je volledig stoppen voor de stopstreep en alle verkeer voorrang geven.', 'A un panneau STOP, vous devez vous arreter completement avant la ligne et ceder la priorite.', 1, 'PUBLISHED', NOW()),
('How far must you park from a pedestrian crossing in Belgium?', 'على أي مسافة يجب أن تقف بالسيارة من ممر المشاة في بلجيكا؟', 'Op welke afstand moet je parkeren van een zebrapad in België?', 'A quelle distance d un passage pour pietons en Belgique doit-on se garer?', 'MULTIPLE_CHOICE', 'MEDIUM', 5, 'You must not park within 5 metres before a pedestrian crossing in Belgium.', 'يجب ألا تقف بسيارتك في نطاق 5 أمتار قبل ممر المشاة في بلجيكا.', 'Je mag niet parkeren binnen 5 meter voor een zebrapad in België.', 'En Belgique, il est interdit de stationner a moins de 5 metres avant un passage pieton.', 1, 'PUBLISHED', NOW()),
('What does a blue circular sign with a white arrow mean?', 'ماذا تعني العلامة الدائرية الزرقاء بسهم أبيض؟', 'Wat betekent een blauw rond bord met een witte pijl?', 'Que signifie un panneau circulaire bleu avec une fleche blanche?', 'MULTIPLE_CHOICE', 'MEDIUM', 4, 'A blue circular sign with a white arrow is a mandatory direction sign.', 'العلامة الدائرية الزرقاء بسهم أبيض إشارة اتجاه إلزامي.', 'Een blauw rond bord met witte pijl is een gebodsbord voor rijrichting.', 'Un panneau circulaire bleu avec fleche blanche est un panneau de direction obligatoire.', 1, 'PUBLISHED', NOW()),
('What is the minimum following distance on a motorway in Belgium?', 'ما هي مسافة الأمان الدنيا على الطريق السريع في بلجيكا؟', 'Wat is de minimale volgafstand op een snelweg in België?', 'Quelle est la distance de securite minimale sur autoroute en Belgique?', 'MULTIPLE_CHOICE', 'MEDIUM', 6, 'You must maintain a safe following distance of at least 2 seconds behind the vehicle in front.', 'يجب الحفاظ على مسافة أمان لا تقل عن ثانيتين خلف السيارة الأمامية.', 'Je moet een veilige volgafstand van minimaal 2 seconden aanhouden achter het voertuig voor je.', 'Vous devez maintenir une distance de securite d au moins 2 secondes derriere le vehicule precedent.', 1, 'PUBLISHED', NOW()),
('When must you use your hazard warning lights?', 'متى يجب استخدام أضواء التحذير؟', 'Wanneer moet je de alarmlichten gebruiken?', 'Quand devez-vous utiliser vos feux de detresse?', 'MULTIPLE_CHOICE', 'MEDIUM', 6, 'You must use hazard warning lights when your vehicle is a danger or obstruction to other road users.', 'يجب استخدام أضواء التحذير عندما تكون سيارتك تمثل خطراً أو عائقاً للآخرين.', 'Je moet de alarmlichten gebruiken wanneer je voertuig gevaar oplevert voor anderen.', 'Les feux de detresse doivent etre utilises quand votre vehicule constitue un danger ou une gene.', 1, 'PUBLISHED', NOW()),
('What does a yellow diamond sign on the road mean?', 'ماذا تعني العلامة الماسية الصفراء على الطريق؟', 'Wat betekent een geel ruitvormig bord op de weg?', 'Que signifie un panneau losange jaune sur la route?', 'MULTIPLE_CHOICE', 'MEDIUM', 2, 'A yellow diamond sign means you are on a priority road and have right of way over vehicles from side roads.', 'العلامة الماسية الصفراء تعني أنك على طريق ذو أولوية ولك حق المرور على المركبات القادمة من الطرق الجانبية.', 'Een geel ruitvormig bord betekent dat je op een voorrangsweg rijdt.', 'Un panneau losange jaune indique que vous etes sur une route prioritaire.', 1, 'PUBLISHED', NOW());

-- 8 more HARD questions (need 12 total, have 4)
INSERT INTO quiz_questions (question_en, question_ar, question_nl, question_fr, question_type, difficulty_level, category_id, explanation_en, explanation_ar, explanation_nl, explanation_fr, is_active, status, published_at) VALUES
('On a road with 3 lanes in the same direction, in which lane must you normally drive?', 'على طريق ذي 3 مسارات في نفس الاتجاه، في أي مسار يجب عادةً القيادة؟', 'Op een weg met 3 rijstroken in dezelfde richting, op welke strook moet je normaal rijden?', 'Sur une route a 3 voies dans le meme sens, sur quelle voie devez-vous normalement circuler?', 'MULTIPLE_CHOICE', 'HARD', 3, 'You must normally drive in the rightmost lane. The middle and left lanes are only for overtaking.', 'يجب عادةً القيادة في المسار الأيمن. المسارات الوسطى واليسرى للتجاوز فقط.', 'Je moet normaal op de meest rechtse rijstrook rijden. De middelste en linker rijstroken zijn alleen voor inhalen.', 'Vous devez normalement circuler sur la voie la plus a droite. Les autres voies sont reservees au depassement.', 1, 'PUBLISHED', NOW()),
('When does a speed limit sign end?', 'متى تنتهي علامة حد السرعة؟', 'Wanneer eindigt een snelheidsbeperking?', 'Quand prend fin une limitation de vitesse?', 'MULTIPLE_CHOICE', 'HARD', 3, 'When a speed limit ends, the general speed limit for that road type applies again.', 'عند انتهاء حد السرعة، يُطبَّق حد السرعة العام لذلك النوع من الطريق مرة أخرى.', 'Als een snelheidslimiet eindigt, geldt opnieuw de algemene snelheidslimiet voor dat type weg.', 'Quand une limitation de vitesse se termine, la limitation generale s applique a nouveau.', 1, 'PUBLISHED', NOW()),
('What is the legal blood alcohol limit for novice drivers in Belgium?', 'ما هو الحد القانوني للكحول في الدم لسائقي المبتدئين في بلجيكا؟', 'Wat is de wettelijke bloedalkohollimiet voor beginnende bestuurders in België?', 'Quelle est la limite legale d alcoolemie pour les conducteurs debutants en Belgique?', 'MULTIPLE_CHOICE', 'HARD', 3, 'Novice drivers in Belgium must not exceed 0.2 g/l blood alcohol level (effectively zero tolerance).', 'السائقون المبتدئون في بلجيكا يجب ألا يتجاوزوا 0.2 جرام/لتر من الكحول في الدم.', 'Beginnende bestuurders in België mogen niet meer dan 0,2 g/l bloedalkohol hebben.', 'Les conducteurs debutants en Belgique ne doivent pas depasser 0,2 g/l d alcoolemie.', 1, 'PUBLISHED', NOW()),
('When may you overtake on the right in Belgium?', 'متى يجوز التجاوز من اليمين في بلجيكا؟', 'Wanneer mag je in België rechts inhalen?', 'Quand peut-on depasser par la droite en Belgique?', 'MULTIPLE_CHOICE', 'HARD', 3, 'In Belgium, overtaking on the right is allowed when the vehicle in front has signalled a left turn and you use a separate right lane.', 'في بلجيكا يجوز التجاوز من اليمين عندما أشارت السيارة الأمامية بالانعطاف يساراً وتستخدم مساراً يميناً منفصلاً.', 'In België mag je rechts inhalen als het voertuig voor je links afslaat en je een aparte rechterrijstrook gebruikt.', 'En Belgique, le depassement par la droite est autorise quand le vehicule de devant tourne a gauche.', 1, 'PUBLISHED', NOW()),
('What does a flashing amber traffic light mean?', 'ماذا يعني ضوء المرور الكهرماني الوامض؟', 'Wat betekent een knipperend oranje verkeerslicht?', 'Que signifie un feu de circulation orange clignotant?', 'MULTIPLE_CHOICE', 'HARD', 6, 'A flashing amber light means proceed with caution and give way if necessary.', 'الضوء الكهرماني الوامض يعني المضي قدماً بحذر وإعطاء الأولوية عند الضرورة.', 'Een knipperend oranje licht betekent rijden met voorzichtigheid en voorrang geven indien nodig.', 'Un feu orange clignotant signifie proceder avec prudence et ceder la priorite si necessaire.', 1, 'PUBLISHED', NOW()),
('In a tunnel, what must you do if you see a red cross above your lane?', 'في النفق، ماذا يجب أن تفعل إذا رأيت صليباً أحمر فوق مسارك؟', 'In een tunnel, wat moet je doen als je een rode kruis boven je rijstrook ziet?', 'Dans un tunnel, que devez-vous faire si vous voyez une croix rouge au-dessus de votre voie?', 'MULTIPLE_CHOICE', 'HARD', 3, 'A red cross above a lane means that lane is closed. You must change lanes immediately and safely.', 'الصليب الأحمر فوق المسار يعني أن المسار مغلق. يجب تغيير المسار فوراً وبأمان.', 'Een rode kruis boven een rijstrook betekent dat de rijstrook gesloten is. Je moet onmiddellijk van rijstrook wisselen.', 'Une croix rouge au-dessus d une voie indique que la voie est fermee. Vous devez changer de voie immediatement.', 1, 'PUBLISHED', NOW()),
('When driving in fog in Belgium, when must you use front fog lights?', 'عند القيادة في الضباب في بلجيكا، متى يجب استخدام أضواء الضباب الأمامية؟', 'Wanneer moet je bij mist in België rijden met mistlichten?', 'Quand doit-on utiliser les feux antibrouillard avant en Belgique?', 'MULTIPLE_CHOICE', 'HARD', 6, 'Front fog lights must be used when visibility is reduced to less than 200 metres due to fog, snow or heavy rain.', 'يجب استخدام أضواء الضباب الأمامية عندما تقل الرؤية عن 200 متر بسبب الضباب أو الثلج أو المطر الغزير.', 'Mistlichten voor moeten worden gebruikt als het zicht door mist, sneeuw of zware regen minder dan 200 meter bedraagt.', 'Les feux antibrouillard avant doivent etre utilises quand la visibilite est reduite a moins de 200 metres.', 1, 'PUBLISHED', NOW()),
('What is the first thing you must do after a road accident with injuries in Belgium?', 'ما هو أول شيء يجب القيام به بعد حادث طريق مع إصابات في بلجيكا؟', 'Wat is het eerste wat je moet doen na een verkeersongeval met gewonden in België?', 'Quelle est la premiere chose a faire apres un accident de la route avec blesses en Belgique?', 'MULTIPLE_CHOICE', 'HARD', 6, 'After a road accident with injuries, you must first secure the scene (warning triangle, hazard lights), then call emergency services (112).', 'بعد حادث طريق مع إصابات، يجب أولاً تأمين الموقع (مثلث التحذير، أضواء الطوارئ)، ثم الاتصال بخدمات الطوارئ (112).', 'Na een verkeersongeval met gewonden moet je eerst de plaats beveiligen (gevarendriehoek, alarmlichten) en dan 112 bellen.', 'Apres un accident avec blesses, securisez d abord les lieux (triangle, feux de detresse) puis appellez le 112.', 1, 'PUBLISHED', NOW());
