package com.readyroad.readyroadbackend.domain.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Notification Entity
 *
 * Stores user notifications generated by:
 *  - Exam completion (pass / fail)
 *  - Study streak milestones
 *  - Persistent weak-area alerts
 *  - General achievements
 *  - System announcements
 */
@Entity
@Table(
    name = "notifications",
    indexes = {
        @Index(name = "idx_notifications_user_id",     columnList = "user_id"),
        @Index(name = "idx_notifications_user_unread", columnList = "user_id, is_read"),
        @Index(name = "idx_notifications_created_at",  columnList = "created_at")
    }
)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The user this notification belongs to */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /** High-level category of the notification */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 50)
    private NotificationType type;

    /** Short headline shown in the notification bell panel */
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /** Full notification text */
    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    /**
     * i18n key used by the frontend to render a translated message.
     * When present, the frontend should prefer this over the {@code message} field.
     * Example: "notif.msg.exam_passed"
     */
    @Column(name = "message_key", length = 200)
    private String messageKey;

    /**
     * JSON string of interpolation parameters for {@code messageKey}.
     * Example: {"score":43,"total":50,"pct":86}
     */
    @Column(name = "message_params", columnDefinition = "TEXT")
    private String messageParams;

    /**
     * Optional deep-link inside the app, e.g. "/exam/results/42".
     * Frontend should route to this path when the notification is clicked.
     */
    @Column(name = "link", length = 500)
    private String link;

    /** False until the user opens/reads the notification */
    @Column(name = "is_read", nullable = false)
    @Builder.Default
    private Boolean isRead = false;

    /** When this notification was created */
    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    /** Set when the user marks this notification as read */
    @Column(name = "read_at")
    private Instant readAt;

    // ── Convenience methods ──────────────────────────────────

    /** Mark notification as read (sets readAt timestamp) */
    public void markRead() {
        this.isRead = true;
        this.readAt = Instant.now();
    }
}
