-- Persist ADMIN JWT session identifiers so explicit logout can revoke the
-- current token immediately without changing USER or MODERATOR token policy.

CREATE TABLE admin_auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_admin_auth_session_id UNIQUE (session_id),
    CONSTRAINT fk_admin_auth_session_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_admin_auth_session_expiry
        CHECK (expires_at > created_at AT TIME ZONE 'UTC')
);

CREATE INDEX idx_admin_auth_sessions_user
    ON admin_auth_sessions (user_id, expires_at DESC);

CREATE INDEX idx_admin_auth_sessions_active
    ON admin_auth_sessions (session_id, revoked_at, expires_at);

CREATE TRIGGER trg_admin_auth_sessions_updated_at
BEFORE UPDATE ON admin_auth_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at_column();
