-- Effective PostgreSQL schema for identity, learning, reference content, and
-- developer assessment. Historical MySQL migrations remain independent.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50),
    email VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN', 'INSTRUCTOR', 'MODERATOR'))
);

CREATE TABLE auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(191) NOT NULL,
    provider_email VARCHAR(100) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_auth_identities_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_auth_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_auth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_password_reset_tokens_token UNIQUE (token),
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL,
    description VARCHAR(100),
    permissions TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_roles_role_name UNIQUE (role_name)
);

CREATE TABLE admin_system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name VARCHAR(100) NOT NULL,
    default_language VARCHAR(5) NOT NULL,
    maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE,
    allow_registrations BOOLEAN NOT NULL DEFAULT TRUE,
    exam_questions INTEGER NOT NULL DEFAULT 50,
    exam_duration_minutes INTEGER NOT NULL DEFAULT 30,
    passing_score_percent INTEGER NOT NULL DEFAULT 82,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT chk_admin_exam_questions CHECK (exam_questions > 0),
    CONSTRAINT chk_admin_exam_duration CHECK (exam_duration_minutes > 0),
    CONSTRAINT chk_admin_passing_score CHECK (passing_score_percent BETWEEN 0 AND 100)
);

CREATE TABLE import_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_by VARCHAR(100) NOT NULL,
    performed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    import_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_checksum VARCHAR(64),
    dry_run BOOLEAN NOT NULL DEFAULT FALSE,
    created_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    error_summary TEXT,
    warning_summary TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_import_history_status CHECK (status IN ('SUCCESS', 'PARTIAL', 'FAILED'))
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    message_key VARCHAR(200),
    message_params TEXT,
    link VARCHAR(500),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP(6) WITHOUT TIME ZONE,
    audience VARCHAR(20) NOT NULL DEFAULT 'USER',
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    achieved_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata TEXT,
    CONSTRAINT uq_achievement_user_type UNIQUE (user_id, type),
    CONSTRAINT fk_achievement_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_nl TEXT NOT NULL,
    name_fr TEXT NOT NULL,
    description_ar TEXT,
    description_en TEXT,
    description_nl TEXT,
    description_fr TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_categories_code UNIQUE (code)
);

CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_code VARCHAR(50) NOT NULL,
    title_nl TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_fr TEXT NOT NULL,
    title_ar TEXT NOT NULL,
    description_nl TEXT,
    description_en TEXT,
    description_fr TEXT,
    description_ar TEXT,
    icon VARCHAR(10),
    display_order INTEGER NOT NULL DEFAULT 0,
    estimated_minutes INTEGER NOT NULL DEFAULT 5,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lessons_lesson_code UNIQUE (lesson_code)
);

CREATE TABLE lesson_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL,
    page_number INTEGER NOT NULL,
    title_nl TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_fr TEXT NOT NULL,
    title_ar TEXT NOT NULL,
    content_nl TEXT,
    content_en TEXT,
    content_fr TEXT,
    content_ar TEXT,
    bullet_points_nl TEXT,
    bullet_points_en TEXT,
    bullet_points_fr TEXT,
    bullet_points_ar TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_lesson_page UNIQUE (lesson_id, page_number),
    CONSTRAINT fk_lesson_pages_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE user_lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    pages_read INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_seen_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_lesson UNIQUE (user_id, lesson_id),
    CONSTRAINT fk_ulp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ulp_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT chk_ulp_status CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_ulp_pages_read CHECK (pages_read >= 0)
);

CREATE TABLE traffic_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(20) NOT NULL,
    title_ar TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_nl TEXT NOT NULL,
    title_fr TEXT NOT NULL,
    content_ar TEXT,
    content_en TEXT,
    content_nl TEXT,
    content_fr TEXT,
    category_id BIGINT,
    importance_level VARCHAR(10) DEFAULT 'MEDIUM',
    applies_to VARCHAR(100) DEFAULT 'ALL',
    penalty_info_ar TEXT,
    penalty_info_en TEXT,
    penalty_info_nl TEXT,
    penalty_info_fr TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_traffic_rules_rule_code UNIQUE (rule_code),
    CONSTRAINT fk_traffic_rules_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_traffic_rules_importance CHECK (importance_level IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT chk_traffic_rules_applies_to CHECK (applies_to IN ('ALL', 'CAR', 'MOTORCYCLE', 'BICYCLE', 'TRUCK', 'BUS'))
);

CREATE TABLE dev_exam_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    icon VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dev_cat_code UNIQUE (code)
);

CREATE TABLE dev_exam_category_i18n (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT uq_dev_cat_lang UNIQUE (category_id, language_code),
    CONSTRAINT fk_dci_cat FOREIGN KEY (category_id) REFERENCES dev_exam_categories (id) ON DELETE CASCADE
);

CREATE TABLE dev_exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    question_en TEXT NOT NULL,
    question_ar TEXT,
    question_nl TEXT,
    question_fr TEXT,
    explanation_en TEXT,
    explanation_ar TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deq_cat FOREIGN KEY (category_id) REFERENCES dev_exam_categories (id),
    CONSTRAINT chk_deq_difficulty CHECK (difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'))
);

CREATE TABLE dev_exam_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    text_en TEXT NOT NULL,
    text_ar TEXT,
    text_nl TEXT,
    text_fr TEXT,
    CONSTRAINT fk_dech_q FOREIGN KEY (question_id) REFERENCES dev_exam_questions (id) ON DELETE CASCADE
);

CREATE TABLE dev_exam_settings (
    category_id INTEGER PRIMARY KEY,
    questions_beginner INTEGER NOT NULL DEFAULT 3,
    questions_intermediate INTEGER NOT NULL DEFAULT 3,
    questions_advanced INTEGER NOT NULL DEFAULT 3,
    time_limit_minutes INTEGER NOT NULL DEFAULT 20,
    pass_score_percent INTEGER NOT NULL DEFAULT 70,
    CONSTRAINT fk_des_cat FOREIGN KEY (category_id) REFERENCES dev_exam_categories (id),
    CONSTRAINT chk_des_counts CHECK (questions_beginner >= 0 AND questions_intermediate >= 0 AND questions_advanced >= 0),
    CONSTRAINT chk_des_time_limit CHECK (time_limit_minutes > 0),
    CONSTRAINT chk_des_pass_score CHECK (pass_score_percent BETWEEN 0 AND 100)
);
