-- Effective PostgreSQL schema for the general quiz, exam simulation, and
-- analytics domains. Enum-valued entity fields remain VARCHAR plus CHECKs.

CREATE TABLE road_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sign_code VARCHAR(50) NOT NULL,
    normalized_sign_code VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    image_path VARCHAR(500) NOT NULL DEFAULT '',
    serious_violation BOOLEAN NOT NULL DEFAULT FALSE,
    name_nl TEXT,
    name_en TEXT,
    name_fr TEXT,
    name_ar TEXT,
    description_nl TEXT,
    description_en TEXT,
    description_fr TEXT,
    description_ar TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    summary_nl TEXT,
    summary_en TEXT,
    summary_fr TEXT,
    summary_ar TEXT,
    driver_guidance_nl TEXT,
    driver_guidance_en TEXT,
    driver_guidance_fr TEXT,
    driver_guidance_ar TEXT,
    exceptions_nl TEXT,
    exceptions_en TEXT,
    exceptions_fr TEXT,
    exceptions_ar TEXT,
    CONSTRAINT uk_road_sign_code UNIQUE (sign_code),
    CONSTRAINT uq_road_sign_normalized_code UNIQUE (normalized_sign_code),
    CONSTRAINT chk_road_sign_category CHECK (category IN (
        'DANGER', 'PRIORITY', 'PROHIBITION', 'MANDATORY', 'PARKING',
        'INFORMATION', 'ADDITIONAL', 'CYCLIST', 'DELINEATION', 'ZONE',
        'ROAD_MANAGEMENT'
    )),
    CONSTRAINT chk_sign_code_format CHECK (sign_code ~ '^[A-Za-z0-9_-]+$')
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_ar TEXT NOT NULL,
    question_en TEXT NOT NULL,
    question_nl TEXT NOT NULL,
    question_fr TEXT NOT NULL,
    question_type VARCHAR(20) NOT NULL,
    difficulty_level VARCHAR(10) NOT NULL,
    category_id BIGINT,
    content_image_url TEXT,
    explanation_ar TEXT,
    explanation_en TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    error_explanation_ar TEXT,
    error_explanation_en TEXT,
    error_explanation_nl TEXT,
    error_explanation_fr TEXT,
    typical_error_type VARCHAR(30),
    context_specific BOOLEAN DEFAULT FALSE,
    requires_sign_image BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'DRAFT',
    published_at TIMESTAMP(6) WITHOUT TIME ZONE,
    road_sign_id BIGINT,
    CONSTRAINT fk_quiz_questions_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_quiz_questions_road_sign FOREIGN KEY (road_sign_id) REFERENCES road_signs (id) ON DELETE SET NULL,
    CONSTRAINT chk_qq_type CHECK (question_type IN ('MULTIPLE_CHOICE', 'TRUE_FALSE', 'IMAGE_BASED')),
    CONSTRAINT chk_qq_difficulty CHECK (difficulty_level IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT chk_qq_error_type CHECK (typical_error_type IS NULL OR typical_error_type IN (
        'SIGN_CONFUSION', 'SUPPLEMENTARY_IGNORED', 'PRIORITY_MISUNDERSTANDING',
        'SPEED_LIMIT_ERROR', 'ZONE_CONFUSION', 'RULE_OVERGENERALIZATION', 'OTHER'
    )),
    CONSTRAINT chk_qq_status CHECK (status IS NULL OR status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE quiz_answer_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_text_ar TEXT NOT NULL,
    option_text_en TEXT NOT NULL,
    option_text_nl TEXT NOT NULL,
    option_text_fr TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_question_display_order UNIQUE (question_id, display_order),
    CONSTRAINT fk_qao_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE
);

CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quiz_type VARCHAR(50) NOT NULL DEFAULT 'PRACTICE',
    total_questions INTEGER NOT NULL,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    wrong_answers INTEGER NOT NULL DEFAULT 0,
    score_percentage DOUBLE PRECISION,
    passed BOOLEAN NOT NULL DEFAULT FALSE,
    time_taken_seconds INTEGER,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quiz_attempts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_quiz_attempt_counts CHECK (
        total_questions >= 0 AND correct_answers >= 0 AND wrong_answers >= 0
        AND correct_answers + wrong_answers <= total_questions
    ),
    CONSTRAINT chk_quiz_attempt_score CHECK (score_percentage IS NULL OR score_percentage BETWEEN 0 AND 100)
);

CREATE TABLE quiz_user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_type VARCHAR(10) NOT NULL,
    question_ref_id BIGINT NOT NULL,
    selected_option INTEGER NOT NULL,
    is_correct BOOLEAN NOT NULL,
    time_taken_seconds INTEGER,
    answered_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quiz_user_answers_attempt FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (id) ON DELETE CASCADE,
    CONSTRAINT chk_quiz_user_answer_type CHECK (question_type IN ('PRACTICE', 'EXAM'))
);

CREATE TABLE exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    question_ar TEXT NOT NULL,
    question_en TEXT NOT NULL,
    question_nl TEXT NOT NULL,
    question_fr TEXT NOT NULL,
    option1_ar TEXT NOT NULL,
    option1_en TEXT NOT NULL,
    option1_nl TEXT NOT NULL,
    option1_fr TEXT NOT NULL,
    option2_ar TEXT NOT NULL,
    option2_en TEXT NOT NULL,
    option2_nl TEXT NOT NULL,
    option2_fr TEXT NOT NULL,
    option3_ar TEXT,
    option3_en TEXT,
    option3_nl TEXT,
    option3_fr TEXT,
    option4_ar TEXT,
    option4_en TEXT,
    option4_nl TEXT,
    option4_fr TEXT,
    correct_answer SMALLINT NOT NULL,
    explanation_ar TEXT,
    explanation_en TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    typical_error_type VARCHAR(30),
    context_specific BOOLEAN DEFAULT TRUE,
    image_url VARCHAR(500),
    difficulty VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
    is_important BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exam_questions_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT chk_eq_correct_answer CHECK (correct_answer BETWEEN 1 AND 4),
    CONSTRAINT chk_eq_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT chk_eq_error_type CHECK (typical_error_type IS NULL OR typical_error_type IN (
        'SIGN_CONFUSION', 'SUPPLEMENTARY_IGNORED', 'PRIORITY_MISUNDERSTANDING',
        'SPEED_LIMIT_ERROR', 'ZONE_CONFUSION', 'RULE_OVERGENERALIZATION', 'OTHER'
    ))
);

CREATE TABLE exam_simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    total_questions INTEGER NOT NULL DEFAULT 50,
    correct_answers INTEGER,
    score_percentage NUMERIC(5,2),
    time_taken_seconds INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_exam_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_exam_total_questions CHECK (total_questions = 50),
    CONSTRAINT chk_exam_correct_answers CHECK (correct_answers IS NULL OR correct_answers BETWEEN 0 AND 50),
    CONSTRAINT chk_exam_score CHECK (score_percentage IS NULL OR score_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_exam_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'EXPIRED'))
);

CREATE TABLE exam_simulation_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_exam_question_order UNIQUE (exam_id, question_order),
    CONSTRAINT uq_exam_question UNIQUE (exam_id, question_id),
    CONSTRAINT fk_esq_exam FOREIGN KEY (exam_id) REFERENCES exam_simulations (id) ON DELETE CASCADE,
    CONSTRAINT fk_esq_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE,
    CONSTRAINT chk_esq_order CHECK (question_order BETWEEN 1 AND 50)
);

CREATE TABLE exam_simulation_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    time_taken_seconds INTEGER NOT NULL DEFAULT 0,
    answered_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_exam_answer UNIQUE (exam_id, question_id),
    CONSTRAINT fk_esa_exam FOREIGN KEY (exam_id) REFERENCES exam_simulations (id) ON DELETE CASCADE,
    CONSTRAINT fk_esa_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_esa_option FOREIGN KEY (selected_option_id) REFERENCES quiz_answer_options (id) ON DELETE CASCADE,
    CONSTRAINT chk_esa_time CHECK (time_taken_seconds BETWEEN 0 AND 1800)
);

CREATE TABLE user_category_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    questions_attempted INTEGER NOT NULL DEFAULT 0,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    accuracy_rate NUMERIC(5,2),
    last_practiced TIMESTAMP(6) WITHOUT TIME ZONE,
    mastery_level VARCHAR(20),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ucp_user_category UNIQUE (user_id, category_id),
    CONSTRAINT fk_ucp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ucp_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT chk_ucp_attempted CHECK (questions_attempted >= 0),
    CONSTRAINT chk_ucp_correct CHECK (correct_answers BETWEEN 0 AND questions_attempted),
    CONSTRAINT chk_ucp_accuracy CHECK (accuracy_rate IS NULL OR accuracy_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_ucp_mastery CHECK (mastery_level IS NULL OR mastery_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'))
);

CREATE TABLE user_error_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    error_type VARCHAR(40) NOT NULL,
    question_type VARCHAR(10) NOT NULL,
    question_ref_type VARCHAR(10) NOT NULL,
    question_ref_id BIGINT NOT NULL,
    traffic_sign_code VARCHAR(10),
    rule_category VARCHAR(50),
    occurred_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    CONSTRAINT fk_user_error_patterns_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_uep_error_type CHECK (error_type IN (
        'SIGN_CONFUSION', 'SUPPLEMENTARY_IGNORED', 'PRIORITY_MISUNDERSTANDING',
        'SPEED_LIMIT_ERROR', 'ZONE_CONFUSION', 'RULE_OVERGENERALIZATION', 'OTHER'
    )),
    CONSTRAINT chk_uep_question_type CHECK (question_type IN ('PRACTICE', 'EXAM')),
    CONSTRAINT chk_uep_ref_type CHECK (question_ref_type IN ('RULE', 'SIGN'))
);

CREATE TABLE user_question_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT,
    question_type VARCHAR(10),
    question_ref_id BIGINT NOT NULL,
    last_shown_type VARCHAR(20),
    last_shown_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    times_shown INTEGER NOT NULL DEFAULT 1,
    times_correct INTEGER NOT NULL DEFAULT 0,
    times_wrong INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_correct BOOLEAN,
    time_taken_seconds INTEGER,
    answered_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_answer_correct BOOLEAN,
    CONSTRAINT uk_user_question_ref UNIQUE (user_id, question_ref_id),
    CONSTRAINT fk_user_question_history_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_uqh_counters CHECK (times_shown >= 0 AND times_correct >= 0 AND times_wrong >= 0)
);

CREATE TABLE user_weak_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50),
    traffic_sign_code VARCHAR(50),
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    wrong_answers INTEGER NOT NULL DEFAULT 0,
    accuracy_percentage DOUBLE PRECISION,
    last_updated TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    road_sign_id BIGINT,
    CONSTRAINT uq_uwa_user_category UNIQUE (user_id, category),
    CONSTRAINT uq_uwa_user_sign UNIQUE (user_id, traffic_sign_code),
    CONSTRAINT fk_user_weak_areas_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_weak_areas_road_sign FOREIGN KEY (road_sign_id) REFERENCES road_signs (id) ON DELETE SET NULL,
    CONSTRAINT chk_uwa_counts CHECK (total_questions >= 0 AND correct_answers >= 0 AND wrong_answers >= 0),
    CONSTRAINT chk_uwa_accuracy CHECK (accuracy_percentage IS NULL OR accuracy_percentage BETWEEN 0 AND 100)
);
