-- Traffic-sign quiz schema. The JSON files under signs_import remain the only
-- canonical source for road-sign, question, choice, and sign-exam content.

CREATE TABLE sign_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sign_id BIGINT NOT NULL,
    question_ref VARCHAR(100) NOT NULL,
    question_type VARCHAR(40) NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    is_critical BOOLEAN NOT NULL DEFAULT FALSE,
    show_sign BOOLEAN NOT NULL DEFAULT TRUE,
    question_nl TEXT,
    question_en TEXT,
    question_fr TEXT,
    question_ar TEXT,
    explanation_nl TEXT,
    explanation_en TEXT,
    explanation_fr TEXT,
    explanation_ar TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sq_ref UNIQUE (question_ref),
    CONSTRAINT fk_sq_sign FOREIGN KEY (sign_id) REFERENCES road_signs (id) ON DELETE CASCADE,
    CONSTRAINT chk_sq_type CHECK (question_type IN (
        'IS_IT_ALLOWED', 'WHAT_DOES_IT_MEAN', 'WHAT_MUST_YOU_DO', 'WHICH_SIGN',
        'HAZARD_IDENTIFICATION', 'DRIVER_ACTION', 'WHERE_DOES_IT_APPLY',
        'WHAT_HAPPENS_IF', 'SIGN_PLACEMENT_DISTANCE'
    )),
    CONSTRAINT chk_sq_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE sign_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 1,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    text_nl TEXT,
    text_en TEXT,
    text_fr TEXT,
    text_ar TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sc_q_order UNIQUE (question_id, display_order),
    CONSTRAINT fk_sc_question FOREIGN KEY (question_id) REFERENCES sign_questions (id) ON DELETE CASCADE
);

CREATE TABLE sign_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sign_id BIGINT NOT NULL,
    exam_number SMALLINT NOT NULL,
    passing_score INTEGER NOT NULL DEFAULT 6,
    total_questions INTEGER NOT NULL DEFAULT 8,
    easy_count INTEGER NOT NULL DEFAULT 3,
    medium_count INTEGER NOT NULL DEFAULT 3,
    hard_count INTEGER NOT NULL DEFAULT 2,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_se_sign_num UNIQUE (sign_id, exam_number),
    CONSTRAINT fk_se_sign FOREIGN KEY (sign_id) REFERENCES road_signs (id) ON DELETE CASCADE,
    CONSTRAINT chk_se_exam_number CHECK (exam_number > 0),
    CONSTRAINT chk_se_distribution CHECK (
        total_questions > 0 AND passing_score BETWEEN 0 AND total_questions
        AND easy_count >= 0 AND medium_count >= 0 AND hard_count >= 0
        AND easy_count + medium_count + hard_count = total_questions
    )
);

CREATE TABLE sign_exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_seq_exam_ord UNIQUE (exam_id, question_order),
    CONSTRAINT uk_seq_exam_q UNIQUE (exam_id, question_id),
    CONSTRAINT fk_seq_exam FOREIGN KEY (exam_id) REFERENCES sign_exams (id) ON DELETE CASCADE,
    CONSTRAINT fk_seq_question FOREIGN KEY (question_id) REFERENCES sign_questions (id) ON DELETE CASCADE,
    CONSTRAINT chk_seq_order CHECK (question_order > 0)
);

CREATE TABLE sign_exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sign_id BIGINT NOT NULL,
    sign_code VARCHAR(50) NOT NULL,
    exam_number INTEGER NOT NULL DEFAULT 1,
    total_questions INTEGER NOT NULL DEFAULT 0,
    answered_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    required_to_pass INTEGER NOT NULL DEFAULT 0,
    score_pct NUMERIC(5,2) NOT NULL DEFAULT 0.00,
    passed BOOLEAN NOT NULL DEFAULT FALSE,
    question_results_json TEXT,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ser_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ser_sign FOREIGN KEY (sign_id) REFERENCES road_signs (id) ON DELETE CASCADE,
    CONSTRAINT chk_ser_counts CHECK (
        total_questions >= 0 AND answered_count BETWEEN 0 AND total_questions
        AND correct_count BETWEEN 0 AND answered_count
        AND required_to_pass BETWEEN 0 AND total_questions
    ),
    CONSTRAINT chk_ser_score CHECK (score_pct BETWEEN 0 AND 100)
);

CREATE TABLE sign_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    status VARCHAR(10) NOT NULL,
    signs_processed INTEGER NOT NULL DEFAULT 0,
    signs_created INTEGER NOT NULL DEFAULT 0,
    signs_updated INTEGER NOT NULL DEFAULT 0,
    signs_skipped INTEGER NOT NULL DEFAULT 0,
    questions_created INTEGER NOT NULL DEFAULT 0,
    questions_updated INTEGER NOT NULL DEFAULT 0,
    exams_created INTEGER NOT NULL DEFAULT 0,
    errors_count INTEGER NOT NULL DEFAULT 0,
    error_summary TEXT,
    duration_ms BIGINT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_sir_status CHECK (status IN ('SUCCESS', 'PARTIAL', 'FAILED')),
    CONSTRAINT chk_sir_counts CHECK (
        signs_processed >= 0 AND signs_created >= 0 AND signs_updated >= 0
        AND signs_skipped >= 0 AND questions_created >= 0
        AND questions_updated >= 0 AND exams_created >= 0 AND errors_count >= 0
    )
);

CREATE TABLE sign_practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sign_id BIGINT NOT NULL,
    sign_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_sps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_sps_sign FOREIGN KEY (sign_id) REFERENCES road_signs (id) ON DELETE CASCADE,
    CONSTRAINT chk_sps_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_sps_counts CHECK (total_questions >= 0 AND correct_count BETWEEN 0 AND total_questions)
);

CREATE TABLE sign_practice_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    choice_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    time_taken_seconds INTEGER,
    answered_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_spa_session_question UNIQUE (session_id, question_id),
    CONSTRAINT fk_spa_session FOREIGN KEY (session_id) REFERENCES sign_practice_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_spa_question FOREIGN KEY (question_id) REFERENCES sign_questions (id),
    CONSTRAINT fk_spa_choice FOREIGN KEY (choice_id) REFERENCES sign_choices (id),
    CONSTRAINT chk_spa_time CHECK (time_taken_seconds IS NULL OR time_taken_seconds >= 0)
);

CREATE TABLE sign_random_practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_questions INTEGER NOT NULL DEFAULT 50,
    answered_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    passing_score INTEGER NOT NULL DEFAULT 41,
    score_pct NUMERIC(5,2),
    passed BOOLEAN,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_srps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_srps_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'EXPIRED', 'ABANDONED')),
    CONSTRAINT chk_srps_counts CHECK (
        total_questions > 0 AND answered_count BETWEEN 0 AND total_questions
        AND correct_count BETWEEN 0 AND answered_count
        AND passing_score BETWEEN 0 AND total_questions
    ),
    CONSTRAINT chk_srps_score CHECK (score_pct IS NULL OR score_pct BETWEEN 0 AND 100)
);

CREATE TABLE sign_random_practice_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL,
    selected_choice_id BIGINT,
    is_correct BOOLEAN,
    was_timeout BOOLEAN NOT NULL DEFAULT FALSE,
    answered_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_srpq_session_order UNIQUE (session_id, question_order),
    CONSTRAINT uq_srpq_session_question UNIQUE (session_id, question_id),
    CONSTRAINT fk_srpq_session FOREIGN KEY (session_id) REFERENCES sign_random_practice_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_srpq_question FOREIGN KEY (question_id) REFERENCES sign_questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_srpq_choice FOREIGN KEY (selected_choice_id) REFERENCES sign_choices (id) ON DELETE SET NULL,
    CONSTRAINT chk_srpq_order CHECK (question_order > 0)
);
