-- Additive, forward-only. Roll back application code without dropping queued records.
-- No historical notifications are replayed and no existing user data is changed.
CREATE TABLE learning_notification_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE learning_push_subscriptions (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    endpoint_hash VARCHAR(64) NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth_secret TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_learning_push_user ON learning_push_subscriptions(user_id, active);

CREATE TABLE learning_notification_outbox (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    message_key VARCHAR(200),
    message_params TEXT,
    link VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    notification_id BIGINT UNIQUE REFERENCES notifications(id) ON DELETE CASCADE,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error_code VARCHAR(100)
);
CREATE INDEX idx_learning_outbox_due ON learning_notification_outbox(next_attempt_at)
    WHERE notification_id IS NULL;
CREATE INDEX idx_learning_outbox_dedup ON learning_notification_outbox(user_id, type, created_at);

CREATE TABLE learning_notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id UUID NOT NULL REFERENCES learning_notification_outbox(id) ON DELETE CASCADE,
    channel VARCHAR(10) NOT NULL CHECK (channel IN ('EMAIL', 'PUSH')),
    recipient_key VARCHAR(100) NOT NULL,
    subscription_id UUID REFERENCES learning_push_subscriptions(id) ON DELETE CASCADE,
    status VARCHAR(15) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'SENT', 'CANCELLED')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error_code VARCHAR(100),
    delivered_at TIMESTAMPTZ,
    UNIQUE (outbox_id, channel, recipient_key)
);
CREATE INDEX idx_learning_deliveries_due ON learning_notification_deliveries(next_attempt_at)
    WHERE status = 'PENDING';
