-- Seed the effective general-quiz dataset used by /api/quiz/random.
--
-- Legal source chain: MySQL Flyway V72/V73, V92, and V120, followed by the
-- cleanup/workflow/normalization rules in V85, V95, V96, V107, V119,
-- V197, V199, V202, V204, and V208-V213/V235. The resulting functional
-- dataset is 50 active PUBLISHED questions and 131 deliverable options.
--
-- Stable source_ref values exist only inside this migration. Production
-- relationships are resolved through category.code and the complete
-- multilingual question natural key; no MySQL numeric IDs are assumed.

CREATE TEMPORARY TABLE general_quiz_question_seed (
    source_ref VARCHAR(30) PRIMARY KEY,
    category_code VARCHAR(10) NOT NULL,
    question_ar TEXT NOT NULL,
    question_en TEXT NOT NULL,
    question_nl TEXT NOT NULL,
    question_fr TEXT NOT NULL,
    question_type VARCHAR(20) NOT NULL,
    difficulty_level VARCHAR(10) NOT NULL,
    content_image_url TEXT,
    explanation_ar TEXT,
    explanation_en TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    error_explanation_ar TEXT,
    error_explanation_en TEXT,
    error_explanation_nl TEXT,
    error_explanation_fr TEXT,
    typical_error_type VARCHAR(30),
    context_specific BOOLEAN NOT NULL,
    requires_sign_image BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL
) ON COMMIT DROP;

INSERT INTO general_quiz_question_seed (
    source_ref, category_code,
    question_ar, question_en, question_nl, question_fr,
    question_type, difficulty_level, content_image_url,
    explanation_ar, explanation_en, explanation_nl, explanation_fr,
    error_explanation_ar, error_explanation_en, error_explanation_nl, error_explanation_fr,
    typical_error_type, context_specific, requires_sign_image, is_active, status
) VALUES
    ($readyroad$GENERAL_QUIZ_001$readyroad$, $readyroad$A$readyroad$, $readyroad$ما هي السرعة القصوى في المناطق السكنية؟$readyroad$, $readyroad$What is the speed limit in residential areas?$readyroad$, $readyroad$Wat is de snelheidslimiet in woonwijken?$readyroad$, $readyroad$Quelle est la limite de vitesse dans les zones résidentielles?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_002$readyroad$, $readyroad$A$readyroad$, $readyroad$متى يجب التوقف عند الضوء الأحمر؟$readyroad$, $readyroad$When must you stop at a red light?$readyroad$, $readyroad$Wanneer moet je stoppen bij een rood licht?$readyroad$, $readyroad$Quand devez-vous vous arrêter à un feu rouge?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_003$readyroad$, $readyroad$C$readyroad$, $readyroad$ما هي السرعة القصوى داخل المدن في بلجيكا؟$readyroad$, $readyroad$What is the maximum speed limit inside cities in Belgium?$readyroad$, $readyroad$Wat is de maximumsnelheid binnen steden in België?$readyroad$, $readyroad$Quelle est la vitesse maximale dans les villes en Belgique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$RULE_OVERGENERALIZATION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_004$readyroad$, $readyroad$C$readyroad$, $readyroad$ما السرعة القصوى على الطرق السريعة في الطقس الجاف؟$readyroad$, $readyroad$What is the maximum speed on highways in dry weather?$readyroad$, $readyroad$Wat is de maximumsnelheid op snelwegen bij droog weer?$readyroad$, $readyroad$Quelle est la vitesse maximale sur les autoroutes par temps sec?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$RULE_OVERGENERALIZATION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_005$readyroad$, $readyroad$G$readyroad$, $readyroad$ماذا يعني اللوح التكميلي تحت علامة التوقف؟$readyroad$, $readyroad$What does a supplementary panel below a STOP sign mean?$readyroad$, $readyroad$Wat betekent een onderbord onder een STOPbord?$readyroad$, $readyroad$Que signifie un panneau additionnel sous un panneau STOP?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_006$readyroad$, $readyroad$G$readyroad$, $readyroad$ماذا يعني لوح تكميلي يحمل رسم سهم إلى اليمين؟$readyroad$, $readyroad$What does a supplementary panel with a right-pointing arrow mean?$readyroad$, $readyroad$Wat betekent een onderbord met een pijl naar rechts?$readyroad$, $readyroad$Que signifie un panneau additionnel avec une flèche vers la droite?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_007$readyroad$, $readyroad$G$readyroad$, $readyroad$ما وظيفة اللوحات التكميلية بشكل عام؟$readyroad$, $readyroad$What is the general purpose of supplementary panels?$readyroad$, $readyroad$Wat is het algemene doel van onderborden?$readyroad$, $readyroad$Quel est le but général des panneaux additionnels?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_008$readyroad$, $readyroad$G$readyroad$, $readyroad$ما الشكل المعتاد للوح التكميلي البلجيكي؟$readyroad$, $readyroad$What is the typical shape of a Belgian supplementary panel?$readyroad$, $readyroad$Wat is de gebruikelijke vorm van een Belgisch onderbord?$readyroad$, $readyroad$Quelle est la forme habituelle d'un panneau additionnel belge?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_009$readyroad$, $readyroad$G$readyroad$, $readyroad$ماذا يعني لوح تكميلي يحمل الكلمة UITGEZONDERD / SAUF؟$readyroad$, $readyroad$What does a supplementary panel reading UITGEZONDERD / SAUF mean?$readyroad$, $readyroad$Wat betekent een onderbord met de tekst UITGEZONDERD?$readyroad$, $readyroad$Que signifie un panneau additionnel portant la mention SAUF?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_010$readyroad$, $readyroad$G$readyroad$, $readyroad$هل يلزم احترام اللوحات التكميلية مثل العلامات الرئيسية؟$readyroad$, $readyroad$Must supplementary panels be respected like main signs?$readyroad$, $readyroad$Moeten onderborden worden nageleefd zoals hoofdborden?$readyroad$, $readyroad$Les panneaux additionnels doivent-ils être respectés comme les panneaux principaux?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_011$readyroad$, $readyroad$G$readyroad$, $readyroad$كيف تتميز اللوحة التكميلية التي تحدد فترة زمنية؟$readyroad$, $readyroad$How is a supplementary panel indicating a time period distinguished?$readyroad$, $readyroad$Hoe onderscheidt u een onderbord dat een tijdperiode aangeeft?$readyroad$, $readyroad$Comment distingue-t-on un panneau additionnel indiquant une période horaire?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SUPPLEMENTARY_IGNORED$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_012$readyroad$, $readyroad$Z$readyroad$, $readyroad$ماذا تعني علامة منطقة السرعة 30 كم/ساعة؟$readyroad$, $readyroad$What does a Zone 30 sign mean?$readyroad$, $readyroad$Wat betekent een Zone 30-bord?$readyroad$, $readyroad$Que signifie un panneau Zone 30?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_013$readyroad$, $readyroad$Z$readyroad$, $readyroad$كيف يتم إنهاء منطقة Zone 30؟$readyroad$, $readyroad$How is a Zone 30 terminated?$readyroad$, $readyroad$Hoe wordt een Zone 30 beëindigd?$readyroad$, $readyroad$Comment est terminée une Zone 30?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_014$readyroad$, $readyroad$Z$readyroad$, $readyroad$ماذا يعني علامة منطقة سكنية Woonerf / Zone résidentielle؟$readyroad$, $readyroad$What does a Woonerf / Residential Zone sign mean?$readyroad$, $readyroad$Wat betekent een Woonerf-bord?$readyroad$, $readyroad$Que signifie un panneau Zone résidentielle?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_015$readyroad$, $readyroad$Z$readyroad$, $readyroad$ما الحد الأقصى للسرعة في منطقة سكنية Woonerf؟$readyroad$, $readyroad$What is the maximum speed in a Woonerf residential zone?$readyroad$, $readyroad$Wat is de maximumsnelheid in een Woonerf?$readyroad$, $readyroad$Quelle est la vitesse maximale dans une zone résidentielle Woonerf?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_016$readyroad$, $readyroad$Z$readyroad$, $readyroad$ما الفرق بين Zone 30 وعلامة السرعة القصوى 30 العادية؟$readyroad$, $readyroad$What is the difference between Zone 30 and a regular 30 km/h speed limit sign?$readyroad$, $readyroad$Wat is het verschil tussen Zone 30 en een gewoon 30 km/u-bord?$readyroad$, $readyroad$Quelle est la différence entre Zone 30 et un panneau de vitesse 30 km/h classique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_017$readyroad$, $readyroad$Z$readyroad$, $readyroad$ماذا يعني علامة منطقة المشاة؟$readyroad$, $readyroad$What does a pedestrian zone sign mean?$readyroad$, $readyroad$Wat betekent een voetgangerszone-bord?$readyroad$, $readyroad$Que signifie un panneau zone piétonne?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_018$readyroad$, $readyroad$Z$readyroad$, $readyroad$هل يمكن للسائق دخول منطقة مشاة لتحميل البضائع؟$readyroad$, $readyroad$Can a driver enter a pedestrian zone for loading goods?$readyroad$, $readyroad$Kan een bestuurder een voetgangerszone betreden voor het laden van goederen?$readyroad$, $readyroad$Un conducteur peut-il entrer dans une zone piétonne pour charger des marchandises?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_019$readyroad$, $readyroad$M$readyroad$, $readyroad$ما وظيفة علامات التحديد الجانبية على الطريق؟$readyroad$, $readyroad$What is the function of lateral delineation signs on the road?$readyroad$, $readyroad$Wat is de functie van zijdelingse afbakeningsborden op de weg?$readyroad$, $readyroad$Quelle est la fonction des panneaux de délimitation latérale sur la route?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_020$readyroad$, $readyroad$M$readyroad$, $readyroad$ما اللون المستخدم في علامات تحديد الطريق M1؟$readyroad$, $readyroad$What colour is used in M1 road delineation markers?$readyroad$, $readyroad$Welke kleur wordt gebruikt bij M1 wegafbakeningsborden?$readyroad$, $readyroad$Quelle couleur est utilisée dans les balises de délimitation M1?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_021$readyroad$, $readyroad$M$readyroad$, $readyroad$ما الفرق بين M2 و M3 في علامات التحديد البلجيكية؟$readyroad$, $readyroad$What is the difference between M2 and M3 Belgian delineation markers?$readyroad$, $readyroad$Wat is het verschil tussen M2 en M3 bij Belgische afbakeningsborden?$readyroad$, $readyroad$Quelle est la différence entre M2 et M3 dans les balises belges?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_022$readyroad$, $readyroad$M$readyroad$, $readyroad$لماذا يجب الانتباه لعلامات التحديد في الليل؟$readyroad$, $readyroad$Why should you pay attention to delineation markers at night?$readyroad$, $readyroad$Waarom moet u 's nachts op afbakeningsborden letten?$readyroad$, $readyroad$Pourquoi faut-il prêter attention aux balises de délimitation la nuit?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_023$readyroad$, $readyroad$M$readyroad$, $readyroad$ما علامة التحديد التي تشير إلى خطر العبور فوق جسر أو حافة؟$readyroad$, $readyroad$Which delineation sign warns of a bridge or edge crossing hazard?$readyroad$, $readyroad$Welk afbakeningsbord waarschuwt voor een oversteekgevaar bij een brug of rand?$readyroad$, $readyroad$Quel panneau de délimitation avertit d'un danger de franchissement de pont ou de bord?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_024$readyroad$, $readyroad$M$readyroad$, $readyroad$هل علامات التحديد إلزامية على الطرق الخارجية في بلجيكا؟$readyroad$, $readyroad$Are delineation markers mandatory on rural roads in Belgium?$readyroad$, $readyroad$Zijn afbakeningsborden verplicht op landelijke wegen in België?$readyroad$, $readyroad$Les balises de délimitation sont-elles obligatoires sur les routes rurales en Belgique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_025$readyroad$, $readyroad$H$readyroad$, $readyroad$ماذا تعني علامة الطريق المقطوع أو المغلق مؤقتاً؟$readyroad$, $readyroad$What does a temporary road closed sign mean?$readyroad$, $readyroad$Wat betekent een tijdelijk wegafsluiting-bord?$readyroad$, $readyroad$Que signifie un panneau de route temporairement fermée?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_026$readyroad$, $readyroad$H$readyroad$, $readyroad$ما الفرق بين العلامات الدائمة والمؤقتة لأشغال الطريق؟$readyroad$, $readyroad$What is the difference between permanent and temporary road work signs?$readyroad$, $readyroad$Wat is het verschil tussen permanente en tijdelijke wegenwerken-borden?$readyroad$, $readyroad$Quelle est la différence entre les panneaux permanents et temporaires de travaux routiers?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_027$readyroad$, $readyroad$H$readyroad$, $readyroad$ما السلوك الصحيح عند اقتراب منطقة أشغال؟$readyroad$, $readyroad$What is the correct behaviour when approaching a road work zone?$readyroad$, $readyroad$Wat is het correcte gedrag bij het naderen van een werkenzone?$readyroad$, $readyroad$Quel est le comportement correct en approchant d'une zone de travaux?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_028$readyroad$, $readyroad$H$readyroad$, $readyroad$ما معنى علامة تحويل المرور المؤقتة؟$readyroad$, $readyroad$What does a temporary traffic diversion sign mean?$readyroad$, $readyroad$Wat betekent een tijdelijk verkeersomleiding-bord?$readyroad$, $readyroad$Que signifie un panneau de déviation de circulation temporaire?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_029$readyroad$, $readyroad$H$readyroad$, $readyroad$هل تتمتع العلامات المؤقتة (خلفية صفراء) بنفس قوة العلامات الدائمة؟$readyroad$, $readyroad$Do temporary signs (yellow background) have the same force as permanent signs?$readyroad$, $readyroad$Hebben tijdelijke borden (gele achtergrond) dezelfde kracht als permanente borden?$readyroad$, $readyroad$Les panneaux temporaires (fond jaune) ont-ils la même force que les panneaux permanents?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_030$readyroad$, $readyroad$H$readyroad$, $readyroad$عند تعارض علامة مرور مؤقتة مع علامة دائمة، أيهما يُطاع؟$readyroad$, $readyroad$When a temporary sign conflicts with a permanent sign, which one takes precedence?$readyroad$, $readyroad$Als een tijdelijk bord in conflict is met een permanent bord, welk bord heeft dan voorrang?$readyroad$, $readyroad$En cas de conflit entre un panneau temporaire et un panneau permanent, lequel prime?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_031$readyroad$, $readyroad$H$readyroad$, $readyroad$ما لون خلفية علامات أشغال الطريق المؤقتة في بلجيكا؟$readyroad$, $readyroad$What background colour do temporary road work signs have in Belgium?$readyroad$, $readyroad$Welke achtergrondkleur hebben tijdelijke wegenwerken-borden in België?$readyroad$, $readyroad$De quelle couleur est le fond des panneaux de travaux temporaires en Belgique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_032$readyroad$, $readyroad$B$readyroad$, $readyroad$ماذا يعني العلامة المعينية الصفراء على الطرق البلجيكية؟$readyroad$, $readyroad$What does a yellow diamond-shaped sign indicate to drivers in Belgium?$readyroad$, $readyroad$Wat geeft een geel ruitvormig bord aan voor bestuurders in België?$readyroad$, $readyroad$Que signifie un panneau en forme de losange jaune pour les conducteurs en Belgique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, $readyroad$العلامة المعينية الصفراء (B1) تعني أنك على طريق ذي أولوية. يجب على المركبات الأخرى إعطاءك الأولوية عند التقاطعات.$readyroad$, $readyroad$A yellow diamond sign (B1) means you are on a priority road. Other traffic must yield to you at intersections unless signs indicate otherwise.$readyroad$, $readyroad$Een geel ruitvormig bord (B1) betekent dat u op een voorrangsweg rijdt. Ander verkeer moet voorrang aan u verlenen bij kruispunten.$readyroad$, $readyroad$Un panneau losange jaune (B1) signifie que vous êtes sur une route prioritaire. Les autres véhicules doivent vous céder le passage aux intersections.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_033$readyroad$, $readyroad$D$readyroad$, $readyroad$ماذا يعني العلامة الدائرية الزرقاء ذات السهم الأبيض الموجه للأعلى؟$readyroad$, $readyroad$What does a blue circular sign with a white upward arrow mean?$readyroad$, $readyroad$Wat betekent een blauw rond bord met een witte pijl omhoog?$readyroad$, $readyroad$Que signifie un panneau circulaire bleu avec une flèche blanche vers le haut?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$EASY$readyroad$, NULL, $readyroad$العلامات الدائرية الزرقاء ذات الأسهم البيضاء هي علامات اتجاه إلزامي. السهم الموجه للأعلى يعني يجب الاستمرار في السير مستقيماً دون انعطاف.$readyroad$, $readyroad$Blue circular signs with white arrows are mandatory direction signs. An upward arrow means you must continue straight ahead — no turning is permitted at that point.$readyroad$, $readyroad$Blauwe ronde borden met witte pijlen zijn verplichte richtingsborden. Een pijl omhoog betekent dat u rechtdoor moet rijden — afslaan is op dat punt niet toegestaan.$readyroad$, $readyroad$Les panneaux circulaires bleus avec des flèches blanches sont des panneaux de direction obligatoire. Une flèche vers le haut signifie que vous devez continuer tout droit, sans tourner.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_034$readyroad$, $readyroad$A$readyroad$, $readyroad$ماذا يعني العلامة المثلثة ذات الإطار الأحمر وعلامة التعجب؟$readyroad$, $readyroad$What does a red-bordered triangular sign with an exclamation mark indicate?$readyroad$, $readyroad$Wat geeft een driehoekig bord met rode rand en uitroepteken aan?$readyroad$, $readyroad$Que signifie un panneau triangulaire à bordure rouge avec un point d'exclamation?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$المثلث مع علامة التعجب (A51) هو علامة خطر عام. يحذر من خطر في الأمام لا تغطيه علامة أكثر تحديداً. قلل السرعة وتقدم بحذر.$readyroad$, $readyroad$A triangle with an exclamation mark (A51) is a general danger sign. It warns of a hazard ahead that is not covered by a more specific sign. Reduce speed and proceed cautiously.$readyroad$, $readyroad$Een driehoek met uitroepteken (A51) is een algemeen gevaarsbord. Het waarschuwt voor een gevaar vooruit dat niet door een specifiekere aanduiding wordt gedekt. Snelheid verminderen en voorzichtig rijden.$readyroad$, $readyroad$Un triangle avec un point d'exclamation (A51) est un panneau de danger général. Il avertit d'un danger en avant non couvert par un panneau plus spécifique. Réduire la vitesse et procéder avec prudence.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_035$readyroad$, $readyroad$A$readyroad$, $readyroad$ماذا يجب أن تفعل عندما ترى علامة تحذير من الطريق الزلق؟$readyroad$, $readyroad$What should you do when you see a slippery road warning sign?$readyroad$, $readyroad$Wat moet u doen wanneer u een waarschuwingsbord voor een glad wegdek ziet?$readyroad$, $readyroad$Que devez-vous faire lorsque vous voyez un panneau d'avertissement de chaussée glissante?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$علامة الطريق الزلق تتطلب منك تقليل السرعة وزيادة مسافة الأمان. مسافات التوقف أطول كثيراً على الأسطح الزلقة لذا الحذر الإضافي ضروري.$readyroad$, $readyroad$A slippery road sign requires you to reduce speed and increase following distance. Braking distances are much longer on slippery surfaces, so extra caution is essential.$readyroad$, $readyroad$Een glad wegbord vereist dat u snelheid vermindert en rijafstand vergroot. Remafstanden zijn veel langer op gladde oppervlakken, dus extra voorzichtigheid is essentieel.$readyroad$, $readyroad$Un panneau de chaussée glissante vous oblige à réduire la vitesse et augmenter la distance de sécurité. Les distances de freinage sont bien plus longues sur les surfaces glissantes.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$RULE_OVERGENERALIZATION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_036$readyroad$, $readyroad$B$readyroad$, $readyroad$ماذا تتطلب علامة المثلث المقلوب ذو الإطار الأحمر منك؟$readyroad$, $readyroad$What does an inverted triangle with a red border (give-way sign) require of you?$readyroad$, $readyroad$Wat vereist een omgekeerde driehoek met rode rand (voorrangsbord) van u?$readyroad$, $readyroad$Qu'exige de vous un triangle inversé à bordure rouge (panneau cédez le passage)?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$علامة إعطاء الأولوية (B1a/B17) تعني يجب إعطاء الأولوية لجميع المركبات على الطريق المتقاطع. يمكنك المتابعة عند الأمان ولكن لا تحتاج للتوقف الكامل إلا إذا لزم.$readyroad$, $readyroad$The give-way sign (B1a/B17) means you must yield to all traffic on the intersecting road. You may proceed when it is safe, but you do not need to stop completely unless necessary.$readyroad$, $readyroad$Het voorrangsbord (B1a/B17) betekent dat u voorrang moet verlenen aan al het verkeer op de kruisende weg. U mag doorrijden als het veilig is, maar u hoeft niet volledig te stoppen tenzij nodig.$readyroad$, $readyroad$Le panneau cédez le passage (B1a/B17) signifie que vous devez céder le passage à tout le trafic sur la route croisée. Vous pouvez avancer quand c'est sécuritaire, sans nécessairement vous arrêter.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$PRIORITY_MISUNDERSTANDING$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_037$readyroad$, $readyroad$B$readyroad$, $readyroad$عند تقاطع بلجيكي بدون علامات مرورية، أي مركبة لها حق الأولوية؟$readyroad$, $readyroad$At a Belgian intersection with no traffic signs, which vehicle has priority?$readyroad$, $readyroad$Op een Belgisch kruispunt zonder verkeersborden, welk voertuig heeft voorrang?$readyroad$, $readyroad$À une intersection belge sans panneaux de signalisation, quel véhicule a la priorité?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$في بلجيكا القاعدة الافتراضية هي الأولوية لليمين. عند التقاطعات بدون علامات، أي مركبة تأتي من اليمين لها الأولوية عليك.$readyroad$, $readyroad$In Belgium, the default rule is priority to the right (priorité à droite). At intersections without signs, any vehicle approaching from the right has priority over you.$readyroad$, $readyroad$In België is de standaardregel voorrang van rechts. Op kruispunten zonder borden heeft elk voertuig dat van rechts nadert voorrang op u.$readyroad$, $readyroad$En Belgique, la règle par défaut est la priorité à droite. Aux intersections sans panneaux, tout véhicule venant de droite a la priorité sur vous.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$PRIORITY_MISUNDERSTANDING$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_038$readyroad$, $readyroad$C$readyroad$, $readyroad$ماذا يعني الدائرة البيضاء ذات الإطار الأحمر والشريط الأبيض الأفقي في المنتصف؟$readyroad$, $readyroad$What does a white circle with a red border and a horizontal white bar in the center mean?$readyroad$, $readyroad$Wat betekent een witte cirkel met rode rand en een horizontale witte balk in het midden?$readyroad$, $readyroad$Que signifie un cercle blanc à bordure rouge avec une barre horizontale blanche au centre?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$هذه علامة C1 "ممنوع الدخول". تحظر دخول جميع المركبات. يُضعها عادة عند مدخل الطرق ذات الاتجاه الواحد والمناطق المقيدة.$readyroad$, $readyroad$This is the C1 "No Entry" sign. It prohibits all vehicles from entering. It is commonly placed at the entry of one-way streets and restricted zones.$readyroad$, $readyroad$Dit is het C1 "Verboden toegang"-bord. Het verbiedt alle voertuigen om in te rijden. Het wordt gewoonlijk geplaatst bij de ingang van eenrichtingswegen en beperkte zones.$readyroad$, $readyroad$C'est le panneau C1 "Accès interdit". Il interdit à tous les véhicules d'entrer. Il est couramment placé à l'entrée des sens uniques et des zones restreintes.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_039$readyroad$, $readyroad$C$readyroad$, $readyroad$ماذا يعني العلامة الدائرية بأرقام سوداء داخل دائرة حمراء؟$readyroad$, $readyroad$What does a round sign with a black number inside a red circle indicate?$readyroad$, $readyroad$Wat geeft een rond bord met een zwart getal binnen een rode cirkel aan?$readyroad$, $readyroad$Que signifie un panneau rond avec un chiffre noir à l'intérieur d'un cercle rouge?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$الدائرة الحمراء مع رقم بداخلها هي علامة الحد الأقصى للسرعة (C43). يجب على السائقين عدم تجاوز هذه السرعة. تتجاوز الحد الافتراضي لذلك النوع من الطريق.$readyroad$, $readyroad$A red circle with a number inside is a maximum speed limit sign (C43). Drivers must not exceed this speed. It overrides any default speed limit for that road type.$readyroad$, $readyroad$Een rode cirkel met een getal erin is een maximumsnelheidslimietbord (C43). Bestuurders mogen deze snelheid niet overschrijden. Het vervangt elke standaard snelheidslimiet voor dat wegtype.$readyroad$, $readyroad$Un cercle rouge avec un chiffre est un panneau de vitesse maximale (C43). Les conducteurs ne doivent pas dépasser cette vitesse. Il remplace toute limite de vitesse par défaut pour ce type de route.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SPEED_LIMIT_ERROR$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_040$readyroad$, $readyroad$D$readyroad$, $readyroad$ماذا يعني العلامة الدائرية الزرقاء ذات السهم الأبيض المشير إلى اليمين؟$readyroad$, $readyroad$What does a blue circular sign with a white arrow pointing to the right mean?$readyroad$, $readyroad$Wat betekent een blauw rond bord met een witte pijl naar rechts?$readyroad$, $readyroad$Que signifie un panneau rond bleu avec une flèche blanche pointant vers la droite?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$الدائرة الزرقاء مع السهم الأبيض المشير يميناً (العلامة المرورية: دوران إلزامي) هي علامة اتجاه إلزامي. يجب الانعطاف يميناً عند هذا التقاطع. هذا التزام وليس اقتراحاً.$readyroad$, $readyroad$A blue circle with a rightward white arrow (the traffic sign "Mandatory roundabout") is a mandatory direction sign. You must turn right at this junction. It is an obligation, not a suggestion.$readyroad$, $readyroad$Een blauwe cirkel met een witte pijl naar rechts (het verkeersbord "Verplicht rondgaand verkeer") is een verplicht richtingsbord. U moet rechtsaf slaan op dit kruispunt. Het is een verplichting, geen suggestie.$readyroad$, $readyroad$Un cercle bleu avec une flèche blanche vers la droite (le panneau "Circulation giratoire obligatoire") est un panneau de direction obligatoire. Vous devez tourner à droite à cette jonction. C'est une obligation.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_041$readyroad$, $readyroad$D$readyroad$, $readyroad$العلامات الدائرية الزرقاء ذات الرموز البيضاء في علامات الطريق البلجيكية تنتمي إلى أي فئة؟$readyroad$, $readyroad$Blue circular signs with white symbols in Belgian road signs belong to which category?$readyroad$, $readyroad$Blauwe ronde borden met witte symbolen bij Belgische verkeersborden behoren tot welke categorie?$readyroad$, $readyroad$Les panneaux circulaires bleus avec des symboles blancs dans la signalisation belge appartiennent à quelle catégorie?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$في تصنيف علامات الطريق البلجيكية، العلامات الدائرية الزرقاء تشير إلى الالتزامات أو التعليمات الإلزامية. تخبرك بما يجب فعله، بعكس الدوائر الحمراء التي تحظر أفعالاً.$readyroad$, $readyroad$In Belgian road sign classification, blue circular signs indicate obligations or mandatory instructions (category D). They tell you what you must do, as opposed to red circles which prohibit actions.$readyroad$, $readyroad$In de Belgische verkeersbordclassificatie geven blauwe ronde borden verplichtingen of verplichte instructies aan (categorie D). Ze vertellen u wat u moet doen, in tegenstelling tot rode cirkels die handelingen verbieden.$readyroad$, $readyroad$Dans la classification belge des panneaux, les panneaux ronds bleus indiquent des obligations ou instructions obligatoires (catégorie D). Ils indiquent ce que vous devez faire, par opposition aux cercles rouges qui interdisent.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_042$readyroad$, $readyroad$E$readyroad$, $readyroad$ماذا يعني العلامة الزرقاء التي تحمل الحرف P وعليها خط أحمر قطري؟$readyroad$, $readyroad$What does a blue sign with the letter P and a red diagonal line through it mean?$readyroad$, $readyroad$Wat betekent een blauw bord met de letter P en een rode diagonale streep erdoor?$readyroad$, $readyroad$Que signifie un panneau bleu avec la lettre P et une ligne diagonale rouge?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$العلامة الزرقاء P مع الخط الأحمر القطري هي علامة E3 "ممنوع الوقوف". الوقوف محظور لكن التوقف القصير لإنزال راكب لا يزال مسموحاً به.$readyroad$, $readyroad$A blue P sign with a red diagonal line is the E3 "no parking" sign. Parking is prohibited but brief stopping to drop off a passenger is still permitted.$readyroad$, $readyroad$Een blauw P-bord met een rode diagonale streep is het E3 "verboden te parkeren"-bord. Parkeren is verboden maar kort stoppen om een passagier af te zetten is nog steeds toegestaan.$readyroad$, $readyroad$Un panneau P bleu avec une ligne diagonale rouge est le panneau E3 "stationnement interdit". Le stationnement est interdit mais un bref arrêt pour déposer un passager est encore autorisé.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_043$readyroad$, $readyroad$E$readyroad$, $readyroad$ماذا تدل العلامة المستطيلة الزرقاء التي تحمل الحرف P فقط؟$readyroad$, $readyroad$What does a blue rectangular sign showing only the letter P indicate?$readyroad$, $readyroad$Wat geeft een blauw rechthoekig bord met alleen de letter P aan?$readyroad$, $readyroad$Que signifie un panneau rectangulaire bleu affichant uniquement la lettre P?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$MEDIUM$readyroad$, NULL, $readyroad$العلامة الزرقاء P البسيطة (E9a) تشير إلى منطقة وقوف عامة مسموح بها. ما لم تقيّدها علامات تكميلية تقيد الوقت أو نوع المستخدم، الوقوف مسموح لجميع المركبات.$readyroad$, $readyroad$A plain blue P sign (E9a) indicates a permitted public parking area. Unless supplementary signs restrict the time or user type, parking is allowed for all vehicles.$readyroad$, $readyroad$Een gewoon blauw P-bord (E9a) geeft een toegestane openbare parkeerplaats aan. Tenzij aanvullende borden de tijd of het gebruikerstype beperken, is parkeren toegestaan voor alle voertuigen.$readyroad$, $readyroad$Un simple panneau P bleu (E9a) indique une zone de stationnement public autorisé. Sauf si des panneaux complémentaires restreignent la durée ou le type d'utilisateur, le stationnement est autorisé.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_044$readyroad$, $readyroad$A$readyroad$, $readyroad$تُظهر علامة تحذير مثلثة سيارة مع خطوط متموجة تحتها. ما الخطر المحدد الذي تشير إليه؟$readyroad$, $readyroad$A triangular warning sign shows a car with wavy lines beneath it. What specific hazard does this indicate?$readyroad$, $readyroad$Een driehoekig waarschuwingsbord toont een auto met golvende lijnen eronder. Welk specifiek gevaar geeft dit aan?$readyroad$, $readyroad$Un panneau d'avertissement triangulaire montre une voiture avec des lignes ondulées en dessous. Quel danger spécifique cela indique-t-il?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$علامة A1a تُظهر سيارة تنزلق فوق خطوط متموجة مشيرة إلى سطح طريق زلق. تختلف عن علامة السطح غير المستوي. تحذر تحديداً من خطر فقدان الإمساك بالطريق.$readyroad$, $readyroad$The A1a sign shows a skidding car over wavy lines indicating a slippery road surface. This is different from the general "uneven surface" sign. It warns specifically of grip loss risk, often near bridges or shaded sections.$readyroad$, $readyroad$Het A1a-bord toont een glijdende auto over golvende lijnen die een glad wegoppervlak aangeven. Dit verschilt van het algemene "ongelijk oppervlak"-bord. Het waarschuwt specifiek voor het risico van grip verlies.$readyroad$, $readyroad$Le panneau A1a montre une voiture en dérapage sur des lignes ondulées indiquant une surface glissante. C'est différent du panneau "surface inégale". Il avertit spécifiquement du risque de perte d'adhérence.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_045$readyroad$, $readyroad$A$readyroad$, $readyroad$تُظهر علامة خطر مثلثة سهمين يشيران من الجانبين نحو بعضهما. ما الخطر الذي تشير إليه هذه العلامة المرورية؟$readyroad$, $readyroad$A triangular danger sign shows two arrows pointing toward each other from the sides. What does this warn about?$readyroad$, $readyroad$Een driehoekig gevaarsbord toont twee pijlen die van de zijkanten naar elkaar toe wijzen. Waarvoor waarschuwt dit?$readyroad$, $readyroad$Un panneau de danger triangulaire montre deux flèches pointant l'une vers l'autre depuis les côtés. De quoi avertit-il?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$علامة A7a "تضييق الطريق من كلا الجانبين" تحذر من أن حارة الطريق تضيق. قد يتطلب هذا توخي الحذر عند مرور مركبات مقابلة. يجب على السائقين التباطؤ والاستعداد لإعطاء الأولوية.$readyroad$, $readyroad$The A7a "road narrows on both sides" sign warns that the carriageway reduces in width. This may require extra caution when meeting oncoming traffic. Drivers should slow and be prepared to give way.$readyroad$, $readyroad$Het A7a-bord "weg versmalt aan beide zijden" waarschuwt dat de rijbaan smaller wordt. Dit vereist mogelijk extra voorzichtigheid bij tegemoetkomend verkeer. Bestuurders moeten vertragen.$readyroad$, $readyroad$Le panneau A7a "chaussée rétrécie des deux côtés" avertit que la chaussée se réduit en largeur. Cela peut nécessiter une prudence supplémentaire pour le trafic venant en sens inverse.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_046$readyroad$, $readyroad$B$readyroad$, $readyroad$أنت على طريق ذي أولوية وتدخل مركبة من اليمين دون إعطاء الأولوية. من يتحمل المسؤولية القانونية عن الحادث؟$readyroad$, $readyroad$You are on a priority road and another vehicle from the right enters without yielding. Who bears legal responsibility for the incident?$readyroad$, $readyroad$U rijdt op een voorrangsweg en een ander voertuig van rechts rijdt op zonder voorrang te verlenen. Wie draagt de wettelijke verantwoordelijkheid voor het incident?$readyroad$, $readyroad$Vous roulez sur une route prioritaire et un autre véhicule venant de droite entre sans céder le passage. Qui porte la responsabilité légale pour l'incident?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$على الطريق ذي الأولوية لديك حق المرور. المركبة التي لم تعطِ الأولوية من اليمين مسؤولة قانونياً. ومع ذلك حتى على طريق الأولوية يجب الحفاظ على سرعة آمنة.$readyroad$, $readyroad$On a priority road you have the right of way. The vehicle that failed to yield from the right is legally at fault. However, even on a priority road you must maintain a safe speed and stay alert — contributory negligence may apply if you were speeding.$readyroad$, $readyroad$Op een voorrangsweg heeft u het recht van weg. Het voertuig dat geen voorrang verleende van rechts is wettelijk schuldig. Toch moet u ook op een voorrangsweg een veilige snelheid handhaven.$readyroad$, $readyroad$Sur une route prioritaire vous avez la priorité. Le véhicule qui n'a pas cédé le passage venant de droite est légalement responsable. Cependant même sur une route prioritaire vous devez maintenir une vitesse sûre.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$PRIORITY_MISUNDERSTANDING$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_047$readyroad$, $readyroad$C$readyroad$, $readyroad$دائرة بيضاء بخطوط رمادية قطرية متعددة تظهر بعد سلسلة من القيود. ماذا تعني هذه العلامة المرورية؟$readyroad$, $readyroad$A white circle with multiple diagonal grey lines is posted after a series of restrictions. What does this traffic sign mean?$readyroad$, $readyroad$Een witte cirkel met meerdere diagonale grijze lijnen staat na een opeenvolging beperkingen. Wat betekent dit verkeersbord?$readyroad$, $readyroad$Un cercle blanc avec plusieurs lignes grises diagonales est placé après une série de restrictions. Que signifie ce panneau?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$علامة C99 تلغي جميع الحظر السابق الذي تم الإشارة إليه على الطريق (مثل حدود السرعة وحظر التجاوز وما إلى ذلك). تستأنف قواعد المرور العادية من هذه النقطة.$readyroad$, $readyroad$This C99 sign cancels all previous prohibitions that were signed on the road (such as speed limits, overtaking bans, etc.). The normal traffic rules resume from this point onwards.$readyroad$, $readyroad$Dit C99-bord heft alle eerder aangeduide verboden op de weg op (zoals snelheidslimieten, inhaalverboden, enz.). De normale verkeersregels hervatten vanaf dit punt.$readyroad$, $readyroad$Ce panneau C99 annule toutes les interdictions précédemment signalées sur la route (limites de vitesse, interdictions de dépassement, etc.). Les règles normales de circulation reprennent.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$RULE_OVERGENERALIZATION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_048$readyroad$, $readyroad$D$readyroad$, $readyroad$تُظهر علامة دائرية زرقاء رمز دراجة ورمز مشاة مفصولَين بخط عمودي. ماذا يعني هذا؟$readyroad$, $readyroad$A blue circular sign shows a bicycle symbol and a pedestrian symbol separated by a vertical line. What does this indicate?$readyroad$, $readyroad$Een blauw rond bord toont een fietssymbool en een voetgangerssymbool gescheiden door een verticale lijn. Wat geeft dit aan?$readyroad$, $readyroad$Un panneau rond bleu montre un symbole de vélo et un symbole piéton séparés par une ligne verticale. Que signifie cela?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$علامة العلامة المرورية: مسار مشترك للمشاة وراكبي الدراجات تشير إلى مسار مشترك مقسم: جانب للدراجات وآخر للمشاة. يجب أن يبقى كلا المستخدمين في منطقتهم المخصصة. تختلف عن D9 حيث يتقاسمون المسار الكامل.$readyroad$, $readyroad$The the traffic sign "Shared path for pedestrians and cyclists" sign indicates a shared path that is divided: one side for cyclists and one for pedestrians. Both users must stay in their designated zone. This is different from D9 where they share the full path without separation.$readyroad$, $readyroad$Het het verkeersbord "Deel van de weg voorbehouden voor voetgangers en fietsers"-bord geeft een gedeeld pad aan dat verdeeld is: één zijde voor fietsers en één voor voetgangers. Beide gebruikers moeten in hun aangewezen zone blijven. Dit verschilt van D9 waar ze het gehele pad delen.$readyroad$, $readyroad$Le panneau le panneau "Chemin partagé pour piétons et cyclistes" indique un chemin partagé divisé: un côté pour les cyclistes et un pour les piétons. Les deux utilisateurs doivent rester dans leur zone désignée. Différent du D9 où ils partagent l'intégralité.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_049$readyroad$, $readyroad$E$readyroad$, $readyroad$ما الفرق القانوني الرئيسي بين علامة E1 (ممنوع التوقف) وعلامة E3 (ممنوع الركن) في بلجيكا؟$readyroad$, $readyroad$What is the key legal difference between an E1 (no stopping) sign and an E3 (no parking) sign in Belgium?$readyroad$, $readyroad$Wat is het belangrijkste juridische verschil tussen een E1-bord (verboden te stoppen) en een E3-bord (verboden te parkeren) in België?$readyroad$, $readyroad$Quelle est la différence juridique essentielle entre un panneau E1 (arrêt interdit) et un panneau E3 (stationnement interdit) en Belgique?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$E1 (ممنوع التوقف) يحظر أي شكل من أشكال التوقف حتى للحظة. E3 (ممنوع الركن) يحظر فقط ترك المركبة دون مراقبة لكن يسمح بالتوقف القصير للتحميل أو التفريغ أو إنزال الركاب.$readyroad$, $readyroad$E1 (no stopping) prohibits any form of stopping, even momentarily. E3 (no parking) only prohibits leaving a vehicle unattended but allows brief stops for loading, unloading or dropping off passengers.$readyroad$, $readyroad$E1 (verboden te stoppen) verbiedt elke vorm van stoppen, zelfs kort. E3 (verboden te parkeren) verbiedt alleen het verlaten van een voertuig zonder toezicht, maar staat korte stops voor laden/lossen of uitstappen toe.$readyroad$, $readyroad$E1 (arrêt interdit) interdit toute forme d'arrêt, même momentanée. E3 (stationnement interdit) interdit uniquement de laisser un véhicule sans surveillance, mais permet de brefs arrêts pour charger/décharger.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$ZONE_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$),
    ($readyroad$GENERAL_QUIZ_050$readyroad$, $readyroad$F$readyroad$, $readyroad$تُظهر علامة معلومات مستطيلة زرقاء الحرف H مع سهم اتجاه. ماذا تشير هذه العلامة المرورية؟$readyroad$, $readyroad$A blue rectangular information sign displays the letter H with a directional arrow. What does this sign indicate?$readyroad$, $readyroad$Een blauw rechthoekig informatiebord toont de letter H met een richtingspijl. Wat geeft dit bord aan?$readyroad$, $readyroad$Un panneau d'information rectangulaire bleu affiche la lettre H avec une flèche directionnelle. Que signifie ce panneau?$readyroad$, $readyroad$MULTIPLE_CHOICE$readyroad$, $readyroad$HARD$readyroad$, NULL, $readyroad$الحرف H على علامة معلومات زرقاء يرمز إلى "Hôpital" (بالفرنسية) أو المستشفى. وهي علامة اتجاه خدمية ترشد السائقين نحو أقرب مستشفى. تنتمي هذه العلامات إلى الفئة F (علامات المعلومات) في تصنيف علامات الطريق البلجيكية.$readyroad$, $readyroad$The letter H on a blue information sign stands for "Hôpital" (French) or "Hospital". It is a service direction sign and guides drivers toward the nearest hospital. These signs are part of the F-category (information signs) in Belgian road sign classification.$readyroad$, $readyroad$De letter H op een blauw informatiebord staat voor "Hôpital" (Frans) of ziekenhuis. Het is een dienstrichtingsbord en begeleidt bestuurders naar het dichtstbijzijnde ziekenhuis. Deze borden behoren tot de F-categorie in de Belgische verkeersbordclassificatie.$readyroad$, $readyroad$La lettre H sur un panneau d'information bleu signifie "Hôpital". C'est un panneau de direction de service qui guide les conducteurs vers l'hôpital le plus proche. Ces panneaux font partie de la catégorie F des panneaux belges.$readyroad$, NULL, NULL, NULL, NULL, $readyroad$SIGN_CONFUSION$readyroad$, FALSE, FALSE, TRUE, $readyroad$PUBLISHED$readyroad$)
;

CREATE TEMPORARY TABLE general_quiz_option_seed (
    question_source_ref VARCHAR(30) NOT NULL,
    option_text_ar TEXT NOT NULL,
    option_text_en TEXT NOT NULL,
    option_text_nl TEXT NOT NULL,
    option_text_fr TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    PRIMARY KEY (question_source_ref, display_order),
    FOREIGN KEY (question_source_ref)
        REFERENCES general_quiz_question_seed (source_ref)
        ON DELETE CASCADE
) ON COMMIT DROP;

INSERT INTO general_quiz_option_seed (
    question_source_ref,
    option_text_ar, option_text_en, option_text_nl, option_text_fr,
    is_correct, display_order
) VALUES
    ($readyroad$GENERAL_QUIZ_001$readyroad$, $readyroad$50 كم/ساعة$readyroad$, $readyroad$50 km/h$readyroad$, $readyroad$50 km/u$readyroad$, $readyroad$50 km/h$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_001$readyroad$, $readyroad$70 كم/ساعة$readyroad$, $readyroad$70 km/h$readyroad$, $readyroad$70 km/u$readyroad$, $readyroad$70 km/h$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_001$readyroad$, $readyroad$90 كم/ساعة$readyroad$, $readyroad$90 km/h$readyroad$, $readyroad$90 km/u$readyroad$, $readyroad$90 km/h$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_002$readyroad$, $readyroad$دائماً$readyroad$, $readyroad$Always$readyroad$, $readyroad$Altijd$readyroad$, $readyroad$Toujours$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_002$readyroad$, $readyroad$إذا لم يكن هناك سيارات$readyroad$, $readyroad$If there are no cars$readyroad$, $readyroad$Als er geen auto's zijn$readyroad$, $readyroad$S'il n'y a pas de voitures$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_002$readyroad$, $readyroad$فقط في النهار$readyroad$, $readyroad$Only during daytime$readyroad$, $readyroad$Alleen overdag$readyroad$, $readyroad$Seulement pendant la journée$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_003$readyroad$, $readyroad$50 كم/ساعة$readyroad$, $readyroad$50 km/h$readyroad$, $readyroad$50 km/u$readyroad$, $readyroad$50 km/h$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_003$readyroad$, $readyroad$60 كم/ساعة$readyroad$, $readyroad$60 km/h$readyroad$, $readyroad$60 km/u$readyroad$, $readyroad$60 km/h$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_003$readyroad$, $readyroad$70 كم/ساعة$readyroad$, $readyroad$70 km/h$readyroad$, $readyroad$70 km/u$readyroad$, $readyroad$70 km/h$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_004$readyroad$, $readyroad$120 كم/ساعة$readyroad$, $readyroad$120 km/h$readyroad$, $readyroad$120 km/u$readyroad$, $readyroad$120 km/h$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_004$readyroad$, $readyroad$100 كم/ساعة$readyroad$, $readyroad$100 km/h$readyroad$, $readyroad$100 km/u$readyroad$, $readyroad$100 km/h$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_004$readyroad$, $readyroad$90 كم/ساعة$readyroad$, $readyroad$90 km/h$readyroad$, $readyroad$90 km/u$readyroad$, $readyroad$90 km/h$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_005$readyroad$, $readyroad$يضيف شرطاً إضافياً للعلامة الرئيسية$readyroad$, $readyroad$It adds an additional condition to the main sign$readyroad$, $readyroad$Het voegt een bijkomende voorwaarde aan het hoofdbord toe$readyroad$, $readyroad$Il ajoute une condition supplémentaire au panneau principal$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_005$readyroad$, $readyroad$يلغي العلامة الرئيسية$readyroad$, $readyroad$It cancels the main sign$readyroad$, $readyroad$Het annuleert het hoofdbord$readyroad$, $readyroad$Il annule le panneau principal$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_005$readyroad$, $readyroad$يُغير لون العلامة الرئيسية$readyroad$, $readyroad$It changes the colour of the main sign$readyroad$, $readyroad$Het verandert de kleur van het hoofdbord$readyroad$, $readyroad$Il change la couleur du panneau principal$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_006$readyroad$, $readyroad$يشير إلى أن التطبيق يكون في الاتجاه الذي يشير إليه السهم$readyroad$, $readyroad$It indicates the sign applies in the direction the arrow points$readyroad$, $readyroad$Het geeft aan dat het bord geldt in de pijlrichting$readyroad$, $readyroad$Il indique que le panneau s'applique dans la direction indiquée par la flèche$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_006$readyroad$, $readyroad$يشير إلى مسار هروب$readyroad$, $readyroad$It marks an escape route$readyroad$, $readyroad$Het markeert een vluchtroute$readyroad$, $readyroad$Il marque une route d'évacuation$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_007$readyroad$, $readyroad$تحديد أو تقييد نطاق تطبيق العلامة الرئيسية$readyroad$, $readyroad$To define or restrict the scope of the main sign$readyroad$, $readyroad$De reikwijdte van het hoofdbord afbakenen of beperken$readyroad$, $readyroad$Définir ou restreindre la portée du panneau principal$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_007$readyroad$, $readyroad$استبدال العلامة الرئيسية$readyroad$, $readyroad$To replace the main sign$readyroad$, $readyroad$Het hoofdbord vervangen$readyroad$, $readyroad$Remplacer le panneau principal$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_008$readyroad$, $readyroad$مستطيل أبيض بإطار أحمر$readyroad$, $readyroad$White rectangle with red border$readyroad$, $readyroad$Witte rechthoek met rode rand$readyroad$, $readyroad$Rectangle blanc avec bordure rouge$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_008$readyroad$, $readyroad$دائرة زرقاء$readyroad$, $readyroad$Blue circle$readyroad$, $readyroad$Blauwe cirkel$readyroad$, $readyroad$Cercle bleu$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_008$readyroad$, $readyroad$مثلث أصفر$readyroad$, $readyroad$Yellow triangle$readyroad$, $readyroad$Gele driehoek$readyroad$, $readyroad$Triangle jaune$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_009$readyroad$, $readyroad$استثناء لفئة معينة من تطبيق العلامة الرئيسية$readyroad$, $readyroad$An exception for a specific category from the main sign$readyroad$, $readyroad$Een uitzondering voor een bepaalde categorie van het hoofdbord$readyroad$, $readyroad$Une exception pour une catégorie spécifique du panneau principal$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_009$readyroad$, $readyroad$يمنع جميع المركبات$readyroad$, $readyroad$It prohibits all vehicles$readyroad$, $readyroad$Het verbiedt alle voertuigen$readyroad$, $readyroad$Il interdit tous les véhicules$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_009$readyroad$, $readyroad$مرحلة تجريبية$readyroad$, $readyroad$Pilot phase indicator$readyroad$, $readyroad$Pilootfase indicator$readyroad$, $readyroad$Indicateur de phase pilote$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_010$readyroad$, $readyroad$نعم، لها قوة قانونية ملزمة$readyroad$, $readyroad$Yes, they have legally binding force$readyroad$, $readyroad$Ja, ze hebben wettelijk bindende kracht$readyroad$, $readyroad$Oui, ils ont une force juridiquement contraignante$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_010$readyroad$, $readyroad$لا، هي مجرد توصيات$readyroad$, $readyroad$No, they are merely recommendations$readyroad$, $readyroad$Nee, het zijn slechts aanbevelingen$readyroad$, $readyroad$Non, ce ne sont que des recommandations$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_011$readyroad$, $readyroad$تحمل أوقاتاً أو أياماً مكتوبة عليها$readyroad$, $readyroad$It shows times or days written on it$readyroad$, $readyroad$Het toont tijden of dagen erop geschreven$readyroad$, $readyroad$Il affiche des heures ou des jours indiqués dessus$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_011$readyroad$, $readyroad$تكون مضاءة باللون الأخضر$readyroad$, $readyroad$It is lit in green$readyroad$, $readyroad$Het is verlicht in het groen$readyroad$, $readyroad$Il est éclairé en vert$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_011$readyroad$, $readyroad$تحمل رمز ساعة$readyroad$, $readyroad$It carries a clock symbol$readyroad$, $readyroad$Het draagt een kloksymbool$readyroad$, $readyroad$Il porte un symbole d'horloge$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_012$readyroad$, $readyroad$السرعة القصوى في المنطقة كاملها 30 كم/ساعة$readyroad$, $readyroad$Maximum speed throughout the entire zone is 30 km/h$readyroad$, $readyroad$Maximumsnelheid door de gehele zone is 30 km/u$readyroad$, $readyroad$La vitesse maximale dans toute la zone est de 30 km/h$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_012$readyroad$, $readyroad$السرعة القصوى 30 كم/ساعة في هذه النقطة فقط$readyroad$, $readyroad$Maximum speed is 30 km/h at this point only$readyroad$, $readyroad$Maximumsnelheid is 30 km/u alleen op dit punt$readyroad$, $readyroad$La vitesse maximale est de 30 km/h à ce point seulement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_012$readyroad$, $readyroad$لا يوجد حد سرعة$readyroad$, $readyroad$There is no speed limit$readyroad$, $readyroad$Er is geen snelheidslimiet$readyroad$, $readyroad$Il n'y a pas de limitation de vitesse$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_013$readyroad$, $readyroad$علامة نهاية Zone 30$readyroad$, $readyroad$An End Zone 30 sign$readyroad$, $readyroad$Een Einde Zone 30-bord$readyroad$, $readyroad$Un panneau Fin Zone 30$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_013$readyroad$, $readyroad$خط أبيض على الأرض$readyroad$, $readyroad$A white line on the ground$readyroad$, $readyroad$Een witte lijn op de grond$readyroad$, $readyroad$Une ligne blanche sur le sol$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_014$readyroad$, $readyroad$منطقة مشتركة بين المشاة والمركبات بقواعد خاصة$readyroad$, $readyroad$A shared area for pedestrians and vehicles with special rules$readyroad$, $readyroad$Een gedeeld gebied voor voetgangers en voertuigen met speciale regels$readyroad$, $readyroad$Une zone partagée entre piétons et véhicules avec des règles spéciales$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_014$readyroad$, $readyroad$منطقة مخصصة للمركبات فقط$readyroad$, $readyroad$A zone reserved for vehicles only$readyroad$, $readyroad$Een zone voorbehouden aan voertuigen$readyroad$, $readyroad$Une zone réservée aux véhicules uniquement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_014$readyroad$, $readyroad$طريق سريع محلي$readyroad$, $readyroad$A local express road$readyroad$, $readyroad$Een lokale snelweg$readyroad$, $readyroad$Une voie express locale$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_015$readyroad$, $readyroad$20 كم/ساعة$readyroad$, $readyroad$20 km/h$readyroad$, $readyroad$20 km/u$readyroad$, $readyroad$20 km/h$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_015$readyroad$, $readyroad$30 كم/ساعة$readyroad$, $readyroad$30 km/h$readyroad$, $readyroad$30 km/u$readyroad$, $readyroad$30 km/h$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_015$readyroad$, $readyroad$50 كم/ساعة$readyroad$, $readyroad$50 km/h$readyroad$, $readyroad$50 km/u$readyroad$, $readyroad$50 km/h$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_016$readyroad$, $readyroad$Zone 30 تنطبق على الشوارع داخل المنطقة بأكملها، بينما الأخرى تنطبق فقط من نقطة الوضع$readyroad$, $readyroad$Zone 30 applies to all streets within the zone, while the other applies only from where it is placed$readyroad$, $readyroad$Zone 30 geldt voor alle straten in de zone, terwijl het andere enkel geldt vanaf de plaatsing$readyroad$, $readyroad$Zone 30 s'applique à toutes les rues de la zone, l'autre seulement depuis son emplacement$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_016$readyroad$, $readyroad$لا يوجد فرق$readyroad$, $readyroad$There is no difference$readyroad$, $readyroad$Er is geen verschil$readyroad$, $readyroad$Il n'y a pas de différence$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_017$readyroad$, $readyroad$المنطقة مخصصة للمشاة، المركبات ممنوعة إلا بإذن$readyroad$, $readyroad$The zone is for pedestrians only, vehicles are prohibited unless authorised$readyroad$, $readyroad$De zone is voorbehouden voor voetgangers, voertuigen zijn verboden tenzij gemachtigd$readyroad$, $readyroad$La zone est réservée aux piétons, les véhicules sont interdits sauf autorisation$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_017$readyroad$, $readyroad$المشاة فقط ممنوعون من الدخول$readyroad$, $readyroad$Only pedestrians are prohibited from entering$readyroad$, $readyroad$Alleen voetgangers mogen niet binnenkomen$readyroad$, $readyroad$Seuls les piétons sont interdits d'entrée$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_017$readyroad$, $readyroad$السرعة القصوى 10 كم/ساعة$readyroad$, $readyroad$Maximum speed is 10 km/h$readyroad$, $readyroad$Maximumsnelheid is 10 km/u$readyroad$, $readyroad$La vitesse maximale est de 10 km/h$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_018$readyroad$, $readyroad$فقط في حال كان هناك لوح تكميلي يسمح بذلك$readyroad$, $readyroad$Only if there is a supplementary panel authorising it$readyroad$, $readyroad$Alleen als er een onderbord is dat dit toestaat$readyroad$, $readyroad$Seulement s'il y a un panneau additionnel l'autorisant$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_018$readyroad$, $readyroad$نعم دائماً$readyroad$, $readyroad$Yes always$readyroad$, $readyroad$Ja altijd$readyroad$, $readyroad$Oui toujours$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_018$readyroad$, $readyroad$لا أبداً$readyroad$, $readyroad$Never$readyroad$, $readyroad$Nooit$readyroad$, $readyroad$Jamais$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_019$readyroad$, $readyroad$إرشاد السائقين لحافة الطريق أو العوائق$readyroad$, $readyroad$To guide drivers to the road edge or obstacles$readyroad$, $readyroad$Bestuurders naar de rijbaanrand of obstakels leiden$readyroad$, $readyroad$Guider les conducteurs vers le bord de la chaussée ou les obstacles$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_019$readyroad$, $readyroad$تحديد الحد الأقصى للسرعة$readyroad$, $readyroad$To indicate the maximum speed$readyroad$, $readyroad$De maximumsnelheid aanduiden$readyroad$, $readyroad$Indiquer la vitesse maximale$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_019$readyroad$, $readyroad$منع الوقوف$readyroad$, $readyroad$To prohibit parking$readyroad$, $readyroad$Parkeren verbieden$readyroad$, $readyroad$Interdire le stationnement$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_020$readyroad$, $readyroad$أبيض مع شريط عاكس أحمر وأبيض$readyroad$, $readyroad$White with red and white reflective strip$readyroad$, $readyroad$Wit met rood-witte reflecterende strook$readyroad$, $readyroad$Blanc avec bande réfléchissante rouge et blanche$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_020$readyroad$, $readyroad$أصفر تماماً$readyroad$, $readyroad$Entirely yellow$readyroad$, $readyroad$Volledig geel$readyroad$, $readyroad$Entièrement jaune$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_020$readyroad$, $readyroad$أزرق مع نجمة بيضاء$readyroad$, $readyroad$Blue with a white star$readyroad$, $readyroad$Blauw met een witte ster$readyroad$, $readyroad$Bleu avec une étoile blanche$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_021$readyroad$, $readyroad$M2 لليمين (أحمر-أبيض) و M3 لليسار (أبيض)$readyroad$, $readyroad$M2 marks the right side (red-white) and M3 marks the left side (white)$readyroad$, $readyroad$M2 markeert de rechterkant (rood-wit) en M3 de linkerkant (wit)$readyroad$, $readyroad$M2 marque le côté droit (rouge-blanc) et M3 le côté gauche (blanc)$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_021$readyroad$, $readyroad$M2 للطرق السريعة و M3 للطرق المحلية$readyroad$, $readyroad$M2 is for highways and M3 for local roads$readyroad$, $readyroad$M2 is voor snelwegen en M3 voor lokale wegen$readyroad$, $readyroad$M2 est pour les autoroutes et M3 pour les routes locales$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_022$readyroad$, $readyroad$لأنها عاكسة وتحدد حافة الطريق في الظلام$readyroad$, $readyroad$Because they are reflective and mark the road edge in the dark$readyroad$, $readyroad$Omdat ze reflecterend zijn en de rijbaanrand in het donker markeren$readyroad$, $readyroad$Parce qu'elles sont réfléchissantes et marquent le bord de la route dans l'obscurité$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_022$readyroad$, $readyroad$لأنها مضاءة بشكل نشط$readyroad$, $readyroad$Because they are actively illuminated$readyroad$, $readyroad$Omdat ze actief verlicht zijn$readyroad$, $readyroad$Parce qu'elles sont activement éclairées$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_023$readyroad$, $readyroad$علامة التحديد M4 ذات الألوان الحمراء والبيضاء المتناوبة$readyroad$, $readyroad$M4 delineation marker with alternate red and white colours$readyroad$, $readyroad$M4 afbakeningsbord met afwisselend rood en wit$readyroad$, $readyroad$Balise de délimitation M4 avec couleurs rouges et blanches alternées$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_023$readyroad$, $readyroad$علامة التحديد M1 الصغيرة$readyroad$, $readyroad$Small M1 delineation marker$readyroad$, $readyroad$Klein M1-afbakeningsbord$readyroad$, $readyroad$Petite balise de délimitation M1$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_024$readyroad$, $readyroad$نعم، تُنصب حيث يوجد خطر أو حافة غير محمية$readyroad$, $readyroad$Yes, installed where there is a hazard or unprotected edge$readyroad$, $readyroad$Ja, geplaatst waar een gevaar of onbeschermde rand bestaat$readyroad$, $readyroad$Oui, installées là où il y a un danger ou un bord non protégé$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_024$readyroad$, $readyroad$لا، هي اختيارية تماماً$readyroad$, $readyroad$No, they are completely optional$readyroad$, $readyroad$Nee, ze zijn volledig optioneel$readyroad$, $readyroad$Non, elles sont entièrement facultatives$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_025$readyroad$, $readyroad$يجب على السائق إيجاد طريق بديل$readyroad$, $readyroad$The driver must find an alternative route$readyroad$, $readyroad$De bestuurder moet een alternatieve route zoeken$readyroad$, $readyroad$Le conducteur doit trouver un itinéraire alternatif$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_025$readyroad$, $readyroad$يمكن المرور ببطء$readyroad$, $readyroad$You may pass slowly$readyroad$, $readyroad$U mag langzaam passeren$readyroad$, $readyroad$Vous pouvez passer lentement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_025$readyroad$, $readyroad$الطريق مغلق للمشاة فقط$readyroad$, $readyroad$The road is closed for pedestrians only$readyroad$, $readyroad$De weg is alleen afgesloten voor voetgangers$readyroad$, $readyroad$La route est fermée pour les piétons uniquement$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_026$readyroad$, $readyroad$العلامات المؤقتة لها خلفية صفراء في بلجيكا$readyroad$, $readyroad$Temporary signs have a yellow background in Belgium$readyroad$, $readyroad$Tijdelijke borden hebben een gele achtergrond in België$readyroad$, $readyroad$Les panneaux temporaires ont un fond jaune en Belgique$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_026$readyroad$, $readyroad$العلامات المؤقتة أصغر حجماً$readyroad$, $readyroad$Temporary signs are smaller in size$readyroad$, $readyroad$Tijdelijke borden zijn kleiner van formaat$readyroad$, $readyroad$Les panneaux temporaires sont plus petits$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_027$readyroad$, $readyroad$خفض السرعة والانتباه للعمال والعلامات المؤقتة$readyroad$, $readyroad$Reduce speed and watch out for workers and temporary signs$readyroad$, $readyroad$Snelheid verminderen en letten op arbeiders en tijdelijke borden$readyroad$, $readyroad$Réduire la vitesse et faire attention aux ouvriers et aux panneaux temporaires$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_027$readyroad$, $readyroad$تسريع للمرور بسرعة$readyroad$, $readyroad$Accelerate to pass quickly$readyroad$, $readyroad$Versnellen om snel voorbij te komen$readyroad$, $readyroad$Accélérer pour passer rapidement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_027$readyroad$, $readyroad$تشغيل الأضواء الخلفية$readyroad$, $readyroad$Turn on rear lights$readyroad$, $readyroad$Achterlichten inschakelen$readyroad$, $readyroad$Allumer les feux arrière$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_028$readyroad$, $readyroad$يجب اتباع مسار التحويل المشار إليه$readyroad$, $readyroad$You must follow the indicated diversion route$readyroad$, $readyroad$U moet de aangegeven omleiding volgen$readyroad$, $readyroad$Vous devez suivre l'itinéraire de déviation indiqué$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_028$readyroad$, $readyroad$التحويل اختياري$readyroad$, $readyroad$The diversion is optional$readyroad$, $readyroad$De omleiding is optioneel$readyroad$, $readyroad$La déviation est facultative$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_028$readyroad$, $readyroad$الطريق مفتوح للجميع$readyroad$, $readyroad$The road is open to everyone$readyroad$, $readyroad$De weg is voor iedereen open$readyroad$, $readyroad$La route est ouverte à tous$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_029$readyroad$, $readyroad$نعم، يجب احترامها بنفس القدر$readyroad$, $readyroad$Yes, they must be respected equally$readyroad$, $readyroad$Ja, ze moeten even goed worden nageleefd$readyroad$, $readyroad$Oui, ils doivent être respectés de la même manière$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_029$readyroad$, $readyroad$لا، يمكن تجاهلها$readyroad$, $readyroad$No, they can be ignored$readyroad$, $readyroad$Nee, ze mogen worden genegeerd$readyroad$, $readyroad$Non, ils peuvent être ignorés$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_030$readyroad$, $readyroad$العلامة المؤقتة لها الأولوية$readyroad$, $readyroad$The temporary sign takes precedence$readyroad$, $readyroad$Het tijdelijke bord heeft voorrang$readyroad$, $readyroad$Le panneau temporaire a la priorité$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_030$readyroad$, $readyroad$العلامة الدائمة لها الأولوية$readyroad$, $readyroad$The permanent sign takes precedence$readyroad$, $readyroad$Het permanente bord heeft voorrang$readyroad$, $readyroad$Le panneau permanent a la priorité$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_031$readyroad$, $readyroad$أصفر$readyroad$, $readyroad$Yellow$readyroad$, $readyroad$Geel$readyroad$, $readyroad$Jaune$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_031$readyroad$, $readyroad$أبيض$readyroad$, $readyroad$White$readyroad$, $readyroad$Wit$readyroad$, $readyroad$Blanc$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_031$readyroad$, $readyroad$برتقالي$readyroad$, $readyroad$Orange$readyroad$, $readyroad$Oranje$readyroad$, $readyroad$Orange$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_032$readyroad$, $readyroad$أنت تسير على طريق ذي أولوية$readyroad$, $readyroad$You are driving on a priority road$readyroad$, $readyroad$U rijdt op een voorrangsweg$readyroad$, $readyroad$Vous roulez sur une route prioritaire$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_032$readyroad$, $readyroad$يجب عليك إعطاء الأولوية لجميع المركبات القادمة$readyroad$, $readyroad$You must give way to all oncoming traffic$readyroad$, $readyroad$U moet voorrang verlenen aan al het tegemoetkomend verkeer$readyroad$, $readyroad$Vous devez céder le passage à tout le trafic venant en sens inverse$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_032$readyroad$, $readyroad$أنت تقترب من دوار$readyroad$, $readyroad$You are approaching a roundabout$readyroad$, $readyroad$U nadert een rotonde$readyroad$, $readyroad$Vous approchez d'un rond-point$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_033$readyroad$, $readyroad$يجب عليك الاستمرار في السير مستقيماً$readyroad$, $readyroad$You must continue straight ahead$readyroad$, $readyroad$U moet rechtdoor rijden$readyroad$, $readyroad$Vous devez continuer tout droit$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_033$readyroad$, $readyroad$يمكنك الدخول فقط بتصريح$readyroad$, $readyroad$You may only enter with a permit$readyroad$, $readyroad$U mag alleen met een vergunning binnenrijden$readyroad$, $readyroad$Vous ne pouvez entrer qu'avec une autorisation$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_033$readyroad$, $readyroad$شارع ذو اتجاه واحد في الأمام$readyroad$, $readyroad$One-way street ahead$readyroad$, $readyroad$Eenrichtingsstraat voor u$readyroad$, $readyroad$Sens unique en avant$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_034$readyroad$, $readyroad$خطر عام في الطريق$readyroad$, $readyroad$General danger or hazard ahead$readyroad$, $readyroad$Algemeen gevaar of hindernis vooruit$readyroad$, $readyroad$Danger général ou obstacle en avant$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_034$readyroad$, $readyroad$يجب عليك التوقف فوراً$readyroad$, $readyroad$You must stop immediately$readyroad$, $readyroad$U moet onmiddellijk stoppen$readyroad$, $readyroad$Vous devez vous arrêter immédiatement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_034$readyroad$, $readyroad$تبدأ منطقة حد السرعة$readyroad$, $readyroad$Speed limit zone begins$readyroad$, $readyroad$Zone met snelheidsbeperking begint$readyroad$, $readyroad$Début d'une zone de limitation de vitesse$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_035$readyroad$, $readyroad$تقليل السرعة وزيادة مسافة الأمان$readyroad$, $readyroad$Reduce speed and increase following distance$readyroad$, $readyroad$Snelheid verminderen en rijafstand vergroten$readyroad$, $readyroad$Réduire la vitesse et augmenter la distance de sécurité$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_035$readyroad$, $readyroad$أوقف السيارة وانتظر حتى تختفي الخطورة$readyroad$, $readyroad$Stop the vehicle and wait for the hazard to clear$readyroad$, $readyroad$Stop het voertuig en wacht tot het gevaar voorbij is$readyroad$, $readyroad$Arrêter le véhicule et attendre que le danger disparaisse$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_035$readyroad$, $readyroad$تشغيل أضواء الطوارئ فقط$readyroad$, $readyroad$Switch on your hazard warning lights only$readyroad$, $readyroad$Alleen de gevarendriehoek inschakelen$readyroad$, $readyroad$Activer uniquement les feux de détresse$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_036$readyroad$, $readyroad$إعطاء الأولوية لجميع المركبات على الطريق المتقاطع$readyroad$, $readyroad$Give way to all traffic on the intersecting road$readyroad$, $readyroad$Voorrang verlenen aan al het verkeer op de kruisende weg$readyroad$, $readyroad$Céder le passage à tout le trafic sur la route croisée$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_036$readyroad$, $readyroad$التوقف التام قبل الدخول إلى التقاطع$readyroad$, $readyroad$Stop completely before entering the intersection$readyroad$, $readyroad$Volledig stoppen voor het oprijden van het kruispunt$readyroad$, $readyroad$S'arrêter complètement avant d'entrer dans l'intersection$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_036$readyroad$, $readyroad$إعطاء الأولوية للترام والحافلات فقط$readyroad$, $readyroad$Give way only to trams and buses$readyroad$, $readyroad$Alleen voorrang verlenen aan trams en bussen$readyroad$, $readyroad$Céder le passage uniquement aux trams et aux bus$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_037$readyroad$, $readyroad$المركبة القادمة من اليمين$readyroad$, $readyroad$The vehicle coming from the right$readyroad$, $readyroad$Het voertuig dat van rechts komt$readyroad$, $readyroad$Le véhicule venant de droite$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_037$readyroad$, $readyroad$المركبة التي تسير بسرعة أعلى$readyroad$, $readyroad$The vehicle travelling at the higher speed$readyroad$, $readyroad$Het voertuig dat met hogere snelheid rijdt$readyroad$, $readyroad$Le véhicule circulant à la vitesse la plus élevée$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_037$readyroad$, $readyroad$المركبة على الطريق الأوسع$readyroad$, $readyroad$The vehicle on the wider road$readyroad$, $readyroad$Het voertuig op de bredere weg$readyroad$, $readyroad$Le véhicule sur la route la plus large$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_038$readyroad$, $readyroad$ممنوع الدخول لجميع المركبات$readyroad$, $readyroad$No entry for all vehicles$readyroad$, $readyroad$Verboden toegang voor alle voertuigen$readyroad$, $readyroad$Accès interdit à tous les véhicules$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_038$readyroad$, $readyroad$منطقة حد السرعة في الأمام$readyroad$, $readyroad$Speed limit zone ahead$readyroad$, $readyroad$Zone met snelheidsbeperking voor u$readyroad$, $readyroad$Zone de limitation de vitesse en avant$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_038$readyroad$, $readyroad$لا موقف على هذا الجانب من الطريق$readyroad$, $readyroad$No parking on this side of the road$readyroad$, $readyroad$Parkeren verboden aan deze kant van de weg$readyroad$, $readyroad$Stationnement interdit de ce côté de la route$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_039$readyroad$, $readyroad$الحد الأقصى للسرعة بالكيلومتر في الساعة$readyroad$, $readyroad$Maximum speed limit in kilometres per hour$readyroad$, $readyroad$Maximale snelheidslimiet in kilometer per uur$readyroad$, $readyroad$Vitesse maximale autorisée en kilomètres par heure$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_039$readyroad$, $readyroad$الحد الأدنى للسرعة المطلوبة بالكيلومتر في الساعة$readyroad$, $readyroad$Minimum speed required in kilometres per hour$readyroad$, $readyroad$Minimumsnelheid vereist in kilometer per uur$readyroad$, $readyroad$Vitesse minimale requise en kilomètres par heure$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_039$readyroad$, $readyroad$السرعة الموصى بها للمنعطفات الخطرة$readyroad$, $readyroad$Advisory speed for dangerous curves$readyroad$, $readyroad$Aanbevolen snelheid voor gevaarlijke bochten$readyroad$, $readyroad$Vitesse conseillée pour les courbes dangereuses$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_040$readyroad$, $readyroad$يجب عليك الانعطاف يميناً$readyroad$, $readyroad$You must turn right$readyroad$, $readyroad$U moet rechtsaf slaan$readyroad$, $readyroad$Vous devez tourner à droite$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_040$readyroad$, $readyroad$يمكنك الانعطاف يميناً إذا أردت$readyroad$, $readyroad$You may turn right if you wish$readyroad$, $readyroad$U mag rechtsaf slaan als u wilt$readyroad$, $readyroad$Vous pouvez tourner à droite si vous le souhaitez$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_040$readyroad$, $readyroad$الانعطاف يميناً محظور في الأمام$readyroad$, $readyroad$Right turn is prohibited ahead$readyroad$, $readyroad$Rechtsaf slaan is verboden voor u$readyroad$, $readyroad$Le virage à droite est interdit en avant$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_041$readyroad$, $readyroad$علامات الالتزام أو التعليمات الإلزامية$readyroad$, $readyroad$Obligation or mandatory instruction signs$readyroad$, $readyroad$Gebodsverkeerstekens of verplichtingsborden$readyroad$, $readyroad$Panneaux d'obligation ou d'instruction obligatoire$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_041$readyroad$, $readyroad$علامات المعلومات والخدمات$readyroad$, $readyroad$Information and service signs$readyroad$, $readyroad$Informatie- en dienstenborden$readyroad$, $readyroad$Panneaux d'information et de services$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_041$readyroad$, $readyroad$علامات التحذير والخطر$readyroad$, $readyroad$Warning and danger signs$readyroad$, $readyroad$Waarschuwings- en gevaarsborden$readyroad$, $readyroad$Panneaux d'avertissement et de danger$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_042$readyroad$, $readyroad$الوقوف غير مسموح به$readyroad$, $readyroad$Parking is not allowed$readyroad$, $readyroad$Parkeren is niet toegestaan$readyroad$, $readyroad$Le stationnement n'est pas autorisé$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_042$readyroad$, $readyroad$منطقة الوقوف المدفوع$readyroad$, $readyroad$Paid parking zone$readyroad$, $readyroad$Betalende parkeerzone$readyroad$, $readyroad$Zone de stationnement payant$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_042$readyroad$, $readyroad$الوقوف مخصص لحاملي التصاريح$readyroad$, $readyroad$Parking reserved for permit holders$readyroad$, $readyroad$Parkeren voorbehouden aan vergunninghouders$readyroad$, $readyroad$Stationnement réservé aux détenteurs de permis$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_043$readyroad$, $readyroad$منطقة وقوف مسموح بها$readyroad$, $readyroad$A permitted parking area$readyroad$, $readyroad$Een toegestane parkeerplaats$readyroad$, $readyroad$Une zone de stationnement autorisée$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_043$readyroad$, $readyroad$وقوف لمركبات الشرطة فقط$readyroad$, $readyroad$Parking for police vehicles only$readyroad$, $readyroad$Parkeren alleen voor politievoertuigen$readyroad$, $readyroad$Parking réservé aux véhicules de police$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_043$readyroad$, $readyroad$نهاية قيود الوقوف$readyroad$, $readyroad$End of parking restrictions$readyroad$, $readyroad$Einde van parkeerbeperkingen$readyroad$, $readyroad$Fin des restrictions de stationnement$readyroad$, FALSE, 3),
    ($readyroad$GENERAL_QUIZ_044$readyroad$, $readyroad$طريق زلق أو غير مستقر في الأمام$readyroad$, $readyroad$Slippery or unstable road surface ahead$readyroad$, $readyroad$Glad of onstabiel wegdek voor u$readyroad$, $readyroad$Chaussée glissante ou instable en avant$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_044$readyroad$, $readyroad$فيضانات أو مياه على سطح الطريق$readyroad$, $readyroad$Flooding or water on the road surface$readyroad$, $readyroad$Overstromingen of water op het wegoppervlak$readyroad$, $readyroad$Inondations ou eau sur la surface de la route$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_045$readyroad$, $readyroad$الطريق يضيق في الأمام من كلا الجانبين$readyroad$, $readyroad$The road narrows ahead on both sides$readyroad$, $readyroad$De weg versmalt voor u aan beide zijden$readyroad$, $readyroad$La route se rétrécit des deux côtés en avant$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_045$readyroad$, $readyroad$يبدأ المرور في اتجاهين في الأمام$readyroad$, $readyroad$Two-way traffic begins ahead$readyroad$, $readyroad$Tweerichtingsverkeer begint voor u$readyroad$, $readyroad$La circulation à double sens commence en avant$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_046$readyroad$, $readyroad$المركبة القادمة من اليمين التي لم تعطِ الأولوية$readyroad$, $readyroad$The vehicle from the right, which failed to yield$readyroad$, $readyroad$Het voertuig van rechts dat geen voorrang verleende$readyroad$, $readyroad$Le véhicule venant de droite qui n'a pas cédé le passage$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_046$readyroad$, $readyroad$السائق على طريق الأولوية لعدم توقع الخطر$readyroad$, $readyroad$The driver on the priority road for not anticipating the hazard$readyroad$, $readyroad$De bestuurder op de voorrangsweg voor het niet anticiperen op het gevaar$readyroad$, $readyroad$Le conducteur sur la route prioritaire pour ne pas avoir anticipé le danger$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_047$readyroad$, $readyroad$نهاية جميع الحظر المُنشر سابقاً على هذا الطريق$readyroad$, $readyroad$End of all previously posted prohibitions on this road$readyroad$, $readyroad$Einde van alle eerder aangeduide verboden op deze weg$readyroad$, $readyroad$Fin de toutes les interdictions précédemment signalées sur cette route$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_047$readyroad$, $readyroad$بداية منطقة مقيدة جديدة بقواعد مختلفة$readyroad$, $readyroad$Start of a new restricted zone with different rules$readyroad$, $readyroad$Begin van een nieuwe beperkte zone met andere regels$readyroad$, $readyroad$Début d'une nouvelle zone restreinte avec des règles différentes$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_048$readyroad$, $readyroad$مسار مشترك له مناطق منفصلة لراكبي الدراجات والمشاة$readyroad$, $readyroad$A shared path with separate zones for cyclists and pedestrians$readyroad$, $readyroad$Een gedeeld pad met aparte zones voor fietsers en voetgangers$readyroad$, $readyroad$Un chemin partagé avec des zones séparées pour les cyclistes et les piétons$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_048$readyroad$, $readyroad$مسار حيث يتقاسم راكبو الدراجات والمشاة العرض الكامل بحرية$readyroad$, $readyroad$A path where cyclists and pedestrians share the full width freely$readyroad$, $readyroad$Een pad waar fietsers en voetgangers de volledige breedte vrij delen$readyroad$, $readyroad$Un chemin où cyclistes et piétons partagent toute la largeur librement$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_049$readyroad$, $readyroad$E1 يحظر أي توقف؛ E3 يحظر الوقوف المطول فقط ويسمح بالتوقف القصير$readyroad$, $readyroad$E1 prohibits any stopping; E3 prohibits only prolonged parking but allows brief stops$readyroad$, $readyroad$E1 verbiedt elk stoppen; E3 verbiedt alleen langdurig parkeren maar staat korte stops toe$readyroad$, $readyroad$E1 interdit tout arrêt; E3 interdit seulement le stationnement prolongé mais permet les brefs arrêts$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_049$readyroad$, $readyroad$E1 ينطبق فقط خلال ساعات النهار؛ E3 ينطبق على مدار الساعة$readyroad$, $readyroad$E1 applies only during day hours; E3 applies around the clock$readyroad$, $readyroad$E1 geldt alleen overdag; E3 geldt de klok rond$readyroad$, $readyroad$E1 s'applique uniquement pendant les heures de jour; E3 s'applique à toute heure$readyroad$, FALSE, 2),
    ($readyroad$GENERAL_QUIZ_050$readyroad$, $readyroad$الاتجاه نحو أقرب مستشفى$readyroad$, $readyroad$Direction to the nearest hospital$readyroad$, $readyroad$Richting naar het dichtstbijzijnde ziekenhuis$readyroad$, $readyroad$Direction vers l'hôpital le plus proche$readyroad$, TRUE, 1),
    ($readyroad$GENERAL_QUIZ_050$readyroad$, $readyroad$طريق نقل المواد الخطرة$readyroad$, $readyroad$Hazardous materials transport route$readyroad$, $readyroad$Route voor transport van gevaarlijke stoffen$readyroad$, $readyroad$Route de transport de matières dangereuses$readyroad$, FALSE, 2)
;

DO $$
BEGIN
    IF (SELECT COUNT(*) FROM general_quiz_question_seed) <> 50 THEN
        RAISE EXCEPTION 'General quiz seed must contain exactly 50 questions';
    END IF;
    IF (SELECT COUNT(*) FROM general_quiz_option_seed) <> 131 THEN
        RAISE EXCEPTION 'General quiz seed must contain exactly 131 options';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM general_quiz_question_seed seed
        LEFT JOIN categories category ON category.code = seed.category_code
        WHERE category.id IS NULL
    ) THEN
        RAISE EXCEPTION 'General quiz seed references an unknown category code';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM general_quiz_option_seed
        GROUP BY question_source_ref
        HAVING COUNT(*) NOT BETWEEN 2 AND 3
           OR COUNT(*) FILTER (WHERE is_correct) <> 1
    ) THEN
        RAISE EXCEPTION 'Every general quiz question must have 2-3 options and exactly one correct option';
    END IF;
END;
$$;

INSERT INTO quiz_questions (
    question_ar, question_en, question_nl, question_fr,
    question_type, difficulty_level, category_id, content_image_url,
    explanation_ar, explanation_en, explanation_nl, explanation_fr,
    error_explanation_ar, error_explanation_en, error_explanation_nl, error_explanation_fr,
    typical_error_type, context_specific, requires_sign_image,
    is_active, status, published_at
)
SELECT
    seed.question_ar, seed.question_en, seed.question_nl, seed.question_fr,
    seed.question_type, seed.difficulty_level, category.id, seed.content_image_url,
    seed.explanation_ar, seed.explanation_en, seed.explanation_nl, seed.explanation_fr,
    seed.error_explanation_ar, seed.error_explanation_en,
    seed.error_explanation_nl, seed.error_explanation_fr,
    seed.typical_error_type, seed.context_specific, seed.requires_sign_image,
    seed.is_active, seed.status,
    CASE WHEN seed.status = 'PUBLISHED' THEN CURRENT_TIMESTAMP ELSE NULL END
FROM general_quiz_question_seed seed
JOIN categories category ON category.code = seed.category_code
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_questions existing
    WHERE existing.question_ar = seed.question_ar
      AND existing.question_en = seed.question_en
      AND existing.question_nl = seed.question_nl
      AND existing.question_fr = seed.question_fr
);

INSERT INTO quiz_answer_options (
    question_id,
    option_text_ar, option_text_en, option_text_nl, option_text_fr,
    is_correct, display_order
)
SELECT
    question.id,
    option_seed.option_text_ar, option_seed.option_text_en,
    option_seed.option_text_nl, option_seed.option_text_fr,
    option_seed.is_correct, option_seed.display_order
FROM general_quiz_option_seed option_seed
JOIN general_quiz_question_seed question_seed
  ON question_seed.source_ref = option_seed.question_source_ref
JOIN quiz_questions question
  ON question.question_ar = question_seed.question_ar
 AND question.question_en = question_seed.question_en
 AND question.question_nl = question_seed.question_nl
 AND question.question_fr = question_seed.question_fr
WHERE NOT EXISTS (
    SELECT 1
    FROM quiz_answer_options existing
    WHERE existing.question_id = question.id
      AND existing.display_order = option_seed.display_order
);

DO $$
DECLARE
    matched_questions INTEGER;
    matched_options INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO matched_questions
      FROM general_quiz_question_seed seed
      JOIN quiz_questions question
        ON question.question_ar = seed.question_ar
       AND question.question_en = seed.question_en
       AND question.question_nl = seed.question_nl
       AND question.question_fr = seed.question_fr
     WHERE question.is_active = TRUE
       AND question.status = 'PUBLISHED';

    SELECT COUNT(*)
      INTO matched_options
      FROM general_quiz_option_seed option_seed
      JOIN general_quiz_question_seed question_seed
        ON question_seed.source_ref = option_seed.question_source_ref
      JOIN quiz_questions question
        ON question.question_ar = question_seed.question_ar
       AND question.question_en = question_seed.question_en
       AND question.question_nl = question_seed.question_nl
       AND question.question_fr = question_seed.question_fr
      JOIN quiz_answer_options option
        ON option.question_id = question.id
       AND option.display_order = option_seed.display_order
       AND option.option_text_ar = option_seed.option_text_ar
       AND option.option_text_en = option_seed.option_text_en
       AND option.option_text_nl = option_seed.option_text_nl
       AND option.option_text_fr = option_seed.option_text_fr
       AND option.is_correct = option_seed.is_correct;

    IF matched_questions <> 50 THEN
        RAISE EXCEPTION 'Expected 50 active published general quiz questions, found %', matched_questions;
    END IF;
    IF matched_options <> 131 THEN
        RAISE EXCEPTION 'Expected 131 matched general quiz options, found %', matched_options;
    END IF;
END;
$$;
