package com.readyroad.readyroadbackend.marketing.editorial;

enum EditorialArticleQualityGate {
    USEFUL_DEPTH,
    HUMAN_READABILITY,
    SEARCH_INTENT,
    SOURCE_VERIFICATION,
    LEGAL_CONSISTENCY,
    REGIONAL_ACCURACY,
    TRANSLATION_QUALITY,
    DUPLICATE_CHECK,
    CANNIBALIZATION_CHECK,
    INTERNAL_LINKS,
    IMAGE_LICENSE,
    IMAGE_RELEVANCE,
    IMAGE_OPTIMIZATION,
    ALT_TEXT,
    METADATA,
    STRUCTURED_DATA,
    MOBILE_PREVIEW,
    NO_BROKEN_LINKS,
    NO_MISLEADING_CLAIMS,
    NO_KEYWORD_STUFFING,
    NO_INVENTED_FACTS,
    NO_UNSUPPORTED_LEGAL_CLAIMS
}
