-- V110: Fix Traffic Signs Encoding + Restore All Damaged Sign Data
-- Strategy: CONVERT Mojibake first for undamaged rows, then restore the 21 damaged rows by overwriting with correct authoritative values.
-- Sources: signs.json (FR/NL/EN), signs_backup JSON (AR), V90 migration (structure)

SET NAMES utf8mb4;

-- ============================================================
-- PHASE 1: Fix remaining Mojibake encoding for non-Arabic columns
-- Each column uses its OWN WHERE condition (no cross-column side effects)
-- Only affects rows still containing actual Mojibake patterns (C383/C382 bytes)
-- ============================================================

-- Fix remaining 1 corrupted Arabic row in name_ar
UPDATE traffic_signs
SET name_ar = CONVERT(BINARY(CONVERT(name_ar USING latin1)) USING utf8mb4)
WHERE HEX(name_ar) LIKE '%C383%' OR HEX(name_ar) LIKE '%C382%';

-- Fix corrupted French rows in name_fr
UPDATE traffic_signs
SET name_fr = CONVERT(BINARY(CONVERT(name_fr USING latin1)) USING utf8mb4)
WHERE HEX(name_fr) LIKE '%C383%' OR HEX(name_fr) LIKE '%C382%';

-- Fix corrupted Dutch rows in name_nl
UPDATE traffic_signs
SET name_nl = CONVERT(BINARY(CONVERT(name_nl USING latin1)) USING utf8mb4)
WHERE HEX(name_nl) LIKE '%C383%' OR HEX(name_nl) LIKE '%C382%';

-- Fix corrupted Arabic rows in description_ar
UPDATE traffic_signs
SET description_ar = CONVERT(BINARY(CONVERT(description_ar USING latin1)) USING utf8mb4)
WHERE description_ar IS NOT NULL AND (HEX(description_ar) LIKE '%C383%' OR HEX(description_ar) LIKE '%C382%');

-- Fix corrupted French rows in description_fr
UPDATE traffic_signs
SET description_fr = CONVERT(BINARY(CONVERT(description_fr USING latin1)) USING utf8mb4)
WHERE description_fr IS NOT NULL AND (HEX(description_fr) LIKE '%C383%' OR HEX(description_fr) LIKE '%C382%');

-- Fix corrupted Dutch rows in description_nl
UPDATE traffic_signs
SET description_nl = CONVERT(BINARY(CONVERT(description_nl USING latin1)) USING utf8mb4)
WHERE description_nl IS NOT NULL AND (HEX(description_nl) LIKE '%C383%' OR HEX(description_nl) LIKE '%C382%');

-- Fix corrupted Arabic rows in long_description_ar
UPDATE traffic_signs
SET long_description_ar = CONVERT(BINARY(CONVERT(long_description_ar USING latin1)) USING utf8mb4)
WHERE long_description_ar IS NOT NULL AND (HEX(long_description_ar) LIKE '%C383%' OR HEX(long_description_ar) LIKE '%C382%');

-- Fix corrupted French rows in long_description_fr
UPDATE traffic_signs
SET long_description_fr = CONVERT(BINARY(CONVERT(long_description_fr USING latin1)) USING utf8mb4)
WHERE long_description_fr IS NOT NULL AND (HEX(long_description_fr) LIKE '%C383%' OR HEX(long_description_fr) LIKE '%C382%');

-- Fix corrupted Dutch rows in long_description_nl
UPDATE traffic_signs
SET long_description_nl = CONVERT(BINARY(CONVERT(long_description_nl USING latin1)) USING utf8mb4)
WHERE long_description_nl IS NOT NULL AND (HEX(long_description_nl) LIKE '%C383%' OR HEX(long_description_nl) LIKE '%C382%');

-- ============================================================
-- PHASE 2: Restore the 21 signs damaged by accidental double-conversion
-- These rows had correct data that was double-converted to '?????'
-- Restoring from backup JSON and signs.json (authoritative sources)
-- ============================================================

-- 2a: Restore Arabic (name_ar, description_ar, long_description_ar)
-- Part 1: Restore 20 damaged signs (all 3 Arabic columns)
UPDATE traffic_signs SET name_ar='ممنوع الوقوف', description_ar='ممنوع الوقوف', long_description_ar='تشير هذه العلامة المرورية إلى أن وقوف السيارات محظور في هذا الموقع، ولكن يسمح بالتوقف المؤقت للسماح للركاب بالدخول أو الخروج.' WHERE sign_code='E1';
UPDATE traffic_signs SET name_ar='لا توقف ومواقف السيارات', description_ar='لا توقف ومواقف السيارات', long_description_ar='تشير هذه العلامة المرورية إلى أن التوقف والوقوف ممنوع تماماً في هذا الموقع لأي سبب من الأسباب. المخالفة تؤدي إلى غرامة مرورية.' WHERE sign_code='E3';
UPDATE traffic_signs SET name_ar='ممنوع ركن السيارات من 1 إلى 15 من الشهر', description_ar='ممنوع ركن السيارات من 1 إلى 15 من الشهر', long_description_ar='تشير هذه العلامة المرورية إلى منع الوقوف خلال النصف الأول من كل شهر على هذا الجانب من الطريق. وتهدف هذه اللائحة إلى المحافظة على انسيابية حركة المرور ومنع الطريق من الميل إلى أحد الجانبين.' WHERE sign_code='E5';
UPDATE traffic_signs SET name_ar='ممنوع ركن السيارات من يوم 16 حتى نهاية الشهر', description_ar='ممنوع ركن السيارات من يوم 16 حتى نهاية الشهر', long_description_ar='تشير هذه العلامة المرورية إلى منع الوقوف خلال النصف الثاني من كل شهر (من اليوم 16 إلى يوم 31) على هذا الجانب من الطريق. وتهدف هذه اللائحة إلى الحفاظ على تدفق حركة المرور.' WHERE sign_code='E7';
UPDATE traffic_signs SET name_ar='مواقف للسيارات الكهربائية', description_ar='مواقف للسيارات الكهربائية', long_description_ar='تشير هذه العلامة المرورية إلى أنه يسمح بوقوف السيارات الكهربائية فقط. هذه المساحة مخصصة حصريًا للسيارات التي تعمل بالطاقة الكهربائية وغالبًا ما تكون مجهزة بنقطة شحن.' WHERE sign_code='E9a';
UPDATE traffic_signs SET name_ar='وقوف السيارات مسموح به', description_ar='وقوف السيارات مسموح به', long_description_ar='تشير هذه العلامة المرورية إلى السماح بوقوف جميع أنواع المركبات دون استثناء. ولا يقتصر على نوع معين من المركبات.' WHERE sign_code='E9a-v2';
UPDATE traffic_signs SET name_ar='مكان لوقوف السيارات للشحن الكهربائي', description_ar='مكان لوقوف السيارات للشحن الكهربائي', long_description_ar='تشير إشارة المرور هذه إلى أن مكان ركن السيارة مخصص للسيارات الكهربائية التي تحتاج إلى الشحن. يجب أن تكون السيارة متصلة بمحطة الشحن أثناء وقوفها.' WHERE sign_code='E9a-v3';
UPDATE traffic_signs SET name_ar='وقوف السيارات لفترة محدودة مع قرص وقوف السيارات', description_ar='وقوف السيارات لفترة محدودة مع قرص وقوف السيارات', long_description_ar='يُسمح بوقوف السيارات هنا لفترة محدودة (بحد أقصى 30 دقيقة). مطلوب قرص وقوف السيارات. لا يسمح بتمديد وقت وقوف السيارات. إذا كنت ترغب في البقاء لفترة أطول، يجب عليك مغادرة مكان وقوف السيارات والعودة في وقت لاحق.' WHERE sign_code='E9a-v6';
UPDATE traffic_signs SET name_ar='مواقف سيارات للأشخاص ذوي الإعاقة', description_ar='مواقف سيارات للأشخاص ذوي الإعاقة', long_description_ar='مكان ركن السيارات هذا مخصص للأشخاص الذين يحملون بطاقة إعاقة رسمية صادرة عن الحكومة. لا يُسمح للمركبات الأخرى بالوقوف هنا. لا يُسمح بالتوقف المؤقت إلا في حالة بقاء السائق خلف عجلة القيادة.' WHERE sign_code='E9a-v7';
UPDATE traffic_signs SET name_ar='E9a مسموح بوقوف السيارات', description_ar='E9a مسموح بوقوف السيارات', long_description_ar='علامة وقوف السيارات: اتبع قواعد وقوف السيارات المشار إليها.' WHERE sign_code='E9a-v10';
UPDATE traffic_signs SET name_ar='مواقف للسيارات فقط', description_ar='مواقف للسيارات فقط', long_description_ar='تشير هذه العلامة المرورية إلى أن هذا المكان مخصص حصراً للسيارات الخاصة الصغيرة التي يبلغ وزنها الأقصى 3.5 طن. لا يُسمح للشاحنات أو الحافلات التي يزيد وزنها عن 3.5 طن بالوقوف هنا.' WHERE sign_code='E9b';
UPDATE traffic_signs SET name_ar='مواقف للشاحنات فقط', description_ar='مواقف للشاحنات فقط', long_description_ar='تشير إشارة المرور هذه إلى أن مكان ركن السيارات هذا مخصص حصراً للشاحنات الخفيفة لنقل البضائع. لا يُسمح لجميع المركبات الأخرى بالوقوف هنا.' WHERE sign_code='E9c';
UPDATE traffic_signs SET name_ar='مواقف للسيارات للحافلات فقط', description_ar='مواقف للسيارات للحافلات فقط', long_description_ar='تشير هذه الشاخصة المرورية إلى أن هذا المكان لوقوف السيارات مخصص حصراً لحافلات النقل العام أو الحافلات السياحية. يحظر على جميع المركبات الأخرى الوقوف هنا.' WHERE sign_code='E9d';
UPDATE traffic_signs SET name_ar='وقوف السيارات الإلزامي على حافة أو الرصيف', description_ar='وقوف السيارات الإلزامي على حافة أو الرصيف', long_description_ar='تشير هذه العلامة المرورية إلى أنه يجب على السائقين ركن سيارتهم بشكل كامل على الرصيف. يمنع الوقوف بشكل جزئي على الطريق أو في وسطه كما هو موضح في الشاخصة.' WHERE sign_code='E9e';
UPDATE traffic_signs SET name_ar='ركن السيارة بشكل جزئي على الحافة أو الرصيف', description_ar='ركن السيارة بشكل جزئي على الحافة أو الرصيف', long_description_ar='تتطلب هذه العلامة المرورية من السائقين ركن سيارتهم جزئيًا على الرصيف، مع وضع بعض العجلات على الرصيف والباقي على الطريق. وعادة ما تستخدم هذه الطريقة على الطرق الضيقة لتسهيل حركة المرور.' WHERE sign_code='E9f';
UPDATE traffic_signs SET name_ar='وقوف السيارات الإلزامية على الطريق', description_ar='وقوف السيارات الإلزامية على الطريق', long_description_ar='تتطلب هذه العلامة المرورية من السائقين ركن سياراتهم بشكل كامل على الطريق. يمنع منعاً باتاً الصعود على الرصيف ولو جزئياً. ويهدف ذلك إلى حماية الأرصفة للمشاة وضمان سلامتهم.' WHERE sign_code='E9g';
UPDATE traffic_signs SET name_ar='E9g وقوف السيارات الإلزامي على الطريق', description_ar='E9g وقوف السيارات الإلزامي على الطريق', long_description_ar='علامة وقوف السيارات: اتبع قواعد وقوف السيارات المشار إليها.' WHERE sign_code='E9g-v1';
UPDATE traffic_signs SET name_ar='موقف سيارات لعربات الكارافانات فقط', description_ar='موقف سيارات لعربات الكارافانات فقط', long_description_ar='مساحة وقوف السيارات هذه مخصصة حصريًا لعربات الكارافانات والكرفانات المخصصة للتخييم والرحلات الطويلة. لا يُسمح للمركبات العادية بالوقوف هنا.' WHERE sign_code='E9h';
UPDATE traffic_signs SET name_ar='مواقف للدراجات النارية فقط', description_ar='مواقف للدراجات النارية فقط', long_description_ar='مساحة وقوف السيارات هذه مخصصة للدراجات النارية حصريًا. يمنع منعا باتا وقوف السيارات أو المركبات الأخرى هنا.' WHERE sign_code='E9i';
UPDATE traffic_signs SET name_ar='مواقف سيارات نصف شهرية', description_ar='مواقف سيارات نصف شهرية', long_description_ar='تنظم هذه العلامة المرورية وقوف السيارات حسب التاريخ من الشهر. من اليوم 1 إلى اليوم 15، يُسمح بالوقوف على الجانب الذي به أرقام فردية، ومن اليوم 16 إلى نهاية الشهر فقط على الجانب الذي يحتوي على أرقام زوجية.' WHERE sign_code='E11';
-- A1a: only name_ar damaged
UPDATE traffic_signs SET name_ar='منعطف خطير إلى اليسار' WHERE sign_code='A1a';

-- 2b: Restore French and Dutch (name_fr, description_fr, long_description_fr, name_nl, description_nl, long_description_nl)
UPDATE traffic_signs SET name_fr='Virage dangereux à gauche', description_fr='Virage dangereux à gauche.', long_description_fr='Avertissement d''un virage dangereux à gauche à environ 150 mètres. Réduisez votre vitesse et soyez attentif.', name_nl='Gevaarlijke bocht naar links', description_nl='Waarschuwing voor een gevaarlijke bocht, eerst naar links.', long_description_nl='Waarschuwing voor een gevaarlijke bocht naar links op ongeveer 150 meter afstand. Verminder uw snelheid en let goed op.' WHERE sign_code='A1a';
UPDATE traffic_signs SET name_fr='Interdiction de stationnement', description_fr='Stationnement interdit.', long_description_fr='Ce panneau indique que le stationnement est interdit à cet endroit, mais un arrêt temporaire pour faire monter ou descendre des passagers est autorisé.', name_nl='Parkeerverbod', description_nl='Verboden te parkeren.', long_description_nl='Dit verkeersbord geeft aan dat parkeren verboden is op deze plaats, maar tijdelijk stilstaan om passagiers te laten in- of uitstappen is wel toegestaan.' WHERE sign_code='E1';
UPDATE traffic_signs SET name_fr='Arrêt et stationnement interdits', description_fr='Arrêt et stationnement interdits.', long_description_fr='Ce panneau indique que l arrêt et le stationnement sont totalement interdits à cet endroit, quelle que soit la raison. Une infraction entraîne une amende.', name_nl='Stilstaan en parkeren verboden', description_nl='Stilstaan en parkeren verboden.', long_description_nl='Dit verkeersbord geeft aan dat stilstaan en parkeren volledig verboden zijn op deze plaats, om welke reden dan ook. Overtreding leidt tot een verkeersboete.' WHERE sign_code='E3';
UPDATE traffic_signs SET name_fr='Interdiction de stationnement du 1er au 15 du mois', description_fr='Stationnement interdit de ce côté du 1er au 15 du mois.', long_description_fr='Ce panneau indique que le stationnement est interdit pendant la première moitié de chaque mois de ce côté de la route. Cette réglementation vise à maintenir la fluidité du trafic et à éviter que la route ne penche d''un seul côté.', name_nl='Parkeerverbod van de 1e tot de 15e van de maand', description_nl='Parkeren is toegelaten.', long_description_nl='Dit verkeersbord geeft aan dat parkeren verboden is gedurende de eerste helft van elke maand aan deze kant van de weg. Deze regeling is bedoeld om de doorstroming van het verkeer te behouden en te voorkomen dat de weg naar één kant helt.' WHERE sign_code='E5';
UPDATE traffic_signs SET name_fr='Interdiction de stationnement du 16 à la fin du mois', description_fr='Stationnement interdit de ce côté du 16 à la fin du mois.', long_description_fr='Ce panneau indique que le stationnement est interdit pendant la deuxième moitié de chaque mois (du 16 au 31) de ce côté de la route. Cette réglementation vise à maintenir la fluidité du trafic.', name_nl='Parkeerverbod van de 16e tot het einde van de maand', description_nl='Parkeren is toegelaten mits gebruik van een parkeerschijf.', long_description_nl='Dit verkeersbord geeft aan dat parkeren verboden is gedurende de tweede helft van elke maand (van de 16e tot de 31e) aan deze kant van de weg. Deze regeling is bedoeld om de doorstroming van het verkeer te behouden.' WHERE sign_code='E7';
UPDATE traffic_signs SET name_fr='Parking pour véhicules électriques', description_fr='Stationnement autorisé.', long_description_fr='Ce panneau de signalisation indique que le stationnement est uniquement autorisé pour les véhicules électriques. Cet emplacement est exclusivement destiné aux voitures fonctionnant à l''énergie électrique et souvent équipé d''une borne de recharge.', name_nl='Parkeerplaats voor elektrische voertuigen', description_nl='Parkeren is toegelaten gedurende een beperkte tijd.', long_description_nl='Dit verkeersbord geeft aan dat parkeren alleen is toegestaan voor elektrische voertuigen. Deze plek is exclusief bestemd voor auto''s die op elektrische energie rijden en vaak voorzien van een laadpunt.' WHERE sign_code='E9a';
UPDATE traffic_signs SET name_fr='Stationnement autorisé', description_fr='Stationnement autorisé', long_description_fr='Ce panneau de signalisation indique que le stationnement est autorisé pour tous les types de véhicules sans exception. Il n''est pas limité à un type de véhicule spécifique.', name_nl='Parkeren toegelaten', description_nl='Parkeren toegelaten', long_description_nl='Dit verkeersbord geeft aan dat parkeren is toegestaan voor alle soorten voertuigen zonder uitzondering. Het is niet beperkt tot een specifiek type voertuig.' WHERE sign_code='E9a-v2';
UPDATE traffic_signs SET name_fr='Place de stationnement pour recharge électrique', description_fr='Place de stationnement pour recharge électrique', long_description_fr='Ce panneau indique que la place de stationnement est réservée aux véhicules électriques qui doivent se recharger. La voiture doit être branchée à la borne de recharge pendant le stationnement.', name_nl='Parkeerplaats voor elektrisch opladen', description_nl='Parkeerplaats voor elektrisch opladen', long_description_nl='Dit verkeersbord geeft aan dat de parkeerplaats is gereserveerd voor elektrische voertuigen die moeten opladen. De auto moet aangesloten zijn op de laadpaal tijdens het parkeren.' WHERE sign_code='E9a-v3';
UPDATE traffic_signs SET name_fr='Stationnement limite dans le temps avec disque de stationnement', description_fr='Stationnement limite dans le temps avec disque de stationnement', long_description_fr='Le stationnement est autorise ici pour une duree limitee (30 minutes maximum). Un disque de stationnement est obligatoire. La prolongation du temps de stationnement n est pas autorisee; si vous souhaitez rester plus longtemps, vous devez quitter la place et revenir plus tard.', name_nl='Parkeren beperkt in tijd met parkeerschijf', description_nl='Parkeren beperkt in tijd met parkeerschijf', long_description_nl='Parkeren is hier toegestaan voor een beperkte tijd (maximaal 30 minuten). Een parkeerschijf is verplicht. Verlenging van de parkeertijd is niet toegestaan; als u langer wilt blijven, moet u de parkeerplaats verlaten en later terugkeren.' WHERE sign_code='E9a-v6';
UPDATE traffic_signs SET name_fr='Stationnement pour personnes handicapees', description_fr='Stationnement pour personnes handicapees', long_description_fr='Cette place de stationnement est reservee aux personnes detenant une carte de handicap officielle delivree par l etat. Les autres vehicules ne peuvent pas stationner ici. Un arret temporaire n est autorise que si le conducteur reste au volant.', name_nl='Parkeren voor mindervaliden', description_nl='Parkeren voor mindervaliden', long_description_nl='Deze parkeerplaats is gereserveerd voor personen met een officiele gehandicaptenkaart uitgegeven door de overheid. Andere voertuigen mogen hier niet parkeren. Tijdelijk stilstaan is alleen toegestaan als de bestuurder achter het stuur blijft zitten.' WHERE sign_code='E9a-v7';
UPDATE traffic_signs SET name_fr='E9a Stationnement autorisé', description_fr='E9a Stationnement autorisé', long_description_fr='Panneau de stationnement : suivez les règles de stationnement indiquées.', name_nl='E9a - Parkeerzone speciale bestemming', description_nl='E9a - Parkeerzone speciale bestemming', long_description_nl='Parkeerbord: Parkeren toegelaten. Volg de aangegeven parkeerregels.' WHERE sign_code='E9a-v10';
UPDATE traffic_signs SET name_fr='Stationnement reserve aux voitures', description_fr='Stationnement reserve aux voitures', long_description_fr='Ce panneau indique que cette place de stationnement est exclusivement reservee aux petites voitures particulieres d un poids maximal de 3,5 tonnes. Les camions ou bus de plus de 3,5 tonnes ne peuvent pas stationner ici.', name_nl='Parkeren uitsluitend voor auto s', description_nl='Parkeren enkel toegestaan voor motorfietsen, personenauto''s, auto''s dubbel gebruik, minibussen.', long_description_nl='Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor kleine personenauto s met een maximaal gewicht van 3,5 ton. Vrachtwagens of bussen zwaarder dan 3,5 ton mogen hier niet parkeren.' WHERE sign_code='E9b';
UPDATE traffic_signs SET name_fr='Stationnement réservé aux camions', description_fr='Stationnement réservé aux camions', long_description_fr='Ce panneau indique que cette place de stationnement est exclusivement réservée aux camionnettes légères pour le transport de marchandises. Tous les autres véhicules ne peuvent pas stationner ici.', name_nl='Parkeren uitsluitend voor vrachtwagens', description_nl='Parkeren enkel toegestaan voor lichte vrachtauto''s, vrachtauto''s.', long_description_nl='Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor lichte vrachtwagens voor het vervoer van goederen. Alle andere voertuigen mogen hier niet parkeren.' WHERE sign_code='E9c';
UPDATE traffic_signs SET name_fr='Stationnement réservé aux autocars', description_fr='Stationnement réservé aux autocars', long_description_fr='Ce panneau indique que cette place de stationnement est exclusivement réservée aux bus de transport public ou aux autocars touristiques. Il est interdit à tout autre véhicule de stationner ici.', name_nl='Parkeren uitsluitend voor autocars', description_nl='Parkeren enkel toegestaan voor autocars.', long_description_nl='Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor bussen van het openbaar vervoer of touringcars. Het is voor alle andere voertuigen verboden hier te parkeren.' WHERE sign_code='E9d';
UPDATE traffic_signs SET name_fr='Stationnement obligatoire sur l accotement ou le trottoir', description_fr='Stationnement obligatoire sur l accotement ou le trottoir', long_description_fr='Ce panneau indique que les conducteurs doivent garer leur vehicule entierement sur le trottoir. Le stationnement partiel sur la chaussee ou au milieu n est pas autorise, comme indique sur le panneau.', name_nl='Verplicht parkeren op de berm of op het trottoir', description_nl='Verplicht parkeren op de berm of op het trottoir.', long_description_nl='Dit verkeersbord geeft aan dat bestuurders hun voertuig volledig op het trottoir moeten parkeren. Gedeeltelijk parkeren op de rijbaan of in het midden ervan is niet toegestaan, zoals aangegeven op het bord.' WHERE sign_code='E9e';
UPDATE traffic_signs SET name_fr='Stationnement obligatoire partiellement sur l accotement ou le trottoir', description_fr='Stationnement obligatoire partiellement sur l accotement ou le trottoir', long_description_fr='Ce panneau oblige les conducteurs a garer leur vehicule partiellement sur le trottoir, avec certaines roues sur le trottoir et le reste sur la chaussee. Cette methode est generalement utilisee sur les routes etroites pour faciliter la circulation.', name_nl='Verplicht parkeren deels op de berm of op het trottoir', description_nl='Verplicht parkeren deels op de berm of op het trottoir.', long_description_nl='Dit verkeersbord verplicht bestuurders om hun voertuig gedeeltelijk op het trottoir te parkeren, waarbij enkele wielen op het trottoir staan en de rest op de rijbaan. Deze methode wordt meestal gebruikt op smalle wegen om het verkeer te vergemakkelijken.' WHERE sign_code='E9f';
UPDATE traffic_signs SET name_fr='Stationnement obligatoire sur la chaussee', description_fr='Stationnement obligatoire sur la chaussee', long_description_fr='Ce panneau oblige les conducteurs a garer leur vehicule entierement sur la chaussee. Il est absolument interdit de monter sur le trottoir, meme partiellement. Cela vise a proteger les trottoirs reserves aux pietons et a garantir leur securite.', name_nl='Verplicht parkeren op de rijbaan', description_nl='Verplicht parkeren op de rijbaan.', long_description_nl='Dit verkeersbord verplicht bestuurders om hun voertuig volledig op de rijbaan te parkeren. Het is absoluut verboden om op het trottoir te rijden, zelfs gedeeltelijk. Dit is bedoeld om de trottoirs voor voetgangers te beschermen en hun veiligheid te garanderen.' WHERE sign_code='E9g';
UPDATE traffic_signs SET name_fr='E9g Stationnement obligatoire sur la route', description_fr='E9g Stationnement obligatoire sur la route', long_description_fr='Panneau de stationnement : suivez les règles de stationnement indiquées.', name_nl='E9g - Verplicht parkeren op de rijbaan variant 2', description_nl='E9g - Verplicht parkeren op de rijbaan variant 2', long_description_nl='Parkeerbord: Parkeren uitsluitend voor fietsen en bromfietsen. Volg de aangegeven parkeerregels.' WHERE sign_code='E9g-v1';
UPDATE traffic_signs SET name_fr='Stationnement reserve aux camping-cars', description_fr='Stationnement reserve aux camping-cars', long_description_fr='Cette place de stationnement est exclusivement reservee aux camping-cars et caravanes destines au camping et aux longs voyages. Il n est pas permis aux vehicules ordinaires de stationner ici.', name_nl='Parkeren uitsluitend voor kampeerauto s', description_nl='Parkeren voorbehouden voor personen met handicap.', long_description_nl='Deze parkeerplaats is uitsluitend bestemd voor kampeerauto s en caravans die bedoeld zijn voor kamperen en lange reizen. Het is niet toegestaan voor gewone voertuigen om hier te parkeren.' WHERE sign_code='E9h';
UPDATE traffic_signs SET name_fr='Stationnement reserve aux motos', description_fr='Stationnement reserve aux motos', long_description_fr='Cette place de stationnement est exclusivement reservee aux motos. Il est strictement interdit aux voitures ou autres vehicules de stationner ici.', name_nl='Parkeren uitsluitend voor motorfietsen', description_nl='Parkeren enkel toegestaan voor motorfietsen.', long_description_nl='Deze parkeerplaats is exclusief bestemd voor motorfietsen. Het is strikt verboden voor auto s of andere voertuigen om hier te parkeren.' WHERE sign_code='E9i';
UPDATE traffic_signs SET name_fr='Stationnement semi-mensuel', description_fr='Stationnement semi-mensuel', long_description_fr='Ce panneau réglemente le stationnement selon la date du mois. Du 1er au 15, le stationnement est autorisé du côté des numéros impairs, et du 16 à la fin du mois uniquement du côté des numéros pairs.', name_nl='Halfmaandelijks parkeren', description_nl='Parkeren is afwisselend toegelaten afhankelijk van de periode.', long_description_nl='Dit verkeersbord regelt het parkeren volgens de datum van de maand. Van de 1e tot de 15e is parkeren toegestaan aan de kant met oneven huisnummers, en van de 16e tot het einde van de maand alleen aan de kant met even huisnummers.' WHERE sign_code='E11';