-- V12__Add_Practice_Questions_Lessons_16_20.sql
-- Practice Questions for Lessons 16-20
-- All questions have exactly 4 options (required by schema)

INSERT INTO practice_questions (
    lesson_id,
    question_ar, question_en, question_nl, question_fr,
    option1_ar, option1_en, option1_nl, option1_fr,
    option2_ar, option2_en, option2_nl, option2_fr,
    option3_ar, option3_en, option3_nl, option3_fr,
    option4_ar, option4_en, option4_nl, option4_fr,
    correct_answer,
    explanation_ar, explanation_en, explanation_nl, explanation_fr,
    display_order, is_active, created_at, updated_at
) VALUES

-- Lesson 16: Highways

(16,'ما هي السرعة القصوى على الطرق السريعة في بلجيكا؟',
'What is the maximum speed on highways in Belgium?',
'Wat is de maximumsnelheid op snelwegen in België?',
'Quelle est la vitesse maximale sur les autoroutes en Belgique?',
'100 كم/س','100 km/h','100 km/u','100 km/h',
'120 كم/س','120 km/h','120 km/u','120 km/h',
'130 كم/س','130 km/h','130 km/u','130 km/h',
'90 كم/س','90 km/h','90 km/u','90 km/h',
2,
'السرعة القصوى على الطرق السريعة هي 120 كم/س','The maximum speed on highways is 120 km/h','De maximumsnelheid op snelwegen is 120 km/u','La vitesse maximale sur autoroutes est 120 km/h',
1,TRUE,NOW(),NOW()),

(16,'أي حارة تستخدم للقيادة العادية على الطريق السريع؟',
'Which lane should be used for normal driving on the highway?',
'Welke rijstrook moet worden gebruikt voor normaal rijden op de snelweg?',
'Quelle voie doit être utilisée pour la conduite normale sur l\'autoroute?',
'الحارة اليمنى','Right lane','Rechterbaan','Voie de droite',
'الحارة اليسرى','Left lane','Linkerbaan','Voie de gauche',
'أي حارة','Any lane','Elke baan','N\'importe quelle voie',
'الحارة الوسطى','Middle lane','Middenbaan','Voie du milieu',
1,
'يجب استخدام الحارة اليمنى للقيادة العادية','The right lane must be used for normal driving','De rechterbaan moet worden gebruikt voor normaal rijden','La voie de droite doit être utilisée pour la conduite normale',
2,TRUE,NOW(),NOW()),

(16,'هل يجوز التوقف على الطريق السريع؟',
'Is stopping allowed on the highway?',
'Is stoppen toegestaan op de snelweg?',
'L\'arrêt est-il autorisé sur l\'autoroute?',
'نعم دائماً','Yes always','Ja altijd','Oui toujours',
'فقط في حالات الطوارئ','Only in emergencies','Alleen in noodgevallen','Seulement en cas d\'urgence',
'لا أبداً','Never','Nooit','Jamais',
'فقط ليلاً','Only at night','Alleen \'s nachts','Seulement la nuit',
2,
'التوقف مسموح فقط في حالات الطوارئ','Stopping is only allowed in emergencies','Stoppen is alleen toegestaan in noodgevallen','L\'arrêt n\'est autorisé qu\'en cas d\'urgence',
3,TRUE,NOW(),NOW()),

-- Lesson 17: Traffic Signs

(17,'ماذا يعني الإشارة الدائرية الحمراء مع خط أبيض؟',
'What does the circular red sign with a white line mean?',
'Wat betekent het ronde rode bord met een witte streep?',
'Que signifie le panneau circulaire rouge avec une ligne blanche?',
'ممنوع الدخول','No entry','Verboden in te rijden','Entrée interdite',
'قف','Stop','Stop','Arrêt',
'طريق مغلق','Road closed','Weg gesloten','Route fermée',
'ممنوع الوقوف','No stopping','Verboden te stoppen','Arrêt interdit',
1,
'الإشارة الدائرية الحمراء مع خط أبيض تعني ممنوع الدخول','Circular red sign with white line means no entry','Rond rood bord met witte streep betekent verboden in te rijden','Panneau circulaire rouge avec ligne blanche signifie entrée interdite',
1,TRUE,NOW(),NOW()),

(17,'ماذا تعني الإشارة المثلثة مع حافة حمراء؟',
'What does a triangular sign with a red border mean?',
'Wat betekent een driehoekig bord met een rode rand?',
'Que signifie un panneau triangulaire avec un bord rouge?',
'تحذير','Warning','Waarschuwing','Avertissement',
'إلزامي','Mandatory','Verplicht','Obligatoire',
'معلومات','Information','Informatie','Information',
'ممنوع','Prohibition','Verboden','Interdiction',
1,
'الإشارة المثلثة مع حافة حمراء هي إشارة تحذير','Triangular sign with red border is a warning sign','Driehoekig bord met rode rand is een waarschuwingsbord','Panneau triangulaire avec bord rouge est un panneau d\'avertissement',
2,TRUE,NOW(),NOW()),

-- Lesson 18: Right of Way

(18,'من له الأولوية في دوار؟',
'Who has priority in a roundabout?',
'Wie heeft voorrang op een rotonde?',
'Qui a la priorité sur un rond-point?',
'السيارات داخل الدوار','Vehicles in the roundabout','Voertuigen in de rotonde','Véhicules dans le rond-point',
'السيارات الداخلة','Vehicles entering','Voertuigen die invoegen','Véhicules entrant',
'السيارات الكبيرة','Large vehicles','Grote voertuigen','Grands véhicules',
'لا أحد','No one','Niemand','Personne',
1,
'السيارات داخل الدوار لها الأولوية','Vehicles in the roundabout have priority','Voertuigen in de rotonde hebben voorrang','Les véhicules dans le rond-point ont la priorité',
1,TRUE,NOW(),NOW()),

(18,'ماذا تفعل عند إشارة المرور الصفراء؟',
'What should you do at a yellow traffic light?',
'Wat moet u doen bij een geel verkeerslicht?',
'Que devez-vous faire à un feu de circulation jaune?',
'التوقف إذا كان آمناً','Stop if safe','Stoppen als het veilig is','Arrêter si c\'est sûr',
'تسريع','Speed up','Versnellen','Accélérer',
'الاستمرار بنفس السرعة','Continue at same speed','Doorgaan met dezelfde snelheid','Continuer à la même vitesse',
'التوقف مباشرة','Stop immediately','Onmiddellijk stoppen','Arrêter immédiatement',
1,
'يجب التوقف عند الضوء الأصفر إذا كان آمناً','You must stop at yellow light if safe','U moet stoppen bij geel licht als het veilig is','Vous devez vous arrêter au feu jaune si c\'est sûr',
2,TRUE,NOW(),NOW()),

-- Lesson 19: Parking

(19,'أين يمنع الوقوف؟',
'Where is parking prohibited?',
'Waar is parkeren verboden?',
'Où le stationnement est-il interdit?',
'قرب تقاطع','Near intersection','Bij kruispunt','Près d\'un carrefour',
'في موقف السيارات','In parking lot','Op parkeerplaats','Dans un parking',
'في الشارع','On the street','Op straat','Dans la rue',
'قرب المنزل','Near home','Bij huis','Près de la maison',
1,
'الوقوف ممنوع قرب التقاطعات','Parking is prohibited near intersections','Parkeren is verboden bij kruispunten','Le stationnement est interdit près des carrefours',
1,TRUE,NOW(),NOW()),

(19,'كم المسافة من ممر المشاة لوقوف السيارة؟',
'What is the distance from a pedestrian crossing to park?',
'Wat is de afstand van een zebrapad om te parkeren?',
'Quelle est la distance d\'un passage piéton pour se garer?',
'5 متر','5 meters','5 meter','5 mètres',
'10 متر','10 meters','10 meter','10 mètres',
'15 متر','15 meters','15 meter','15 mètres',
'لا يوجد حد','No limit','Geen limiet','Pas de limite',
1,
'يجب ترك مسافة 5 أمتار على الأقل من ممر المشاة','Must leave at least 5 meters from pedestrian crossing','Moet minstens 5 meter van zebrapad laten','Doit laisser au moins 5 mètres du passage piéton',
2,TRUE,NOW(),NOW()),

-- Lesson 20: Safety

(20,'متى يجب استخدام حزام الأمان؟',
'When should you wear a seatbelt?',
'Wanneer moet u een veiligheidsgordel dragen?',
'Quand devez-vous porter une ceinture de sécurité?',
'دائماً','Always','Altijd','Toujours',
'فقط على الطرق السريعة','Only on highways','Alleen op snelwegen','Seulement sur autoroutes',
'فقط في المدينة','Only in city','Alleen in de stad','Seulement en ville',
'فقط ليلاً','Only at night','Alleen \'s nachts','Seulement la nuit',
1,
'يجب استخدام حزام الأمان دائماً','Seatbelt must be worn always','Veiligheidsgordel moet altijd worden gedragen','La ceinture de sécurité doit toujours être portée',
1,TRUE,NOW(),NOW()),

(20,'ما هو الحد الأدنى لعمق المداس في الإطارات؟',
'What is the minimum tread depth for tires?',
'Wat is de minimum profieldiepte voor banden?',
'Quelle est la profondeur minimale de la bande de roulement?',
'1.6 مم','1.6 mm','1.6 mm','1.6 mm',
'2.0 مم','2.0 mm','2.0 mm','2.0 mm',
'3.0 مم','3.0 mm','3.0 mm','3.0 mm',
'لا يوجد حد','No limit','Geen limiet','Pas de limite',
1,
'الحد الأدنى لعمق المداس هو 1.6 ملم','Minimum tread depth is 1.6 mm','Minimum profieldiepte is 1.6 mm','La profondeur minimale est 1.6 mm',
2,TRUE,NOW(),NOW());
