-- ==========================================================================
-- V184 — Developer Skills Assessment System — Seed: Questions & Choices
-- 171 questions (19 categories × 3 difficulties × 3 questions).
-- Full translations (en/ar/nl/fr) for cats 1,2,3,13; EN-only for others.
-- Question IDs are explicit so choice inserts can reference them directly.
-- ==========================================================================

-- ──────────────────────────────────────────────────────────────────────────
-- QUESTIONS INSERT
-- ──────────────────────────────────────────────────────────────────────────

INSERT INTO dev_exam_questions
  (id, category_id, difficulty, question_en, question_ar, question_nl, question_fr, explanation_en)
VALUES

-- ═══ Category 1: restapi — BEGINNER ══════════════════════════════════════
(1,1,'BEGINNER',
 'What does REST stand for?',
 'ماذا تعني REST اختصاراً؟',
 'Waar staat REST voor?',
 'Que signifie l''acronyme REST?',
 'REST stands for Representational State Transfer, an architectural style for distributed hypermedia systems.'),

(2,1,'BEGINNER',
 'Which HTTP method retrieves data without modifying the resource?',
 'أي طريقة HTTP تسترجع البيانات دون تعديل المورد؟',
 'Welke HTTP-methode haalt gegevens op zonder de resource te wijzigen?',
 'Quelle méthode HTTP récupère des données sans modifier la ressource?',
 'GET is the safe and idempotent method for reading resources.'),

(3,1,'BEGINNER',
 'What HTTP status code indicates a successful response (OK)?',
 'ما رمز حالة HTTP الذي يشير إلى الاستجابة الناجحة (OK)؟',
 'Welke HTTP-statuscode duidt op een succesvolle respons (OK)?',
 'Quel code de statut HTTP indique une réponse réussie (OK)?',
 '200 OK is the standard success response for GET, PUT, and PATCH requests.'),

-- ═══ Category 1: restapi — INTERMEDIATE ══════════════════════════════════
(4,1,'INTERMEDIATE',
 'What makes an HTTP method "idempotent"?',
 'ما الذي يجعل طريقة HTTP "idempotent"؟',
 'Wat maakt een HTTP-methode "idempotent"?',
 'Qu''est-ce qui rend une méthode HTTP "idempotente"?',
 'An idempotent method can be called multiple times with the same effect as a single call.'),

(5,1,'INTERMEDIATE',
 'Which HTTP method is NOT idempotent by definition?',
 'أي طريقة HTTP ليست idempotent بطبيعتها؟',
 'Welke HTTP-methode is van nature niet idempotent?',
 'Quelle méthode HTTP n''est pas idempotente par définition?',
 'POST creates a new resource each time it is called, so multiple calls produce different results.'),

(6,1,'INTERMEDIATE',
 'What is the purpose of the HTTP Content-Type header?',
 'ما الغرض من رأس HTTP Content-Type؟',
 'Wat is het doel van de HTTP Content-Type header?',
 'Quel est le rôle du header HTTP Content-Type?',
 'Content-Type tells the receiver the media type of the request or response body.'),

-- ═══ Category 1: restapi — ADVANCED ══════════════════════════════════════
(7,1,'ADVANCED',
 'What is HATEOAS in REST architecture?',
 'ما هو HATEOAS في معمارية REST؟',
 'Wat is HATEOAS in REST-architectuur?',
 'Qu''est-ce que HATEOAS dans l''architecture REST?',
 'HATEOAS (Hypermedia as the Engine of Application State) means responses include links to available next actions.'),

(8,1,'ADVANCED',
 'What is the meaning of HTTP status code 429?',
 'ماذا يشير رمز حالة HTTP 429؟',
 'Wat betekent HTTP-statuscode 429?',
 'Que signifie le code de statut HTTP 429?',
 '429 Too Many Requests indicates the client has exceeded the server''s rate limit.'),

(9,1,'ADVANCED',
 'Which HTTP method should be used for a partial update to a resource?',
 'أي طريقة HTTP يجب استخدامها للتحديثات الجزئية للمورد؟',
 'Welke HTTP-methode dient gebruikt te worden voor gedeeltelijke updates?',
 'Quelle méthode HTTP faut-il utiliser pour une mise à jour partielle d''une ressource?',
 'PATCH is designed for partial updates, while PUT replaces the entire resource.'),

-- ═══ Category 2: databaseintegration — BEGINNER ══════════════════════════
(10,2,'BEGINNER',
 'What does SQL stand for?',
 'ماذا تعني SQL اختصاراً؟',
 'Waar staat SQL voor?',
 'Que signifie l''acronyme SQL?',
 'SQL stands for Structured Query Language, used to manage and query relational databases.'),

(11,2,'BEGINNER',
 'Which SQL command is used to retrieve data from a table?',
 'أي أمر SQL يُستخدم لاسترداد البيانات من جدول؟',
 'Welk SQL-commando wordt gebruikt om gegevens uit een tabel op te halen?',
 'Quelle commande SQL est utilisée pour récupérer des données d''une table?',
 'SELECT retrieves rows from one or more tables based on a query.'),

(12,2,'BEGINNER',
 'What is a primary key in a database?',
 'ما هو المفتاح الأساسي في قاعدة البيانات؟',
 'Wat is een primaire sleutel in een database?',
 'Qu''est-ce qu''une clé primaire dans une base de données?',
 'A primary key is a column (or columns) that uniquely identifies each row in a table.'),

-- ═══ Category 2: databaseintegration — INTERMEDIATE ══════════════════════
(13,2,'INTERMEDIATE',
 'What is the N+1 query problem in ORM?',
 'ما هي مشكلة استعلامات N+1 في إطار ORM؟',
 'Wat is het N+1 query probleem in ORM?',
 'Qu''est-ce que le problème de requêtes N+1 dans un ORM?',
 'N+1 occurs when one query loads a list of entities and then one extra query fires per entity to load its relations.'),

(14,2,'INTERMEDIATE',
 'What does INNER JOIN return in SQL?',
 'ماذا يُعيد INNER JOIN في SQL؟',
 'Wat retourneert INNER JOIN in SQL?',
 'Que retourne INNER JOIN en SQL?',
 'INNER JOIN returns only the rows where there is a match in both joined tables.'),

(15,2,'INTERMEDIATE',
 'What is the primary purpose of database indexing?',
 'ما الغرض الأساسي من الفهرسة في قاعدة البيانات؟',
 'Wat is het primaire doel van database-indexering?',
 'Quel est l''objectif principal de l''indexation d''une base de données?',
 'Indexes speed up data retrieval by allowing the database to find rows without full table scans.'),

-- ═══ Category 2: databaseintegration — ADVANCED ══════════════════════════
(16,2,'ADVANCED',
 'What is database connection pooling?',
 'ما هو توحيد اتصالات قاعدة البيانات (Connection Pooling)؟',
 'Wat is database connection pooling?',
 'Qu''est-ce que le pooling de connexions de base de données?',
 'Connection pooling maintains a pool of open database connections that are reused, reducing overhead.'),

(17,2,'ADVANCED',
 'What is optimistic locking in a database?',
 'ما هو القفل المتفائل (Optimistic Locking) في قاعدة البيانات؟',
 'Wat is optimistic locking in een database?',
 'Qu''est-ce que le verrouillage optimiste dans une base de données?',
 'Optimistic locking assumes no conflict and checks for concurrent modification only at commit time.'),

(18,2,'ADVANCED',
 'What does the CAP theorem state about distributed databases?',
 'ماذا تقول نظرية CAP عن قواعد البيانات الموزعة؟',
 'Wat stelt het CAP-theorema over gedistribueerde databases?',
 'Que dit le théorème CAP sur les bases de données distribuées?',
 'CAP: a distributed system cannot simultaneously guarantee Consistency, Availability, and Partition tolerance.'),

-- ═══ Category 3: authentication — BEGINNER ════════════════════════════════
(19,3,'BEGINNER',
 'What does JWT stand for?',
 'ماذا تعني JWT اختصاراً؟',
 'Waar staat JWT voor?',
 'Que signifie l''acronyme JWT?',
 'JWT stands for JSON Web Token, a compact, self-contained way to transmit claims between parties.'),

(20,3,'BEGINNER',
 'What are the three parts of a JWT?',
 'ما هي الأجزاء الثلاثة لـ JWT؟',
 'Wat zijn de drie onderdelen van een JWT?',
 'Quelles sont les trois parties d''un JWT?',
 'A JWT consists of a Header, Payload, and Signature, each Base64Url-encoded and separated by dots.'),

(21,3,'BEGINNER',
 'Why should passwords be hashed before storage?',
 'لماذا يجب تجزئة كلمات المرور قبل التخزين؟',
 'Waarom moeten wachtwoorden worden gehasht voor opslag?',
 'Pourquoi les mots de passe doivent-ils être hachés avant stockage?',
 'Hashing is one-way and prevents passwords from being recovered if the database is compromised.'),

-- ═══ Category 3: authentication — INTERMEDIATE ════════════════════════════
(22,3,'INTERMEDIATE',
 'What is the difference between authentication and authorization?',
 'ما الفرق بين المصادقة (authentication) والتفويض (authorization)؟',
 'Wat is het verschil tussen authenticatie en autorisatie?',
 'Quelle est la différence entre authentification et autorisation?',
 'Authentication verifies who you are; authorization determines what you are allowed to do.'),

(23,3,'INTERMEDIATE',
 'What is the primary purpose of OAuth 2.0?',
 'ما الغرض الأساسي من OAuth 2.0؟',
 'Wat is het primaire doel van OAuth 2.0?',
 'Quel est l''objectif principal d''OAuth 2.0?',
 'OAuth 2.0 allows a user to grant a third-party application limited access to their resources without sharing credentials.'),

(24,3,'INTERMEDIATE',
 'What is a refresh token in OAuth 2.0?',
 'ما هو رمز التحديث (Refresh Token) في OAuth 2.0؟',
 'Wat is een refresh token in OAuth 2.0?',
 'Qu''est-ce qu''un refresh token dans OAuth 2.0?',
 'A refresh token is a long-lived credential used to obtain new short-lived access tokens without re-authentication.'),

-- ═══ Category 3: authentication — ADVANCED ════════════════════════════════
(25,3,'ADVANCED',
 'What does PKCE add to the OAuth 2.0 authorization code flow?',
 'ما الذي يُضيفه PKCE إلى تدفق رمز التفويض في OAuth 2.0؟',
 'Wat voegt PKCE toe aan de OAuth 2.0-autorisatiecodeflo?',
 'Que PKCE ajoute-t-il au flux de code d''autorisation OAuth 2.0?',
 'PKCE (Proof Key for Code Exchange) prevents authorization code interception attacks by using a code verifier and challenge.'),

(26,3,'ADVANCED',
 'What is the purpose of the nonce claim in OpenID Connect?',
 'ما الغرض من مطالبة nonce في OpenID Connect؟',
 'Wat is het doel van de nonce-claim in OpenID Connect?',
 'Quel est le rôle du claim "nonce" dans OpenID Connect?',
 'The nonce is a random value included in the authentication request and verified in the ID token to prevent replay attacks.'),

(27,3,'ADVANCED',
 'What characterizes multi-factor authentication (MFA)?',
 'ما الذي يُميز المصادقة متعددة العوامل (MFA)؟',
 'Wat kenmerkt multi-factor authenticatie (MFA)?',
 'Qu''est-ce qui caractérise l''authentification multi-facteurs (MFA)?',
 'MFA requires two or more independent verification factors from different categories: something you know, have, or are.'),

-- ═══ Category 4: authorization — BEGINNER ════════════════════════════════
(28,4,'BEGINNER',
 'What is Role-Based Access Control (RBAC)?',NULL,NULL,NULL,
 'RBAC assigns permissions to users based on their roles, simplifying permission management.'),

(29,4,'BEGINNER',
 'What does ACL stand for in access control?',NULL,NULL,NULL,
 'ACL stands for Access Control List, a list that specifies which subjects can perform which actions on a resource.'),

(30,4,'BEGINNER',
 'What does a permission define in an access control system?',NULL,NULL,NULL,
 'A permission defines what actions (read, write, delete) a subject is allowed to perform on a resource.'),

-- ═══ Category 4: authorization — INTERMEDIATE ════════════════════════════
(31,4,'INTERMEDIATE',
 'What is the principle of least privilege?',NULL,NULL,NULL,
 'Grant subjects only the minimum permissions they need to perform their assigned tasks.'),

(32,4,'INTERMEDIATE',
 'What is Attribute-Based Access Control (ABAC)?',NULL,NULL,NULL,
 'ABAC makes access decisions based on attributes of the user, resource, and environment.'),

(33,4,'INTERMEDIATE',
 'What is a security policy in ABAC?',NULL,NULL,NULL,
 'A policy defines the rules that combine attributes to determine whether access should be granted.'),

-- ═══ Category 4: authorization — ADVANCED ════════════════════════════════
(34,4,'ADVANCED',
 'What is claims-based authorization?',NULL,NULL,NULL,
 'Claims-based authorization uses named values in a security token (claims) to make access decisions.'),

(35,4,'ADVANCED',
 'What is a Policy Decision Point (PDP)?',NULL,NULL,NULL,
 'A PDP is the component responsible for evaluating access control policies and granting or denying access.'),

(36,4,'ADVANCED',
 'What is permission delegation?',NULL,NULL,NULL,
 'Delegation allows a user to temporarily grant their permissions to another entity to act on their behalf.'),

-- ═══ Category 5: frontend — BEGINNER ═════════════════════════════════════
(37,5,'BEGINNER',
 'What is the Virtual DOM?',NULL,NULL,NULL,
 'The Virtual DOM is an in-memory copy of the real DOM; frameworks diff it to compute minimal real DOM updates.'),

(38,5,'BEGINNER',
 'What is component-based architecture in frontend development?',NULL,NULL,NULL,
 'UI is built from independent, reusable components that encapsulate their own state and presentation.'),

(39,5,'BEGINNER',
 'What is a Single Page Application (SPA)?',NULL,NULL,NULL,
 'An SPA loads a single HTML document and dynamically updates content without full page reloads.'),

-- ═══ Category 5: frontend — INTERMEDIATE ═════════════════════════════════
(40,5,'INTERMEDIATE',
 'What is hydration in server-side rendered frontend frameworks?',NULL,NULL,NULL,
 'Hydration attaches JavaScript event handlers to server-rendered HTML so the page becomes interactive.'),

(41,5,'INTERMEDIATE',
 'What is lazy loading in frontend development?',NULL,NULL,NULL,
 'Lazy loading defers loading resources until they are needed, reducing initial bundle size.'),

(42,5,'INTERMEDIATE',
 'What is the purpose of CSS-in-JS?',NULL,NULL,NULL,
 'CSS-in-JS allows writing component-scoped styles in JavaScript, enabling dynamic styling.'),

-- ═══ Category 5: frontend — ADVANCED ════════════════════════════════════
(43,5,'ADVANCED',
 'What is code splitting in web applications?',NULL,NULL,NULL,
 'Code splitting divides the JavaScript bundle into smaller chunks loaded on demand, improving Time to Interactive.'),

(44,5,'ADVANCED',
 'What is the purpose of a service worker?',NULL,NULL,NULL,
 'Service workers run in the background enabling offline support, caching strategies, and background sync.'),

(45,5,'ADVANCED',
 'What is tree shaking in JavaScript bundlers?',NULL,NULL,NULL,
 'Tree shaking removes dead (unused) code from the final bundle at build time, reducing its size.'),

-- ═══ Category 6: backendlogic — BEGINNER ═════════════════════════════════
(46,6,'BEGINNER',
 'What is the service layer in backend architecture?',NULL,NULL,NULL,
 'The service layer encapsulates business logic, separating it from controllers and data access.'),

(47,6,'BEGINNER',
 'What is dependency injection?',NULL,NULL,NULL,
 'Dependency injection provides a class''s dependencies from outside rather than letting it create them.'),

(48,6,'BEGINNER',
 'What is a DTO (Data Transfer Object)?',NULL,NULL,NULL,
 'A DTO is a simple object carrying data between layers or over the network, containing no business logic.'),

-- ═══ Category 6: backendlogic — INTERMEDIATE ═════════════════════════════
(49,6,'INTERMEDIATE',
 'What is the repository pattern?',NULL,NULL,NULL,
 'The repository pattern abstracts data persistence behind an interface, decoupling business logic from storage.'),

(50,6,'INTERMEDIATE',
 'What characterizes a pure function?',NULL,NULL,NULL,
 'A pure function always returns the same output for the same inputs and produces no side effects.'),

(51,6,'INTERMEDIATE',
 'What is the purpose of the Builder design pattern?',NULL,NULL,NULL,
 'Builder constructs complex objects step by step using a fluent API, separating construction from representation.'),

-- ═══ Category 6: backendlogic — ADVANCED ═════════════════════════════════
(52,6,'ADVANCED',
 'What is CQRS (Command Query Responsibility Segregation)?',NULL,NULL,NULL,
 'CQRS separates the read model (queries) from the write model (commands) for independent scaling and optimization.'),

(53,6,'ADVANCED',
 'What is Event Sourcing?',NULL,NULL,NULL,
 'Event Sourcing stores state as an immutable sequence of events; current state is derived by replaying events.'),

(54,6,'ADVANCED',
 'What is the Saga pattern in microservices?',NULL,NULL,NULL,
 'A Saga is a sequence of local transactions, each publishing events that trigger the next step, managing long-running processes.'),

-- ═══ Category 7: validation — BEGINNER ═══════════════════════════════════
(55,7,'BEGINNER',
 'What is input validation?',NULL,NULL,NULL,
 'Input validation verifies that user-supplied data meets expected format, type, and constraint requirements.'),

(56,7,'BEGINNER',
 'What does the @NotNull annotation do in Java Bean Validation?',NULL,NULL,NULL,
 '@NotNull ensures the annotated element value is not null; validation fails if null is provided.'),

(57,7,'BEGINNER',
 'What is client-side validation?',NULL,NULL,NULL,
 'Client-side validation checks input in the browser before submission, improving UX but not replacing server validation.'),

-- ═══ Category 7: validation — INTERMEDIATE ═══════════════════════════════
(58,7,'INTERMEDIATE',
 'What is the difference between whitelist and blacklist validation?',NULL,NULL,NULL,
 'Whitelist (allowlist) accepts only known-good values; blacklist (denylist) rejects known-bad values.'),

(59,7,'INTERMEDIATE',
 'What is cross-field validation?',NULL,NULL,NULL,
 'Cross-field validation checks relationships between multiple fields in the same object.'),

(60,7,'INTERMEDIATE',
 'What should always accompany client-side validation?',NULL,NULL,NULL,
 'Server-side validation must always be performed independently, as client-side can be bypassed.'),

-- ═══ Category 7: validation — ADVANCED ═══════════════════════════════════
(61,7,'ADVANCED',
 'What is the Java Bean Validation (JSR 380) specification?',NULL,NULL,NULL,
 'Bean Validation is a Java standard for declaring validation constraints on objects via annotations.'),

(62,7,'ADVANCED',
 'What is a custom constraint in Java Bean Validation?',NULL,NULL,NULL,
 'A custom constraint is a user-defined annotation paired with a ConstraintValidator implementation.'),

(63,7,'ADVANCED',
 'What is the purpose of validation groups in Bean Validation?',NULL,NULL,NULL,
 'Validation groups allow different subsets of constraints to be applied in different contexts.'),

-- ═══ Category 8: security — BEGINNER ═════════════════════════════════════
(64,8,'BEGINNER',
 'What is SQL Injection?',NULL,NULL,NULL,
 'SQL Injection inserts malicious SQL through input fields to manipulate or expose database data.'),

(65,8,'BEGINNER',
 'What is Cross-Site Scripting (XSS)?',NULL,NULL,NULL,
 'XSS injects malicious scripts into web pages that execute in other users'' browsers.'),

(66,8,'BEGINNER',
 'What does HTTPS provide over HTTP?',NULL,NULL,NULL,
 'HTTPS adds TLS/SSL encryption, ensuring data in transit is confidential and tamper-proof.'),

-- ═══ Category 8: security — INTERMEDIATE ═════════════════════════════════
(67,8,'INTERMEDIATE',
 'What is a CSRF attack?',NULL,NULL,NULL,
 'CSRF tricks a logged-in user''s browser into sending forged requests to a trusted site.'),

(68,8,'INTERMEDIATE',
 'What is the purpose of the Content-Security-Policy response header?',NULL,NULL,NULL,
 'CSP instructs the browser which content sources are trusted, preventing XSS and injection attacks.'),

(69,8,'INTERMEDIATE',
 'What is a parameterized query (prepared statement)?',NULL,NULL,NULL,
 'Parameterized queries separate SQL code from data, eliminating SQL injection by treating input as data only.'),

-- ═══ Category 8: security — ADVANCED ════════════════════════════════════
(70,8,'ADVANCED',
 'What is the OWASP Top 10?',NULL,NULL,NULL,
 'The OWASP Top 10 is a community-driven list of the ten most critical web application security risks.'),

(71,8,'ADVANCED',
 'What is penetration testing?',NULL,NULL,NULL,
 'Penetration testing is an authorized simulated attack on a system to identify exploitable security vulnerabilities.'),

(72,8,'ADVANCED',
 'What is a dependency vulnerability scan?',NULL,NULL,NULL,
 'It checks third-party libraries used by the application for publicly disclosed security vulnerabilities.'),

-- ═══ Category 9: testing — BEGINNER ══════════════════════════════════════
(73,9,'BEGINNER',
 'What is a unit test?',NULL,NULL,NULL,
 'A unit test verifies the behavior of a single isolated unit of code, such as a method or class.'),

(74,9,'BEGINNER',
 'What is a test mock?',NULL,NULL,NULL,
 'A mock is a simulated replacement for a real dependency that lets you isolate and verify interactions.'),

(75,9,'BEGINNER',
 'What is the difference between a stub and a mock?',NULL,NULL,NULL,
 'Stubs provide canned responses for indirect inputs; mocks also verify expected interactions were made.'),

-- ═══ Category 9: testing — INTERMEDIATE ══════════════════════════════════
(76,9,'INTERMEDIATE',
 'What is Test-Driven Development (TDD)?',NULL,NULL,NULL,
 'TDD writes a failing test first, then minimal code to pass it, then refactors while keeping tests green.'),

(77,9,'INTERMEDIATE',
 'What is test coverage?',NULL,NULL,NULL,
 'Test coverage measures the percentage of production code lines or branches executed during the test suite.'),

(78,9,'INTERMEDIATE',
 'What is an integration test?',NULL,NULL,NULL,
 'Integration tests verify multiple components or layers work correctly together, often with real infrastructure.'),

-- ═══ Category 9: testing — ADVANCED ══════════════════════════════════════
(79,9,'ADVANCED',
 'What is contract testing?',NULL,NULL,NULL,
 'Contract testing verifies that an API consumer and provider agree on the interface, detecting breaking changes.'),

(80,9,'ADVANCED',
 'What is mutation testing?',NULL,NULL,NULL,
 'Mutation testing introduces small code changes to verify the test suite detects and fails on them.'),

(81,9,'ADVANCED',
 'What is a test fixture?',NULL,NULL,NULL,
 'A test fixture is the fixed state of objects and data used as a known baseline for running tests.'),

-- ═══ Category 10: errorhandling — BEGINNER ════════════════════════════════
(82,10,'BEGINNER',
 'What is an exception in programming?',NULL,NULL,NULL,
 'An exception is an event that disrupts the normal execution flow of a program.'),

(83,10,'BEGINNER',
 'What is the purpose of a try-catch block?',NULL,NULL,NULL,
 'A try-catch block handles exceptions gracefully, preventing uncontrolled application crashes.'),

(84,10,'BEGINNER',
 'What is the difference between checked and unchecked exceptions in Java?',NULL,NULL,NULL,
 'Checked exceptions must be declared or handled; unchecked (runtime) exceptions do not require explicit handling.'),

-- ═══ Category 10: errorhandling — INTERMEDIATE ════════════════════════════
(85,10,'INTERMEDIATE',
 'Which HTTP status code range indicates server-side errors?',NULL,NULL,NULL,
 '5xx codes (e.g., 500 Internal Server Error) indicate the server failed to fulfil a valid request.'),

(86,10,'INTERMEDIATE',
 'What is a global exception handler in Spring Boot?',NULL,NULL,NULL,
 '@ControllerAdvice (with @ExceptionHandler methods) intercepts and handles exceptions across all controllers centrally.'),

(87,10,'INTERMEDIATE',
 'What is the purpose of returning a Problem Details response (RFC 7807)?',NULL,NULL,NULL,
 'Problem Details provides a standardized, machine-readable error format for HTTP API responses.'),

-- ═══ Category 10: errorhandling — ADVANCED ════════════════════════════════
(88,10,'ADVANCED',
 'What is the circuit breaker pattern?',NULL,NULL,NULL,
 'A circuit breaker stops calls to a failing service after a threshold, preventing cascading failures.'),

(89,10,'ADVANCED',
 'What is graceful degradation?',NULL,NULL,NULL,
 'Graceful degradation maintains partial functionality when some system components fail.'),

(90,10,'ADVANCED',
 'What is a dead letter queue (DLQ)?',NULL,NULL,NULL,
 'A DLQ holds messages that could not be processed so they can be analysed and reprocessed.'),

-- ═══ Category 11: performance — BEGINNER ═════════════════════════════════
(91,11,'BEGINNER',
 'What is caching?',NULL,NULL,NULL,
 'Caching stores frequently accessed data temporarily so future requests are served faster.'),

(92,11,'BEGINNER',
 'What does "response time" measure?',NULL,NULL,NULL,
 'Response time is the total duration from when a request is sent until the full response is received.'),

(93,11,'BEGINNER',
 'What is a performance bottleneck?',NULL,NULL,NULL,
 'A bottleneck is the component limiting overall system throughput.'),

-- ═══ Category 11: performance — INTERMEDIATE ═════════════════════════════
(94,11,'INTERMEDIATE',
 'What is a CDN (Content Delivery Network)?',NULL,NULL,NULL,
 'A CDN distributes content from edge servers geographically close to users, reducing latency.'),

(95,11,'INTERMEDIATE',
 'What is lazy loading in the context of database queries?',NULL,NULL,NULL,
 'Lazy loading fetches related entities only when first accessed, deferring unnecessary queries.'),

(96,11,'INTERMEDIATE',
 'What is horizontal scaling?',NULL,NULL,NULL,
 'Horizontal scaling adds more instances of a service to handle increased load.'),

-- ═══ Category 11: performance — ADVANCED ════════════════════════════════
(97,11,'ADVANCED',
 'What is distributed caching?',NULL,NULL,NULL,
 'Distributed caching (e.g., Redis) shares a cache across multiple service instances.'),

(98,11,'ADVANCED',
 'What is asynchronous processing?',NULL,NULL,NULL,
 'Asynchronous processing executes operations in the background without blocking the calling thread.'),

(99,11,'ADVANCED',
 'What does a profiler measure in application performance?',NULL,NULL,NULL,
 'A profiler identifies where an application spends CPU time and memory to guide optimisation.'),

-- ═══ Category 12: internationalization — BEGINNER ════════════════════════
(100,12,'BEGINNER',
 'What does i18n stand for?',NULL,NULL,NULL,
 'i18n stands for internationalization (18 letters between the first i and the last n).'),

(101,12,'BEGINNER',
 'What is localization (l10n)?',NULL,NULL,NULL,
 'Localization adapts internationalized software for a specific locale, culture, or language.'),

(102,12,'BEGINNER',
 'What is a locale?',NULL,NULL,NULL,
 'A locale is a combination of language and regional settings (e.g., fr-BE, en-US).'),

-- ═══ Category 12: internationalization — INTERMEDIATE ════════════════════
(103,12,'INTERMEDIATE',
 'What is RTL (Right-to-Left) language support?',NULL,NULL,NULL,
 'RTL support renders text and layout from right to left for languages like Arabic and Hebrew.'),

(104,12,'INTERMEDIATE',
 'What is a message key in i18n?',NULL,NULL,NULL,
 'A message key is a unique identifier mapped to locale-specific translated strings.'),

(105,12,'INTERMEDIATE',
 'What is pluralization in i18n?',NULL,NULL,NULL,
 'Pluralization uses different translation strings for singular, plural, and other grammatical forms.'),

-- ═══ Category 12: internationalization — ADVANCED ════════════════════════
(106,12,'ADVANCED',
 'What is the ICU message format?',NULL,NULL,NULL,
 'ICU provides a standard format for locale-sensitive messages including plural rules and variable interpolation.'),

(107,12,'ADVANCED',
 'What HTTP header does a client use to indicate its preferred language?',NULL,NULL,NULL,
 'The Accept-Language header communicates the client''s preferred languages for content negotiation.'),

(108,12,'ADVANCED',
 'What is a locale fallback strategy?',NULL,NULL,NULL,
 'Fallback serves a default locale''s translation when no translation exists for the requested locale.'),

-- ═══ Category 13: deployment — BEGINNER ═════════════════════════════════
(109,13,'BEGINNER',
 'What is Docker?',
 'ما هو Docker؟',
 'Wat is Docker?',
 'Qu''est-ce que Docker?',
 'Docker is a platform that packages applications and their dependencies into portable containers.'),

(110,13,'BEGINNER',
 'What does CI/CD stand for?',
 'ماذا تعني CI/CD اختصاراً؟',
 'Waar staat CI/CD voor?',
 'Que signifie CI/CD?',
 'CI/CD stands for Continuous Integration / Continuous Delivery (or Deployment).'),

(111,13,'BEGINNER',
 'What is a Dockerfile?',
 'ما هو Dockerfile؟',
 'Wat is een Dockerfile?',
 'Qu''est-ce qu''un Dockerfile?',
 'A Dockerfile is a script containing instructions to build a Docker image.'),

-- ═══ Category 13: deployment — INTERMEDIATE ═════════════════════════════
(112,13,'INTERMEDIATE',
 'What is the main difference between a container and a virtual machine?',
 'ما الفرق الرئيسي بين الحاوية والجهاز الافتراضي؟',
 'Wat is het grote verschil tussen een container en een virtuele machine?',
 'Quelle est la principale différence entre un conteneur et une machine virtuelle?',
 'Containers share the host OS kernel; VMs each include a full guest OS, making containers much lighter.'),

(113,13,'INTERMEDIATE',
 'What does Kubernetes provide?',
 'ماذا يوفر Kubernetes؟',
 'Wat biedt Kubernetes?',
 'Que fournit Kubernetes?',
 'Kubernetes automates container deployment, scaling, self-healing, and management across clusters.'),

(114,13,'INTERMEDIATE',
 'What is an application health check endpoint?',
 'ما هو نقطة نهاية فحص صحة التطبيق؟',
 'Wat is een health check eindpunt voor een applicatie?',
 'Qu''est-ce qu''un point de terminaison health check?',
 'A health check endpoint lets infrastructure verify that an application instance is running and ready.'),

-- ═══ Category 13: deployment — ADVANCED ═════════════════════════════════
(115,13,'ADVANCED',
 'What is blue-green deployment?',
 'ما هو نشر الأزرق-الأخضر (Blue-Green Deployment)؟',
 'Wat is blue-green deployment?',
 'Qu''est-ce que le déploiement blue-green?',
 'Blue-green keeps two identical environments; traffic is switched to the new (green) one after verification.'),

(116,13,'ADVANCED',
 'What is a canary release?',
 'ما هو إصدار الكناري (Canary Release)؟',
 'Wat is een canary release?',
 'Qu''est-ce qu''une release canary?',
 'A canary release routes a small percentage of traffic to the new version, allowing gradual validation.'),

(117,13,'ADVANCED',
 'What is Infrastructure as Code (IaC)?',
 'ما هي البنية التحتية كرمز (IaC)؟',
 'Wat is Infrastructure as Code (IaC)?',
 'Qu''est-ce que l''Infrastructure as Code (IaC)?',
 'IaC manages infrastructure through version-controlled, machine-readable definition files.'),

-- ═══ Category 14: loggingmonitoring — BEGINNER ═══════════════════════════
(118,14,'BEGINNER',
 'What is application logging?',NULL,NULL,NULL,
 'Logging records events, messages, and errors for diagnostics, auditing, and debugging.'),

(119,14,'BEGINNER',
 'What is a log level?',NULL,NULL,NULL,
 'A log level is a severity classification for messages: DEBUG, INFO, WARN, ERROR, FATAL.'),

(120,14,'BEGINNER',
 'What is monitoring in software systems?',NULL,NULL,NULL,
 'Monitoring continuously observes system health, performance metrics, and availability.'),

-- ═══ Category 14: loggingmonitoring — INTERMEDIATE ════════════════════════
(121,14,'INTERMEDIATE',
 'What is structured logging?',NULL,NULL,NULL,
 'Structured logging writes entries in a machine-parseable format (e.g., JSON) enabling automated analysis.'),

(122,14,'INTERMEDIATE',
 'What is APM (Application Performance Monitoring)?',NULL,NULL,NULL,
 'APM tracks response times, error rates, throughput, and resource usage of a live application.'),

(123,14,'INTERMEDIATE',
 'What is a metric in monitoring?',NULL,NULL,NULL,
 'A metric is a time-series quantitative measurement of system behaviour (e.g., requests per second).'),

-- ═══ Category 14: loggingmonitoring — ADVANCED ════════════════════════════
(124,14,'ADVANCED',
 'What is distributed tracing?',NULL,NULL,NULL,
 'Distributed tracing tracks a request''s complete journey across multiple services using a correlation ID.'),

(125,14,'ADVANCED',
 'What is a Service Level Agreement (SLA)?',NULL,NULL,NULL,
 'An SLA is a contractual commitment defining expected service performance and availability targets.'),

(126,14,'ADVANCED',
 'What is alerting in monitoring systems?',NULL,NULL,NULL,
 'Alerting automatically notifies engineers when metrics exceed defined thresholds.'),

-- ═══ Category 15: cicd — BEGINNER ════════════════════════════════════════
(127,15,'BEGINNER',
 'What is Continuous Integration (CI)?',NULL,NULL,NULL,
 'CI automatically builds and tests code on each commit, catching integration issues early.'),

(128,15,'BEGINNER',
 'What is a CI pipeline?',NULL,NULL,NULL,
 'A pipeline is an automated sequence of build, test, and deploy steps triggered by code changes.'),

(129,15,'BEGINNER',
 'What is the main benefit CI provides to a development team?',NULL,NULL,NULL,
 'CI enables early detection of integration bugs and regressions before they reach production.'),

-- ═══ Category 15: cicd — INTERMEDIATE ════════════════════════════════════
(130,15,'INTERMEDIATE',
 'What is a deployment artifact?',NULL,NULL,NULL,
 'A deployment artifact is a versioned, packaged build output (e.g., JAR, Docker image) ready to deploy.'),

(131,15,'INTERMEDIATE',
 'What is a rollback in a CI/CD workflow?',NULL,NULL,NULL,
 'A rollback reverts to a previous known-good version when a deployment fails.'),

(132,15,'INTERMEDIATE',
 'What is Continuous Deployment?',NULL,NULL,NULL,
 'Continuous Deployment automatically deploys every change that passes all pipeline tests to production.'),

-- ═══ Category 15: cicd — ADVANCED ════════════════════════════════════════
(133,15,'ADVANCED',
 'What is GitOps?',NULL,NULL,NULL,
 'GitOps uses Git repositories as the single source of truth for both application and infrastructure configuration.'),

(134,15,'ADVANCED',
 'What is a feature flag (feature toggle)?',NULL,NULL,NULL,
 'A feature flag enables or disables features at runtime via configuration, without redeployment.'),

(135,15,'ADVANCED',
 'What is a shift-left approach in CI/CD?',NULL,NULL,NULL,
 'Shift-left moves testing, security scanning, and quality checks earlier in the development process.'),

-- ═══ Category 16: filehandling — BEGINNER ════════════════════════════════
(136,16,'BEGINNER',
 'What is a multipart form data request?',NULL,NULL,NULL,
 'Multipart/form-data is the HTTP encoding used for uploading files alongside form fields.'),

(137,16,'BEGINNER',
 'What is a MIME type?',NULL,NULL,NULL,
 'A MIME type (e.g., image/png) identifies the format of content in an HTTP message.'),

(138,16,'BEGINNER',
 'Why should uploaded files be validated on the server?',NULL,NULL,NULL,
 'Server-side validation ensures files meet expected type and size constraints and prevents malicious uploads.'),

-- ═══ Category 16: filehandling — INTERMEDIATE ════════════════════════════
(139,16,'INTERMEDIATE',
 'What is streaming in file upload/download?',NULL,NULL,NULL,
 'Streaming processes data in chunks without loading the entire file into memory, enabling large file handling.'),

(140,16,'INTERMEDIATE',
 'What is a presigned URL for file upload?',NULL,NULL,NULL,
 'A presigned URL is a temporary URL with embedded credentials allowing direct upload to object storage.'),

(141,16,'INTERMEDIATE',
 'Why should servers generate unique filenames for uploads?',NULL,NULL,NULL,
 'Unique server-generated filenames prevent filename collisions and path traversal attacks.'),

-- ═══ Category 16: filehandling — ADVANCED ════════════════════════════════
(142,16,'ADVANCED',
 'What is resumable file upload?',NULL,NULL,NULL,
 'Resumable upload allows an interrupted upload to continue from its last saved position.'),

(143,16,'ADVANCED',
 'What is content-addressed storage?',NULL,NULL,NULL,
 'Content-addressed storage indexes files by the hash of their content, enabling deduplication.'),

(144,16,'ADVANCED',
 'What security risk must be prevented when allowing file uploads?',NULL,NULL,NULL,
 'Path traversal attacks use crafted filenames to gain access to directories outside the intended upload path.'),

-- ═══ Category 17: reporting — BEGINNER ════════════════════════════════════
(145,17,'BEGINNER',
 'What is data export?',NULL,NULL,NULL,
 'Data export generates a downloadable file (CSV, Excel, PDF) containing application data.'),

(146,17,'BEGINNER',
 'What is a CSV file?',NULL,NULL,NULL,
 'A CSV (Comma-Separated Values) file stores tabular data as plain text with values separated by commas.'),

(147,17,'BEGINNER',
 'What is pagination in data reporting?',NULL,NULL,NULL,
 'Pagination splits large result sets into smaller pages to improve performance and usability.'),

-- ═══ Category 17: reporting — INTERMEDIATE ════════════════════════════════
(148,17,'INTERMEDIATE',
 'What is a report template?',NULL,NULL,NULL,
 'A report template is a predefined layout used to generate consistently formatted reports.'),

(149,17,'INTERMEDIATE',
 'What is data aggregation in reporting?',NULL,NULL,NULL,
 'Data aggregation computes summary statistics (count, sum, average) over a dataset.'),

(150,17,'INTERMEDIATE',
 'What is a scheduled report?',NULL,NULL,NULL,
 'A scheduled report is automatically generated and delivered at configured time intervals.'),

-- ═══ Category 17: reporting — ADVANCED ════════════════════════════════════
(151,17,'ADVANCED',
 'What is an ETL process?',NULL,NULL,NULL,
 'ETL (Extract, Transform, Load) extracts data from a source, transforms it, and loads it into a target system.'),

(152,17,'ADVANCED',
 'What is a data warehouse?',NULL,NULL,NULL,
 'A data warehouse is a centralized repository optimised for analytical queries and historical reporting.'),

(153,17,'ADVANCED',
 'What is report caching?',NULL,NULL,NULL,
 'Report caching stores generated report output so repeat requests are served without regeneration.'),

-- ═══ Category 18: searchfiltering — BEGINNER ════════════════════════════
(154,18,'BEGINNER',
 'What is a search query?',NULL,NULL,NULL,
 'A search query is a request to find records matching specified criteria.'),

(155,18,'BEGINNER',
 'What is a filter in data retrieval?',NULL,NULL,NULL,
 'A filter is a condition that narrows down a result set to only matching records.'),

(156,18,'BEGINNER',
 'What is sorting in data retrieval?',NULL,NULL,NULL,
 'Sorting orders result records by one or more fields in ascending or descending order.'),

-- ═══ Category 18: searchfiltering — INTERMEDIATE ════════════════════════
(157,18,'INTERMEDIATE',
 'What is full-text search?',NULL,NULL,NULL,
 'Full-text search queries the content of text fields rather than matching exact column values.'),

(158,18,'INTERMEDIATE',
 'What is faceted search?',NULL,NULL,NULL,
 'Faceted search lets users filter results by multiple attribute categories simultaneously.'),

(159,18,'INTERMEDIATE',
 'What is offset-based pagination?',NULL,NULL,NULL,
 'Offset-based pagination skips a fixed number of records to retrieve a specific page of results.'),

-- ═══ Category 18: searchfiltering — ADVANCED ════════════════════════════
(160,18,'ADVANCED',
 'What is an Elasticsearch index?',NULL,NULL,NULL,
 'An Elasticsearch index is a collection of documents optimised for full-text search and analytics.'),

(161,18,'ADVANCED',
 'What is cursor-based pagination?',NULL,NULL,NULL,
 'Cursor-based pagination uses a stable pointer to track position, avoiding the shifting problem of offset pagination.'),

(162,18,'ADVANCED',
 'What is relevance scoring in search engines?',NULL,NULL,NULL,
 'Relevance scoring ranks search results by how closely they match the query, using algorithms like TF-IDF.'),

-- ═══ Category 19: configuration — BEGINNER ════════════════════════════════
(163,19,'BEGINNER',
 'What is an environment variable?',NULL,NULL,NULL,
 'An environment variable is a named value set in the OS environment and read by the application at runtime.'),

(164,19,'BEGINNER',
 'What is the purpose of application.yml in Spring Boot?',NULL,NULL,NULL,
 'application.yml is the externalized configuration file for a Spring Boot application.'),

(165,19,'BEGINNER',
 'What is a configuration profile?',NULL,NULL,NULL,
 'A profile is a named set of configuration properties activated for a specific environment (dev, prod).'),

-- ═══ Category 19: configuration — INTERMEDIATE ════════════════════════════
(166,19,'INTERMEDIATE',
 'What is configuration externalization?',NULL,NULL,NULL,
 'Externalization keeps configuration values outside the deployable artifact so they can change without rebuild.'),

(167,19,'INTERMEDIATE',
 'What are Spring Profiles used for?',NULL,NULL,NULL,
 'Spring Profiles activate different beans and properties per environment, enabling environment-specific config.'),

(168,19,'INTERMEDIATE',
 'What is a secret in application configuration?',NULL,NULL,NULL,
 'A secret is a sensitive value (password, API key) that must not be stored in plain text or version control.'),

-- ═══ Category 19: configuration — ADVANCED ════════════════════════════════
(169,19,'ADVANCED',
 'What is a config server in microservices?',NULL,NULL,NULL,
 'A config server provides centralised, dynamic configuration to all services in a microservices architecture.'),

(170,19,'ADVANCED',
 'What does the 12-Factor App principle say about configuration?',NULL,NULL,NULL,
 'Factor III: store config in the environment, not in the codebase, so it can vary between deployments.'),

(171,19,'ADVANCED',
 'What is a feature flag in configuration?',NULL,NULL,NULL,
 'A feature flag is a configuration toggle that enables or disables features without redeployment.');

-- ──────────────────────────────────────────────────────────────────────────
-- CHOICES INSERT
-- ──────────────────────────────────────────────────────────────────────────

-- cat 1 restapi (q 1-9)  — full 4-language choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en,text_ar,text_nl,text_fr) VALUES
(1,1,TRUE, 'Representational State Transfer','نقل الحالة التمثيلية','Representational State Transfer','Representational State Transfer'),
(1,2,FALSE,'Remote Service Technology','تقنية الخدمة البعيدة','Remote Service Technology','Remote Service Technology'),
(1,3,FALSE,'Request-Response Entity','كيان الطلب والاستجابة','Request-Response Entity','Entité Requête-Réponse'),
(1,4,FALSE,'Real-Time Exchange Standard','معيار التبادل الفوري','Real-Time Exchange Standard','Standard d''échange temps réel'),

(2,1,TRUE, 'GET','GET','GET','GET'),
(2,2,FALSE,'POST','POST','POST','POST'),
(2,3,FALSE,'PUT','PUT','PUT','PUT'),
(2,4,FALSE,'DELETE','DELETE','DELETE','DELETE'),

(3,1,TRUE, '200','200','200','200'),
(3,2,FALSE,'201','201','201','201'),
(3,3,FALSE,'404','404','404','404'),
(3,4,FALSE,'500','500','500','500'),

(4,1,TRUE, 'Calling it multiple times produces the same result as one call','استدعاؤه عدة مرات يعطي نفس نتيجة استدعائه مرة واحدة','Meerdere aanroepen geven hetzelfde resultaat als één aanroep','L''appeler plusieurs fois produit le même résultat qu''une seule fois'),
(4,2,FALSE,'It does not require authentication','لا يتطلب مصادقة','Het vereist geen authenticatie','Il ne nécessite pas d''authentification'),
(4,3,FALSE,'It has no request body','ليس له جسم طلب','Het heeft geen aanvraagbody','Il n''a pas de corps de requête'),
(4,4,FALSE,'It uses HTTP caching automatically','يستخدم التخزين المؤقت لـHTTP تلقائياً','Het gebruikt HTTP-caching automatisch','Il utilise la mise en cache HTTP automatiquement'),

(5,1,TRUE, 'POST','POST','POST','POST'),
(5,2,FALSE,'GET','GET','GET','GET'),
(5,3,FALSE,'PUT','PUT','PUT','PUT'),
(5,4,FALSE,'DELETE','DELETE','DELETE','DELETE'),

(6,1,TRUE, 'Specifies the media type of the request or response body','يحدد نوع الوسائط لجسم الطلب أو الاستجابة','Specificeert het mediatype van de aanvraag- of antwoordbody','Spécifie le type de média du corps de la requête ou réponse'),
(6,2,FALSE,'Sets the character encoding of the URL','يضبط ترميز الأحرف للعنوان','Stelt de tekencodering van de URL in','Définit l''encodage des caractères de l''URL'),
(6,3,FALSE,'Identifies the client making the request','يحدد هوية العميل الذي يقوم بالطلب','Identificeert de client die de aanvraag stuurt','Identifie le client faisant la requête'),
(6,4,FALSE,'Controls browser caching behaviour','يتحكم في سلوك التخزين المؤقت بالمتصفح','Beheert het cachinggedrag van de browser','Contrôle le comportement de mise en cache du navigateur'),

(7,1,TRUE, 'Hypermedia links in responses guide client navigation','روابط hypermedia في الاستجابات توجه تنقل العميل','Hypermedialinks in responses sturen clientnavigatie','Les liens hypermedia dans les réponses guident la navigation client'),
(7,2,FALSE,'A REST authentication standard','معيار مصادقة REST','Een REST-authenticatiestandaard','Un standard d''authentification REST'),
(7,3,FALSE,'An HTTP caching mechanism','آلية تخزين مؤقت HTTP','Een HTTP-cachemechanisme','Un mécanisme de mise en cache HTTP'),
(7,4,FALSE,'A REST API versioning strategy','استراتيجية إصدار REST API','Een REST API-versiestrategie','Une stratégie de versionnage d''API REST'),

(8,1,TRUE, 'Too Many Requests – client exceeded the rate limit','طلبات كثيرة جداً — تجاوز العميل حد المعدل','Te Veel Verzoeken – client overschreed de snelheidslimiet','Trop de requêtes – le client a dépassé la limite de débit'),
(8,2,FALSE,'Unauthorized – credentials are missing or invalid','غير مصرح — بيانات الاعتماد مفقودة أو غير صحيحة','Ongeautoriseerd – inloggegevens ontbreken of zijn ongeldig','Non autorisé – identifiants manquants ou invalides'),
(8,3,FALSE,'Gateway Timeout – upstream server did not respond','انتهاء مهلة البوابة — الخادم الوسيط لم يستجب','Gateway Time-out – upstream-server reageerde niet','Délai de passerelle – le serveur en amont n''a pas répondu'),
(8,4,FALSE,'Conflict – the request conflicts with current state','تعارض — يتعارض الطلب مع الحالة الحالية','Conflict – aanvraag conflicteert met huidige toestand','Conflit – la requête est en conflit avec l''état actuel'),

(9,1,TRUE, 'PATCH','PATCH','PATCH','PATCH'),
(9,2,FALSE,'PUT','PUT','PUT','PUT'),
(9,3,FALSE,'POST','POST','POST','POST'),
(9,4,FALSE,'UPDATE','UPDATE','UPDATE','UPDATE');

-- cat 2 databaseintegration (q 10-18) — full 4-language choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en,text_ar,text_nl,text_fr) VALUES
(10,1,TRUE, 'Structured Query Language','لغة الاستعلام الهيكلية','Structured Query Language','Structured Query Language'),
(10,2,FALSE,'Sequential Query Logic','منطق الاستعلام التسلسلي','Sequential Query Logic','Sequential Query Logic'),
(10,3,FALSE,'Standard Query Library','مكتبة الاستعلام القياسية','Standard Query Library','Bibliothèque de requêtes standard'),
(10,4,FALSE,'Simple Query Layer','طبقة الاستعلام البسيطة','Simple Query Layer','Couche de requête simple'),

(11,1,TRUE, 'SELECT','SELECT','SELECT','SELECT'),
(11,2,FALSE,'GET','GET','GET','GET'),
(11,3,FALSE,'FETCH','FETCH','FETCH','FETCH'),
(11,4,FALSE,'READ','READ','READ','READ'),

(12,1,TRUE, 'A column or combination uniquely identifying each row','عمود أو مجموعة أعمدة تُعرّف كل صف بشكل فريد','Een kolom die elke rij uniek identificeert','Une colonne identifiant de manière unique chaque ligne'),
(12,2,FALSE,'The first indexed column in a table','أول عمود مفهرس في الجدول','De eerste geïndexeerde kolom in een tabel','La première colonne indexée d''une table'),
(12,3,FALSE,'A foreign key that references another table','مفتاح خارجي يشير إلى جدول آخر','Een vreemde sleutel die naar een andere tabel verwijst','Une clé étrangère référençant une autre table'),
(12,4,FALSE,'An automatic unique index created by the database','فهرس فريد تلقائي تنشئه قاعدة البيانات','Een automatische unieke index die door de database wordt aangemaakt','Un index unique automatique créé par la base de données'),

(13,1,TRUE, 'One query fetches parents, then one more query fires per child entity','استعلام واحد يجلب الآباء ثم استعلام إضافي لكل كيان ابن','Eén query haalt ouders op, daarna one extra query per kind-entiteit','Une requête charge les parents, puis une requête supplémentaire par entité enfant'),
(13,2,FALSE,'Executing N queries inside a single transaction','تنفيذ N استعلام داخل معاملة واحدة','N queries uitvoeren binnen een enkele transactie','Exécuter N requêtes dans une seule transaction'),
(13,3,FALSE,'An index fragmentation issue','مشكلة تجزؤ الفهرس','Een index-fragmentatieprobleem','Un problème de fragmentation d''index'),
(13,4,FALSE,'A schema version conflict in migrations','تعارض في إصدار المخطط في الترحيلات','Een schemaversieconflict bij migraties','Un conflit de version de schéma dans les migrations'),

(14,1,TRUE, 'Only rows with matching values in both joined tables','فقط الصفوف ذات القيم المتطابقة في كلا الجدولين','Alleen rijen met overeenkomende waarden in beide tabellen','Uniquement les lignes avec des valeurs correspondantes dans les deux tables'),
(14,2,FALSE,'All rows from both tables regardless of match','كل الصفوف من كلا الجدولين بغض النظر عن التطابق','Alle rijen uit beide tabellen ongeacht overeenkomst','Toutes les lignes des deux tables quelle que soit la correspondance'),
(14,3,FALSE,'All rows from the left table and matched from right','كل صفوف الجدول الأيسر والمطابقة من الأيمن','Alle rijen uit de linker tabel en overeenkomende uit de rechter','Toutes les lignes de la table gauche et les correspondances à droite'),
(14,4,FALSE,'Only rows with no match in either table','فقط الصفوف التي لا تطابق في أي جدول','Alleen rijen zonder overeenkomst in beide tabellen','Uniquement les lignes sans correspondance dans les deux tables'),

(15,1,TRUE, 'Speed up data retrieval operations','تسريع عمليات استرداد البيانات','Gegevensopvraging versnellen','Accélérer les opérations de récupération de données'),
(15,2,FALSE,'Enforce unique constraints on columns','فرض قيود التفرد على الأعمدة','Unieke beperkingen op kolommen afdwingen','Appliquer des contraintes d''unicité sur les colonnes'),
(15,3,FALSE,'Define foreign key relationships','تحديد علاقات المفتاح الخارجي','Relaties met vreemde sleutels definiëren','Définir les relations de clé étrangère'),
(15,4,FALSE,'Manage transactions automatically','إدارة المعاملات تلقائياً','Transacties automatisch beheren','Gérer les transactions automatiquement'),

(16,1,TRUE, 'Maintaining a pool of reusable connections to reduce overhead','الاحتفاظ بمجموعة من الاتصالات القابلة لإعادة الاستخدام','Een pool van herbruikbare verbindingen onderhouden om overhead te verminderen','Maintenir un pool de connexions réutilisables pour réduire la surcharge'),
(16,2,FALSE,'Encrypting all database connections','تشفير كل اتصالات قاعدة البيانات','Alle databaseverbindingen versleutelen','Chiffrer toutes les connexions à la base de données'),
(16,3,FALSE,'Distributing data across multiple databases','توزيع البيانات عبر قواعد بيانات متعددة','Gegevens verdelen over meerdere databases','Distribuer les données sur plusieurs bases de données'),
(16,4,FALSE,'Caching frequently accessed query results','تخزين نتائج الاستعلام الأكثر وصولاً','Frequent geraadpleegde queryresultaten in de cache opslaan','Mettre en cache les résultats des requêtes fréquentes'),

(17,1,TRUE, 'Assuming no conflict and checking only at commit time','افتراض غياب التعارض والتحقق فقط عند الإيداع','Geen conflict aannemen en pas bij commit controleren','Supposer qu''il n''y a pas de conflit et vérifier seulement au commit'),
(17,2,FALSE,'Locking all rows at the start of every transaction','قفل كل الصفوف في بداية كل معاملة','Alle rijen vergrendelen aan het begin van elke transactie','Verrouiller toutes les lignes au début de chaque transaction'),
(17,3,FALSE,'Preventing concurrent read operations','منع عمليات القراءة المتزامنة','Gelijktijdige leesbewerkingen voorkomen','Empêcher les opérations de lecture simultanées'),
(17,4,FALSE,'Automatically rolling back failed transactions','التراجع التلقائي عن المعاملات الفاشلة','Mislukte transacties automatisch terugdraaien','Annuler automatiquement les transactions échouées'),

(18,1,TRUE, 'A distributed system cannot simultaneously guarantee Consistency, Availability, and Partition tolerance','نظام موزع لا يمكنه ضمان الاتساق والتوافر وتسامح الانقسام في آنٍ واحد','Een gedistribueerd systeem kan niet tegelijkertijd Consistentie, Beschikbaarheid en Partitietolerantie garanderen','Un système distribué ne peut pas garantir simultanément Cohérence, Disponibilité et Tolérance aux partitions'),
(18,2,FALSE,'A database can achieve Consistency, Availability, and Performance simultaneously','يمكن لقاعدة البيانات تحقيق الاتساق والتوافر والأداء في آنٍ واحد','Een database kan Consistentie, Beschikbaarheid en Prestaties tegelijkertijd bereiken','Une base de données peut atteindre Cohérence, Disponibilité et Performance simultanément'),
(18,3,FALSE,'Caching, Availability, and Partitioning always coexist','التخزين المؤقت والتوافر والتقسيم يمكن دائماً التعايش معاً','Caching, Beschikbaarheid en Partitionering kunnen altijd samen bestaan','La mise en cache, la disponibilité et la partition coexistent toujours'),
(18,4,FALSE,'Any distributed system must sacrifice consistency for availability','يجب على أي نظام موزع التضحية بالاتساق لصالح التوافر','Elk gedistribueerd systeem moet consistentie opofferen voor beschikbaarheid','Tout système distribué doit sacrifier la cohérence pour la disponibilité');

-- cat 3 authentication (q 19-27) — full 4-language choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en,text_ar,text_nl,text_fr) VALUES
(19,1,TRUE, 'JSON Web Token','رمز الويب JSON','JSON Web Token','JSON Web Token'),
(19,2,FALSE,'JavaScript Widget Transfer','نقل عنصر JavaScript','JavaScript Widget Transfer','JavaScript Widget Transfer'),
(19,3,FALSE,'Java Web Transaction','معاملة ويب Java','Java Web Transaction','Java Web Transaction'),
(19,4,FALSE,'JSON Workflow Type','نوع سير عمل JSON','JSON Workflow Type','Type de flux de travail JSON'),

(20,1,TRUE, 'Header, Payload, Signature','الرأس، الحمولة، التوقيع','Header, Payload, Handtekening','En-tête, Charge utile, Signature'),
(20,2,FALSE,'Key, Value, Checksum','المفتاح، القيمة، مجموع التحقق','Sleutel, Waarde, Checksum','Clé, Valeur, Somme de contrôle'),
(20,3,FALSE,'Request, Response, Status','الطلب، الاستجابة، الحالة','Verzoek, Antwoord, Status','Requête, Réponse, Statut'),
(20,4,FALSE,'Algorithm, Data, Digest','الخوارزمية، البيانات، الملخص','Algoritme, Gegevens, Samenvatting','Algorithme, Données, Condensé'),

(21,1,TRUE, 'To prevent passwords being recovered if the database is compromised','لمنع استرداد كلمات المرور في حالة اختراق قاعدة البيانات','Om te voorkomen dat wachtwoorden worden achterhaald als de database is gehackt','Pour empêcher la récupération des mots de passe si la base de données est compromise'),
(21,2,FALSE,'To compress password storage space','لضغط مساحة تخزين كلمات المرور','Om de opslagruimte van wachtwoorden te comprimeren','Pour compresser l''espace de stockage des mots de passe'),
(21,3,FALSE,'To encrypt passwords during network transit','لتشفير كلمات المرور أثناء النقل عبر الشبكة','Om wachtwoorden te versleutelen tijdens netwerkoverdracht','Pour chiffrer les mots de passe pendant le transit réseau'),
(21,4,FALSE,'To verify email addresses automatically','للتحقق من عناوين البريد الإلكتروني تلقائياً','Om e-mailadressen automatisch te verifiëren','Pour vérifier automatiquement les adresses e-mail'),

(22,1,TRUE, 'Authentication verifies who you are; Authorization determines what you can do','المصادقة تتحقق من هويتك؛ التفويض يحدد ما يمكنك فعله','Authenticatie verifieert wie u bent; Autorisatie bepaalt wat u mag doen','L''authentification vérifie qui vous êtes ; l''autorisation détermine ce que vous pouvez faire'),
(22,2,FALSE,'Authentication grants permissions; Authorization verifies identity','المصادقة تمنح الصلاحيات؛ التفويض يتحقق من الهوية','Authenticatie verleent rechten; Autorisatie verifieert identiteit','L''authentification accorde des droits ; l''autorisation vérifie l''identité'),
(22,3,FALSE,'They are two terms for the same process','هما مصطلحان لنفس العملية','Ze zijn twee termen voor hetzelfde proces','Ce sont deux termes pour le même processus'),
(22,4,FALSE,'Authentication is server-side only; Authorization is client-side only','المصادقة من جانب الخادم فقط؛ التفويض من جانب العميل فقط','Authenticatie is alleen server-side; Autorisatie is alleen client-side','L''authentification est côté serveur seulement ; l''autorisation est côté client seulement'),

(23,1,TRUE, 'Delegated access authorization without sharing credentials','تفويض الوصول المفوّض دون مشاركة بيانات الاعتماد','Gedelegeerde toegangsmachtiging zonder inloggegevens te delen','Autorisation d''accès délégué sans partager les identifiants'),
(23,2,FALSE,'Encrypting user passwords during transmission','تشفير كلمات مرور المستخدمين أثناء الإرسال','Gebruikerswachtwoorden versleutelen tijdens verzending','Chiffrer les mots de passe des utilisateurs lors de la transmission'),
(23,3,FALSE,'Securing database access permissions','تأمين أذونات الوصول إلى قاعدة البيانات','Databasetoegangsmachtigingen beveiligen','Sécuriser les autorisations d''accès à la base de données'),
(23,4,FALSE,'Managing user sessions with cookies','إدارة جلسات المستخدمين باستخدام الكوكيز','Gebruikerssessies beheren met cookies','Gérer les sessions utilisateur avec des cookies'),

(24,1,TRUE, 'A long-lived credential used to obtain new access tokens','بيانات اعتماد طويلة الأمد تُستخدم للحصول على رموز وصول جديدة','Een langlevende credential om nieuwe toegangstokens te verkrijgen','Un justificatif de longue durée pour obtenir de nouveaux jetons d''accès'),
(24,2,FALSE,'A short-lived session identifier','معرّف جلسة قصير الأمد','Een kortlevende sessie-identifier','Un identifiant de session de courte durée'),
(24,3,FALSE,'A one-time verification code sent by email','رمز تحقق لمرة واحدة يُرسل عبر البريد الإلكتروني','Een eenmalige verificatiecode die per e-mail wordt verzonden','Un code de vérification à usage unique envoyé par e-mail'),
(24,4,FALSE,'A secondary password for admin accounts','كلمة مرور ثانوية لحسابات المسؤولين','Een secundair wachtwoord voor beheerdersaccounts','Un mot de passe secondaire pour les comptes administrateurs'),

(25,1,TRUE, 'Protection against authorization code interception attacks','الحماية من هجمات اعتراض رمز التفويض','Bescherming tegen het onderscheppen van autorisatiecodes','Protection contre les attaques d''interception du code d''autorisation'),
(25,2,FALSE,'A public-key certificate exchange mechanism','آلية تبادل شهادات المفتاح العام','Een uitwisselingsmechanisme voor publieke-sleutelcertificaten','Un mécanisme d''échange de certificats de clé publique'),
(25,3,FALSE,'A password-based key derivation function','دالة اشتقاق المفاتيح المستندة إلى كلمة المرور','Een wachtwoordgebaseerde sleutelafleiddingsfunctie','Une fonction de dérivation de clé basée sur un mot de passe'),
(25,4,FALSE,'Encrypted refresh token storage','تخزين رموز التحديث المشفرة','Opslag van versleutelde vernieuwingstokens','Stockage de jetons de renouvellement chiffrés'),

(26,1,TRUE, 'Prevent replay attacks by binding the token to a specific request','منع هجمات إعادة التشغيل بربط الرمز بطلب محدد','Replay-aanvallen voorkomen door het token aan een specifiek verzoek te koppelen','Prévenir les attaques par relecture en liant le jeton à une requête spécifique'),
(26,2,FALSE,'Generate unique session identifiers','توليد معرّفات جلسة فريدة','Unieke sessie-identifiers genereren','Générer des identifiants de session uniques'),
(26,3,FALSE,'Encrypt the ID token payload','تشفير حمولة رمز الهوية','De payload van het ID-token versleutelen','Chiffrer la charge utile du jeton d''identité'),
(26,4,FALSE,'Store user profile claims','تخزين مطالبات ملف تعريف المستخدم','Gebruikersprfielclaims opslaan','Stocker les claims du profil utilisateur'),

(27,1,TRUE, 'Requires two or more independent verification factors from different categories','يتطلب عاملَي تحقق مستقلّين أو أكثر من فئات مختلفة','Vereist twee of meer onafhankelijke verificatiefactoren uit verschillende categorieën','Nécessite deux facteurs de vérification indépendants ou plus de catégories différentes'),
(27,2,FALSE,'Requires users to change their password multiple times','يتطلب من المستخدمين تغيير كلمات المرور عدة مرات','Vereist dat gebruikers hun wachtwoord meerdere keren wijzigen','Exige que les utilisateurs changent leur mot de passe plusieurs fois'),
(27,3,FALSE,'Uses multiple devices simultaneously','يستخدم أجهزة متعددة في آنٍ واحد','Gebruikt meerdere apparaten tegelijkertijd','Utilise plusieurs appareils simultanément'),
(27,4,FALSE,'Encrypts tokens using multiple algorithms','يشفّر الرموز باستخدام خوارزميات متعددة','Tokens versleutelen met meerdere algoritmen','Chiffre les jetons avec plusieurs algorithmes');

-- cats 4-12 (q 28-108) — English-only choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en) VALUES
(28,1,TRUE, 'Assigning permissions to users based on their roles'),
(28,2,FALSE,'Restricting access by username patterns'),
(28,3,FALSE,'Applying global access rules to all users'),
(28,4,FALSE,'Time-based access restrictions'),
(29,1,TRUE, 'Access Control List'),
(29,2,FALSE,'Application Config Layer'),
(29,3,FALSE,'Authenticated Client Login'),
(29,4,FALSE,'Automatic Content Loader'),
(30,1,TRUE, 'Defines what actions a subject can perform on a resource'),
(30,2,FALSE,'Identifies the user''s username'),
(30,3,FALSE,'Stores the user''s session token'),
(30,4,FALSE,'Records the user''s last login time'),
(31,1,TRUE, 'Grant subjects only the minimum permissions needed for their task'),
(31,2,FALSE,'Give all administrators unrestricted access'),
(31,3,FALSE,'Open all endpoints by default and restrict individually'),
(31,4,FALSE,'Deny all access initially and never grant permissions'),
(32,1,TRUE, 'Access control decisions based on user, resource, and environmental attributes'),
(32,2,FALSE,'Access restricted to users with a specific attribute tag'),
(32,3,FALSE,'Auto-provisioned credentials based on department attributes'),
(32,4,FALSE,'Application-based compartmentalization'),
(33,1,TRUE, 'A rule combining attributes to determine whether access is granted'),
(33,2,FALSE,'A user''s security clearance level'),
(33,3,FALSE,'A password strength requirement'),
(33,4,FALSE,'A network firewall rule'),
(34,1,TRUE, 'Using named claim values in a security token to make authorization decisions'),
(34,2,FALSE,'Validating only HTTP headers for authorization'),
(34,3,FALSE,'Custom middleware that bypasses standard auth'),
(34,4,FALSE,'Policy-free authorization using roles only'),
(35,1,TRUE, 'The component evaluating access control policies and granting or denying access'),
(35,2,FALSE,'A password decryption provider'),
(35,3,FALSE,'An application deployment parameter'),
(35,4,FALSE,'A database port configuration'),
(36,1,TRUE, 'Allowing a user to temporarily grant their permissions to another entity'),
(36,2,FALSE,'Permanently assigning permissions across all roles'),
(36,3,FALSE,'Blocking permission changes at runtime'),
(36,4,FALSE,'Copying permissions from one system to another'),
(37,1,TRUE, 'An in-memory representation of the real DOM used for efficient updates'),
(37,2,FALSE,'A browser-native API for the DOM'),
(37,3,FALSE,'A CSS preprocessor'),
(37,4,FALSE,'A JavaScript state management library'),
(38,1,TRUE, 'Building UI from independent, reusable components'),
(38,2,FALSE,'A server-rendered page approach'),
(38,3,FALSE,'A CSS framework methodology'),
(38,4,FALSE,'A build tool configuration pattern'),
(39,1,TRUE, 'A web app loading one HTML page and dynamically updating content'),
(39,2,FALSE,'A website with only one page of content'),
(39,3,FALSE,'An application running in a single browser tab'),
(39,4,FALSE,'A mobile-optimised web application'),
(40,1,TRUE, 'Attaching JavaScript event handlers to server-rendered HTML on the client'),
(40,2,FALSE,'Fetching data from remote APIs after page load'),
(40,3,FALSE,'Updating the DOM with new data'),
(40,4,FALSE,'Caching component state in the browser'),
(41,1,TRUE, 'Deferring loading resources until they are actually needed'),
(41,2,FALSE,'Preloading all application assets at startup'),
(41,3,FALSE,'Caching all static files persistently'),
(41,4,FALSE,'Minifying JavaScript at build time'),
(42,1,TRUE, 'Writing component-scoped styles in JavaScript files'),
(42,2,FALSE,'Converting CSS to JavaScript at runtime'),
(42,3,FALSE,'Server-side CSS generation'),
(42,4,FALSE,'Inline style overriding'),
(43,1,TRUE, 'Dividing the JavaScript bundle into smaller chunks loaded on demand'),
(43,2,FALSE,'Separating HTML, CSS, and JavaScript into different files'),
(43,3,FALSE,'Minifying source code at build time'),
(43,4,FALSE,'Splitting API calls into parallel requests'),
(44,1,TRUE, 'Runs in the background enabling offline support, caching, and push notifications'),
(44,2,FALSE,'Manages server-side session configuration'),
(44,3,FALSE,'Handles authentication tokens'),
(44,4,FALSE,'Provides direct database access from the browser'),
(45,1,TRUE, 'Removing unused code from the final bundle at build time'),
(45,2,FALSE,'Organising component dependencies in a tree structure'),
(45,3,FALSE,'Optimising DOM traversal operations'),
(45,4,FALSE,'Caching component trees in memory'),
(46,1,TRUE, 'Layer encapsulating business logic, separated from controllers and data access'),
(46,2,FALSE,'The network communication layer'),
(46,3,FALSE,'The data persistence layer'),
(46,4,FALSE,'The presentation layer'),
(47,1,TRUE, 'Providing a class''s dependencies from outside rather than creating them internally'),
(47,2,FALSE,'Injecting SQL queries into the database'),
(47,3,FALSE,'Pre-loading all classes at application start'),
(47,4,FALSE,'Modifying bytecode at runtime'),
(48,1,TRUE, 'An object carrying data between layers or services with no business logic'),
(48,2,FALSE,'A database table mapping object'),
(48,3,FALSE,'A configuration property holder'),
(48,4,FALSE,'A security token carrier'),
(49,1,TRUE, 'An abstraction layer between business logic and data persistence'),
(49,2,FALSE,'A versioned code storage strategy'),
(49,3,FALSE,'A publish-subscribe message pattern'),
(49,4,FALSE,'A data validation strategy'),
(50,1,TRUE, 'Always returns the same output for the same inputs and has no side effects'),
(50,2,FALSE,'A function without any parameters'),
(50,3,FALSE,'A function that modifies global state'),
(50,4,FALSE,'A function that always returns null'),
(51,1,TRUE, 'Constructing complex objects step-by-step with a fluent API'),
(51,2,FALSE,'Building database schemas programmatically'),
(51,3,FALSE,'Generating API documentation automatically'),
(51,4,FALSE,'Loading configuration from files'),
(52,1,TRUE, 'Separating read operations from write operations using different models'),
(52,2,FALSE,'A concurrency model for parallel processing'),
(52,3,FALSE,'A data serialisation format'),
(52,4,FALSE,'An API communication protocol'),
(53,1,TRUE, 'Storing state as an immutable sequence of events; state is derived by replaying them'),
(53,2,FALSE,'Subscribing to DOM events in the backend'),
(53,3,FALSE,'Logging all service errors to an event bus'),
(53,4,FALSE,'Publishing domain changes to a message queue'),
(54,1,TRUE, 'A sequence of local transactions coordinated to maintain consistency across services'),
(54,2,FALSE,'A database sharding strategy'),
(54,3,FALSE,'A load balancing technique'),
(54,4,FALSE,'A performance profiling method'),
(55,1,TRUE, 'Verifying that user-supplied data meets expected format and constraints'),
(55,2,FALSE,'Encrypting user input before storage'),
(55,3,FALSE,'Logging every user action'),
(55,4,FALSE,'Formatting output data for display'),
(56,1,TRUE, 'Ensures the annotated field value is not null'),
(56,2,FALSE,'Sets a default value for the field'),
(56,3,FALSE,'Trims whitespace from string values'),
(56,4,FALSE,'Logs a warning when the field is null'),
(57,1,TRUE, 'Validation performed in the browser before submitting to the server'),
(57,2,FALSE,'Validation done only at the database level'),
(57,3,FALSE,'Security-focused server validation'),
(57,4,FALSE,'Validation using external services'),
(58,1,TRUE, 'Whitelist accepts only known-good values; blacklist rejects known-bad values'),
(58,2,FALSE,'Whitelist blocks certain users; blacklist allows specific users only'),
(58,3,FALSE,'Both are used in OAuth authorization flows'),
(58,4,FALSE,'Whitelist is client-side; blacklist is server-side'),
(59,1,TRUE, 'Validating relationships or consistency between multiple fields in the same object'),
(59,2,FALSE,'Validating field values in a database'),
(59,3,FALSE,'Cross-service data integrity checking'),
(59,4,FALSE,'Asynchronous validation of a single field'),
(60,1,TRUE, 'Server-side validation must always be performed independently'),
(60,2,FALSE,'Database-level constraints can be skipped'),
(60,3,FALSE,'Client validation can replace server validation for speed'),
(60,4,FALSE,'Only validate critical fields on the server'),
(61,1,TRUE, 'A Java standard for declaring validation constraints on objects via annotations'),
(61,2,FALSE,'A Spring-specific configuration annotation set'),
(61,3,FALSE,'A data serialisation standard'),
(61,4,FALSE,'A testing framework for persistence entities'),
(62,1,TRUE, 'A user-defined annotation paired with a ConstraintValidator implementation'),
(62,2,FALSE,'A modified built-in constraint annotation'),
(62,3,FALSE,'A database-level check constraint'),
(62,4,FALSE,'An API-level validation interceptor'),
(63,1,TRUE, 'Apply different subsets of constraints in different contexts'),
(63,2,FALSE,'Group error messages by field name'),
(63,3,FALSE,'Validate all fields using one annotation'),
(63,4,FALSE,'Define the order of constraint evaluation'),
(64,1,TRUE, 'Injecting malicious SQL through input fields to manipulate the database'),
(64,2,FALSE,'Optimising SQL statements for performance'),
(64,3,FALSE,'Crashing the database server with large queries'),
(64,4,FALSE,'Encrypting SQL connections'),
(65,1,TRUE, 'Injecting malicious scripts into web pages executed in other users'' browsers'),
(65,2,FALSE,'Cross-origin data sharing'),
(65,3,FALSE,'An external style-sheet formatting exploit'),
(65,4,FALSE,'An XML schema security extension'),
(66,1,TRUE, 'HTTP with TLS/SSL encryption for secure data transmission'),
(66,2,FALSE,'A faster version of the HTTP protocol'),
(66,3,FALSE,'HTTP with header compression'),
(66,4,FALSE,'An HTTP authentication extension'),
(67,1,TRUE, 'Tricking a logged-in user''s browser into sending forged requests to a trusted site'),
(67,2,FALSE,'Injecting scripts into a web page'),
(67,3,FALSE,'Intercepting HTTP traffic in transit'),
(67,4,FALSE,'Overloading a server with requests'),
(68,1,TRUE, 'Instructs the browser on trusted content sources, preventing injection attacks'),
(68,2,FALSE,'Hides the server software version from responses'),
(68,3,FALSE,'Sets request rate limits'),
(68,4,FALSE,'Forces HTTPS connections only'),
(69,1,TRUE, 'Separates SQL code from data, eliminating SQL injection'),
(69,2,FALSE,'Improves query performance through caching'),
(69,3,FALSE,'Reduces database network overhead'),
(69,4,FALSE,'Encrypts sensitive data in queries'),
(70,1,TRUE, 'A regularly updated list of the most critical web application security risks'),
(70,2,FALSE,'A web performance benchmark'),
(70,3,FALSE,'A secure coding standard for Java'),
(70,4,FALSE,'A penetration testing methodology'),
(71,1,TRUE, 'An authorised simulated attack to identify exploitable vulnerabilities'),
(71,2,FALSE,'Performance stress testing'),
(71,3,FALSE,'Automated deployment testing'),
(71,4,FALSE,'Static code quality analysis'),
(72,1,TRUE, 'Checking third-party libraries for publicly disclosed security vulnerabilities'),
(72,2,FALSE,'Scanning source code for logic bugs'),
(72,3,FALSE,'Auditing database permissions'),
(72,4,FALSE,'Monitoring network traffic patterns'),
(73,1,TRUE, 'A test verifying the behaviour of a single isolated unit of code'),
(73,2,FALSE,'A test of the entire application end-to-end'),
(73,3,FALSE,'A UI browser automation test'),
(73,4,FALSE,'A performance benchmark test'),
(74,1,TRUE, 'A simulated replacement for a real dependency used in isolation testing'),
(74,2,FALSE,'An actual production database used in tests'),
(74,3,FALSE,'A browser automation tool'),
(74,4,FALSE,'A load generation tool'),
(75,1,TRUE, 'Stubs provide canned responses; mocks also verify interactions were made'),
(75,2,FALSE,'Stubs are for databases; mocks are for APIs'),
(75,3,FALSE,'Mocks return real data; stubs return empty data'),
(75,4,FALSE,'They are the same thing'),
(76,1,TRUE, 'Writing a failing test first, then minimal code to pass, then refactoring'),
(76,2,FALSE,'Running tests only in production'),
(76,3,FALSE,'Auto-generating tests from existing code'),
(76,4,FALSE,'Testing only after a release is complete'),
(77,1,TRUE, 'Percentage of production code executed during the test suite'),
(77,2,FALSE,'Number of test files in the project'),
(77,3,FALSE,'Count of passing tests relative to failing'),
(77,4,FALSE,'Speed at which tests execute'),
(78,1,TRUE, 'Tests verifying multiple components or layers work correctly together'),
(78,2,FALSE,'Tests executed on a CI server'),
(78,3,FALSE,'Tests verifying third-party APIs'),
(78,4,FALSE,'Tests using real users in staging'),
(79,1,TRUE, 'Verifying API consumer and provider agree on the interface contract'),
(79,2,FALSE,'Testing database schema migrations'),
(79,3,FALSE,'Validating UI design specifications'),
(79,4,FALSE,'Checking open-source licence compliance'),
(80,1,TRUE, 'Introducing small code changes to verify the test suite detects them'),
(80,2,FALSE,'Testing with randomly generated inputs'),
(80,3,FALSE,'Cross-platform test execution'),
(80,4,FALSE,'Running tests in randomised order'),
(81,1,TRUE, 'Fixed state of objects and data used as a known baseline for tests'),
(81,2,FALSE,'A physical test device'),
(81,3,FALSE,'A browser automation driver'),
(81,4,FALSE,'A CI/CD job configuration'),
(82,1,TRUE, 'An event that disrupts the normal execution flow of a program'),
(82,2,FALSE,'A syntax error in source code'),
(82,3,FALSE,'A failed test assertion'),
(82,4,FALSE,'A compiler warning'),
(83,1,TRUE, 'Gracefully handle exceptions and prevent application crashes'),
(83,2,FALSE,'Log all errors to a file'),
(83,3,FALSE,'Stop code execution on any error'),
(83,4,FALSE,'Validate input data'),
(84,1,TRUE, 'Checked must be handled or declared; unchecked do not require explicit handling'),
(84,2,FALSE,'Checked are runtime; unchecked are compile-time'),
(84,3,FALSE,'Only unchecked exceptions can be caught'),
(84,4,FALSE,'Checked cannot be thrown from constructors'),
(85,1,TRUE, '5xx (e.g., 500 Internal Server Error)'),
(85,2,FALSE,'4xx (e.g., 404 Not Found)'),
(85,3,FALSE,'2xx (e.g., 200 OK)'),
(85,4,FALSE,'3xx (e.g., 301 Redirect)'),
(86,1,TRUE, 'A @ControllerAdvice class that handles exceptions centrally for all controllers'),
(86,2,FALSE,'A middleware component for logging all errors'),
(86,3,FALSE,'A frontend error boundary component'),
(86,4,FALSE,'A database error interceptor'),
(87,1,TRUE, 'Provides a standardised machine-readable error format for HTTP API responses'),
(87,2,FALSE,'Logs detailed errors to the server'),
(87,3,FALSE,'Displays error messages in the browser'),
(87,4,FALSE,'Retries failed requests automatically'),
(88,1,TRUE, 'Stops calls to a failing service to prevent cascading failures'),
(88,2,FALSE,'Prevents infinite loops in recursive algorithms'),
(88,3,FALSE,'A security firewall pattern for APIs'),
(88,4,FALSE,'A database connection management strategy'),
(89,1,TRUE, 'Maintaining partial functionality when some components fail'),
(89,2,FALSE,'Logging all exceptions with full stack traces'),
(89,3,FALSE,'Restarting failed services automatically'),
(89,4,FALSE,'Blocking all requests when any error occurs'),
(90,1,TRUE, 'A message queue holding unprocessable messages for later analysis'),
(90,2,FALSE,'A queue for completed requests'),
(90,3,FALSE,'A backup message queue'),
(90,4,FALSE,'A queue for admin notifications'),
(91,1,TRUE, 'Storing frequently accessed data temporarily for faster retrieval'),
(91,2,FALSE,'Archiving old records to reduce database size'),
(91,3,FALSE,'Compressing data before storage'),
(91,4,FALSE,'Encrypting data in memory'),
(92,1,TRUE, 'Total duration from when a request is sent until the full response is received'),
(92,2,FALSE,'The server''s CPU usage during a request'),
(92,3,FALSE,'Number of database queries executed'),
(92,4,FALSE,'Time to start the application server'),
(93,1,TRUE, 'A component limiting overall system throughput'),
(93,2,FALSE,'A configuration error causing crashes'),
(93,3,FALSE,'A memory leak in the application'),
(93,4,FALSE,'An unhandled exception'),
(94,1,TRUE, 'Distributed network serving content from servers geographically close to users'),
(94,2,FALSE,'A type of relational database'),
(94,3,FALSE,'A load testing tool'),
(94,4,FALSE,'An application logging framework'),
(95,1,TRUE, 'Fetching related entities only when first accessed'),
(95,2,FALSE,'Loading all data at application startup'),
(95,3,FALSE,'Caching query results in memory'),
(95,4,FALSE,'Using read replicas for reports'),
(96,1,TRUE, 'Adding more instances of a service to handle increased load'),
(96,2,FALSE,'Upgrading CPU and RAM of a single server'),
(96,3,FALSE,'Splitting an application into microservices'),
(96,4,FALSE,'Clustering database servers'),
(97,1,TRUE, 'A cache shared across multiple service instances (e.g., Redis)'),
(97,2,FALSE,'Per-request in-memory caching'),
(97,3,FALSE,'Browser-side caching of static assets'),
(97,4,FALSE,'On-disk caching of database queries'),
(98,1,TRUE, 'Executing operations in the background without blocking the calling thread'),
(98,2,FALSE,'Processing requests one at a time'),
(98,3,FALSE,'Deferring all reads to off-peak hours'),
(98,4,FALSE,'Batching writes to the database'),
(99,1,TRUE, 'Identifies where an application spends CPU time and memory'),
(99,2,FALSE,'A tool that generates load test traffic'),
(99,3,FALSE,'A code review tool for anti-patterns'),
(99,4,FALSE,'An application monitoring dashboard'),
(100,1,TRUE, 'Internationalization (18 letters between the i and the n)'),
(100,2,FALSE,'Internet Interface 18 standard'),
(100,3,FALSE,'Identity validation notation'),
(100,4,FALSE,'Infrastructure version 18'),
(101,1,TRUE, 'Adapting internationalised software for a specific locale or culture'),
(101,2,FALSE,'A logging framework abbreviation'),
(101,3,FALSE,'Layout normalisation technique'),
(101,4,FALSE,'Load balancing variant'),
(102,1,TRUE, 'A combination of language and regional settings (e.g., fr-BE, en-US)'),
(102,2,FALSE,'A geographic server location'),
(102,3,FALSE,'A test environment name'),
(102,4,FALSE,'A configuration profile'),
(103,1,TRUE, 'Rendering text and layout from right to left for Arabic, Hebrew, etc.'),
(103,2,FALSE,'Real-time logging infrastructure'),
(103,3,FALSE,'A request transfer latency metric'),
(103,4,FALSE,'A routing language type'),
(104,1,TRUE, 'A unique identifier mapped to locale-specific translated strings'),
(104,2,FALSE,'A cryptographic key for secure messages'),
(104,3,FALSE,'A unique user identifier'),
(104,4,FALSE,'A database primary key for messages'),
(105,1,TRUE, 'Different translation strings for singular, plural, and other grammatical forms'),
(105,2,FALSE,'Translating to multiple languages simultaneously'),
(105,3,FALSE,'Storing multiple versions of a document'),
(105,4,FALSE,'Running multiple locale tests in parallel'),
(106,1,TRUE, 'Standard format for locale-sensitive messages with plural rules and variable interpolation'),
(106,2,FALSE,'International CPU standard for computing'),
(106,3,FALSE,'In-cluster unit test format'),
(106,4,FALSE,'Integrated configuration utility'),
(107,1,TRUE, 'Accept-Language header indicating the client''s preferred languages'),
(107,2,FALSE,'Authorization headers for language-specific endpoints'),
(107,3,FALSE,'CORS negotiation headers'),
(107,4,FALSE,'Content-Type matching for character sets'),
(108,1,TRUE, 'Serving a default locale''s translation when none exists for the requested locale'),
(108,2,FALSE,'Rolling back to an older translation version'),
(108,3,FALSE,'Using machine translation when no human translation exists'),
(108,4,FALSE,'Disabling unsupported languages at the UI level');

-- cat 13 deployment (q 109-117) — full 4-language choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en,text_ar,text_nl,text_fr) VALUES
(109,1,TRUE, 'A platform packaging and running applications in containers','منصة تحزم وتشغّل التطبيقات في حاويات','Een platform voor het verpakken en uitvoeren van apps in containers','Une plateforme pour empaqueter et exécuter des applications dans des conteneurs'),
(109,2,FALSE,'A programming language','لغة برمجة','Een programmeertaal','Un langage de programmation'),
(109,3,FALSE,'A cloud service provider','مزوّد خدمة سحابية','Een cloudserviceprovider','Un fournisseur de services cloud'),
(109,4,FALSE,'A database management tool','أداة إدارة قواعد البيانات','Een databasebeheertool','Un outil de gestion de base de données'),

(110,1,TRUE, 'Continuous Integration / Continuous Delivery (or Deployment)','التكامل المستمر / التسليم المستمر (أو النشر المستمر)','Continue Integratie / Continue Levering (of Implementatie)','Intégration Continue / Livraison Continue (ou Déploiement Continu)'),
(110,2,FALSE,'Clustered Infrastructure / Clustered Deployment','بنية تحتية مجمّعة / نشر مجمّع','Geclusterde Infrastructuur / Geclusterde Implementatie','Infrastructure Clusterisée / Déploiement Clusterisé'),
(110,3,FALSE,'Code Integration / Code Deployment','تكامل الكود / نشر الكود','Code-integratie / Code-implementatie','Intégration de Code / Déploiement de Code'),
(110,4,FALSE,'Combined Inspection / Combined Distribution','فحص مجمّع / توزيع مجمّع','Gecombineerde Inspectie / Gecombineerde Distributie','Inspection Combinée / Distribution Combinée'),

(111,1,TRUE, 'A script with instructions to build a Docker image','سكريبت بتعليمات لبناء صورة Docker','Een script met instructies om een Docker-image te bouwen','Un script avec des instructions pour construire une image Docker'),
(111,2,FALSE,'A container runtime configuration','إعداد وقت تشغيل الحاوية','Een container-runtimeconfiguratie','Une configuration de l''environnement d''exécution des conteneurs'),
(111,3,FALSE,'A Kubernetes deployment manifest','ملف بيان نشر Kubernetes','Een Kubernetes-implementatiemanifest','Un manifeste de déploiement Kubernetes'),
(111,4,FALSE,'A network routing configuration','إعداد توجيه الشبكة','Een netwerkrouteringsconfiguratie','Une configuration de routage réseau'),

(112,1,TRUE, 'Containers share the host OS kernel; VMs each include a full guest OS','الحاويات تشترك بنواة نظام التشغيل؛ الأجهزة الافتراضية لها نظام ضيف كامل','Containers delen de OS-kernel; VM''s bevatten elk een volledig gast-OS','Les conteneurs partagent le noyau hôte ; les VM ont chacune un OS invité complet'),
(112,2,FALSE,'Containers are slower and use more resources than VMs','الحاويات أبطأ وتستهلك موارد أكثر من الأجهزة الافتراضية','Containers zijn langzamer en verbruiken meer middelen dan VM''s','Les conteneurs sont plus lents et consomment plus que les VM'),
(112,3,FALSE,'VMs provide less isolation than containers','الأجهزة الافتراضية توفر عزلاً أقل من الحاويات','VM''s bieden minder isolatie dan containers','Les VM offrent moins d''isolation que les conteneurs'),
(112,4,FALSE,'Containers require dedicated hardware','الحاويات تتطلب أجهزة مخصصة','Containers vereisen speciale hardware','Les conteneurs nécessitent du matériel dédié'),

(113,1,TRUE, 'Automated container orchestration, scaling, and self-healing','تنسيق الحاويات تلقائياً والتوسعة والإصلاح الذاتي','Geautomatiseerde containerorkestratie, schaling en zelfherstel','Orchestration automatisée des conteneurs, mise à l''échelle et auto-réparation'),
(113,2,FALSE,'Building and pushing Docker images','بناء ودفع صور Docker','Docker-images bouwen en pushen','Construire et pousser des images Docker'),
(113,3,FALSE,'Writing Infrastructure as Code','كتابة البنية التحتية كرمز','Infrastructure as Code schrijven','Écrire l''Infrastructure as Code'),
(113,4,FALSE,'Database administration and scaling','إدارة قواعد البيانات وتوسيعها','Databasebeheer en schaling','Administration et mise à l''échelle de bases de données'),

(114,1,TRUE, 'Lets infrastructure verify an application instance is running and ready','يُمكّن البنية التحتية من التحقق أن المثيل يعمل وجاهز','Laat infrastructuur verifiëren dat een instantie actief en gereed is','Permet à l''infrastructure de vérifier qu''une instance fonctionne et est prête'),
(114,2,FALSE,'A security vulnerability scan','فحص لثغرات أمنية','Een beveiligingskwetsbaarhedenscan','Un scan de vulnérabilités de sécurité'),
(114,3,FALSE,'A performance load test','اختبار حمل لقياس الأداء','Een prestatiebelastingstest','Un test de charge de performance'),
(114,4,FALSE,'A log aggregation endpoint','نقطة نهاية تجميع السجلات','Een logaggregatie-eindpunt','Un point de terminaison d''agrégation de logs'),

(115,1,TRUE, 'Running two identical environments and switching traffic to the new one after verification','تشغيل بيئتين متطابقتين وتحويل الحركة للجديدة بعد التحقق','Twee identieke omgevingen draaien en verkeer naar de nieuwe schakelen na verificatie','Deux environnements identiques; le trafic est basculé vers le nouveau après vérification'),
(115,2,FALSE,'A two-phase build and test process','عملية بناء واختبار ثنائية المراحل','Een tweefasen bouw- en testproces','Un processus de construction et de test en deux phases'),
(115,3,FALSE,'A staged rollback strategy','استراتيجية تراجع مرحلية','Een gefaseerde terugrolstrategie','Une stratégie de retour arrière par étapes'),
(115,4,FALSE,'A multi-region deployment model','نموذج نشر متعدد المناطق','Een multi-regio implementatiemodel','Un modèle de déploiement multi-régions'),

(116,1,TRUE, 'Gradually routing a small percentage of traffic to a new version','توجيه نسبة صغيرة من الحركة تدريجياً إلى الإصدار الجديد','Geleidelijk een klein percentage verkeer naar een nieuwe versie routeren','Router progressivement un faible pourcentage de trafic vers la nouvelle version'),
(116,2,FALSE,'A security testing strategy before release','استراتيجية اختبار أمني قبل الإصدار','Een beveiligingstestsstrategie vóór release','Une stratégie de test de sécurité avant la release'),
(116,3,FALSE,'An automated rollback mechanism','آلية تراجع تلقائية','Een geautomatiseerd terugrolmechanisme','Un mécanisme de retour arrière automatisé'),
(116,4,FALSE,'A CI/CD test suite execution mode','وضع تنفيذ مجموعة اختبارات CI/CD','Een CI/CD-testsuite-uitvoeringsmodus','Un mode d''exécution de suite de tests CI/CD'),

(117,1,TRUE, 'Managing infrastructure through version-controlled, machine-readable definition files','إدارة البنية التحتية من خلال ملفات تعريف يمكن قراءتها آلياً وخاضعة للتحكم بالإصدار','Infrastructuur beheren via versiebeheerde, machineleesbare definitiebestanden','Gérer l''infrastructure via des fichiers de définition contrôlés par version et lisibles par machine'),
(117,2,FALSE,'Writing application code that configures servers','كتابة كود تطبيق لإعداد الخوادم','Applicatiecode schrijven die servers configureert','Écrire du code d''application qui configure les serveurs'),
(117,3,FALSE,'A cloud cost optimisation approach','مقاربة تحسين تكاليف السحابة','Een kostenoptimalisatiebenadering voor de cloud','Une approche d''optimisation des coûts cloud'),
(117,4,FALSE,'Container security scanning','فحص أمان الحاويات','Beveiligingsscan van containers','Analyse de sécurité des conteneurs');

-- cats 14-19 (q 118-171) — English-only choices
INSERT INTO dev_exam_choices (question_id,sort_order,is_correct,text_en) VALUES
(118,1,TRUE, 'Recording events, messages, and errors for diagnostics and auditing'),
(118,2,FALSE,'Storing user data in files'),
(118,3,FALSE,'Writing deployment configuration'),
(118,4,FALSE,'Testing code output'),
(119,1,TRUE, 'A severity classification for messages: DEBUG, INFO, WARN, ERROR'),
(119,2,FALSE,'The maximum size of a log file'),
(119,3,FALSE,'The number of log files retained'),
(119,4,FALSE,'The path where logs are stored'),
(120,1,TRUE, 'Continuously observing system health, performance, and availability'),
(120,2,FALSE,'Writing diagnostic messages to files'),
(120,3,FALSE,'Testing new features before release'),
(120,4,FALSE,'Backing up database records'),
(121,1,TRUE, 'Writing log entries in a machine-parseable format like JSON'),
(121,2,FALSE,'Logging only at the ERROR level'),
(121,3,FALSE,'Grouping log files by date'),
(121,4,FALSE,'Archiving old log files'),
(122,1,TRUE, 'Tracking response times, error rates, and resource usage of an application'),
(122,2,FALSE,'Anti-pattern methodology documentation'),
(122,3,FALSE,'API platform management'),
(122,4,FALSE,'Authentication policy module'),
(123,1,TRUE, 'A time-series quantitative measurement of system behaviour'),
(123,2,FALSE,'A structured log entry'),
(123,3,FALSE,'A distributed trace span'),
(123,4,FALSE,'A health check result'),
(124,1,TRUE, 'Tracking a request''s journey across multiple services using a correlation ID'),
(124,2,FALSE,'Logging database queries across shards'),
(124,3,FALSE,'Monitoring frontend interactions only'),
(124,4,FALSE,'Testing API endpoints one by one'),
(125,1,TRUE, 'A contractual commitment defining expected service performance and availability'),
(125,2,FALSE,'A service versioning convention'),
(125,3,FALSE,'A deployment manifest format'),
(125,4,FALSE,'A server location assignment'),
(126,1,TRUE, 'Automatically notifying engineers when metrics exceed defined thresholds'),
(126,2,FALSE,'Creating manual incident reports'),
(126,3,FALSE,'Logging all requests at INFO level'),
(126,4,FALSE,'Archiving metrics older than 30 days'),
(127,1,TRUE, 'Automatically building and testing code on each commit'),
(127,2,FALSE,'Manually reviewing code before each deployment'),
(127,3,FALSE,'A database migration strategy'),
(127,4,FALSE,'Automatic documentation generation'),
(128,1,TRUE, 'An automated sequence of build, test, and deploy steps triggered by code changes'),
(128,2,FALSE,'A log of previous deployments'),
(128,3,FALSE,'A Docker container configuration'),
(128,4,FALSE,'A network routing rule'),
(129,1,TRUE, 'Early detection of integration issues and regressions'),
(129,2,FALSE,'Eliminating the need for code reviews'),
(129,3,FALSE,'Automatic generation of user documentation'),
(129,4,FALSE,'Faster database queries'),
(130,1,TRUE, 'A versioned, packaged build output ready to be deployed'),
(130,2,FALSE,'A test execution report'),
(130,3,FALSE,'A source code configuration file'),
(130,4,FALSE,'A build log file'),
(131,1,TRUE, 'Reverting to a previous known-good version when a deployment fails'),
(131,2,FALSE,'Merging feature branches into main'),
(131,3,FALSE,'Archiving old build artifacts'),
(131,4,FALSE,'Cleaning up test environments'),
(132,1,TRUE, 'Automatically deploying every change that passes all pipeline tests to production'),
(132,2,FALSE,'Manually approving every deployment'),
(132,3,FALSE,'Deploying once a week on a schedule'),
(132,4,FALSE,'Deploying only to staging environments automatically'),
(133,1,TRUE, 'Using Git as the single source of truth for infrastructure and deployments'),
(133,2,FALSE,'GitHub enterprise workflow optimisation'),
(133,3,FALSE,'A Git branching optimisation strategy'),
(133,4,FALSE,'Graph-based operations for CI systems'),
(134,1,TRUE, 'Enables or disables features at runtime via configuration without redeploying'),
(134,2,FALSE,'A Git branch naming rule'),
(134,3,FALSE,'A frontend route guard'),
(134,4,FALSE,'A database schema permission'),
(135,1,TRUE, 'Moving testing and security checks earlier in the development process'),
(135,2,FALSE,'Deploying to the left region first in multi-region deployments'),
(135,3,FALSE,'Using left-justified log formatting'),
(135,4,FALSE,'Writing feature branches from left to right'),
(136,1,TRUE, 'An HTTP encoding used for uploading files alongside form fields'),
(136,2,FALSE,'A JSON API request type'),
(136,3,FALSE,'A WebSocket connection type'),
(136,4,FALSE,'A database query type'),
(137,1,TRUE, 'A standard identifier for the format of content (e.g., image/png)'),
(137,2,FALSE,'A compression algorithm'),
(137,3,FALSE,'A file encryption scheme'),
(137,4,FALSE,'A caching strategy'),
(138,1,TRUE, 'Ensure files meet expected type and size constraints and prevent malicious uploads'),
(138,2,FALSE,'Encrypt the uploaded file'),
(138,3,FALSE,'Index the file in the search engine'),
(138,4,FALSE,'Compress the file automatically'),
(139,1,TRUE, 'Processing data in chunks without loading the entire file into memory'),
(139,2,FALSE,'Broadcasting file content to multiple clients'),
(139,3,FALSE,'Real-time file synchronisation'),
(139,4,FALSE,'Parallel download from multiple servers'),
(140,1,TRUE, 'A temporary URL with embedded credentials allowing direct upload to object storage'),
(140,2,FALSE,'A permanent public CDN link'),
(140,3,FALSE,'A URL requiring separate authentication'),
(140,4,FALSE,'A direct path to the server file system'),
(141,1,TRUE, 'Prevent filename collisions and path traversal attacks'),
(141,2,FALSE,'Improve search indexing'),
(141,3,FALSE,'Enable faster downloads'),
(141,4,FALSE,'Support multiple file formats'),
(142,1,TRUE, 'An upload that can continue from where it stopped after an interruption'),
(142,2,FALSE,'A compressed upload using chunked encoding'),
(142,3,FALSE,'Parallel upload from multiple sources'),
(142,4,FALSE,'A verified upload with checksum validation'),
(143,1,TRUE, 'Storing files indexed by the hash of their content, enabling deduplication'),
(143,2,FALSE,'Organising files alphabetically by name'),
(143,3,FALSE,'Timestamp-based file organisation'),
(143,4,FALSE,'Permission-based storage directories'),
(144,1,TRUE, 'Path traversal attacks using crafted filenames to access server directories'),
(144,2,FALSE,'File too small error'),
(144,3,FALSE,'Slow download speeds'),
(144,4,FALSE,'Incorrect MIME type in response'),
(145,1,TRUE, 'Generating a downloadable file containing application data'),
(145,2,FALSE,'Moving data between databases'),
(145,3,FALSE,'Archiving old records'),
(145,4,FALSE,'Backing up configuration files'),
(146,1,TRUE, 'A plain text file using commas to separate values in a tabular format'),
(146,2,FALSE,'A compressed SQL view'),
(146,3,FALSE,'A binary data file'),
(146,4,FALSE,'A cache storage value file'),
(147,1,TRUE, 'Splitting large result sets across multiple pages'),
(147,2,FALSE,'Filtering out duplicate records'),
(147,3,FALSE,'Sorting records alphabetically'),
(147,4,FALSE,'Encrypting report data'),
(148,1,TRUE, 'A predefined layout or structure used to generate consistent reports'),
(148,2,FALSE,'A database view'),
(148,3,FALSE,'An API response schema'),
(148,4,FALSE,'A log format specification'),
(149,1,TRUE, 'Computing summary statistics (count, sum, average) over a dataset'),
(149,2,FALSE,'Merging multiple database tables'),
(149,3,FALSE,'Caching query results'),
(149,4,FALSE,'Exporting raw data without processing'),
(150,1,TRUE, 'Automatically generated and delivered at configured time intervals'),
(150,2,FALSE,'Generated only on user request'),
(150,3,FALSE,'Runs inside a database transaction'),
(150,4,FALSE,'Restricted to admin users only'),
(151,1,TRUE, 'Extract data from source, Transform it, and Load into a target system'),
(151,2,FALSE,'Error testing level methodology'),
(151,3,FALSE,'Event timeline logging format'),
(151,4,FALSE,'External token layer protocol'),
(152,1,TRUE, 'A centralised repository optimised for analytical queries and historical reporting'),
(152,2,FALSE,'A high-performance transactional database'),
(152,3,FALSE,'A file storage system'),
(152,4,FALSE,'A backup database replica'),
(153,1,TRUE, 'Storing generated report output to serve repeat requests without regeneration'),
(153,2,FALSE,'Compressing report files'),
(153,3,FALSE,'Archiving old reports'),
(153,4,FALSE,'Encrypting sensitive report data'),
(154,1,TRUE, 'A request to find records matching specified criteria'),
(154,2,FALSE,'A SQL table creation statement'),
(154,3,FALSE,'A REST GET request'),
(154,4,FALSE,'A database backup command'),
(155,1,TRUE, 'A condition narrowing the result set to only matching records'),
(155,2,FALSE,'A mechanism to sort results'),
(155,3,FALSE,'A tool to delete records'),
(155,4,FALSE,'A data transformation rule'),
(156,1,TRUE, 'Ordering result records by one or more fields'),
(156,2,FALSE,'Filtering by a specific value'),
(156,3,FALSE,'Paging through results'),
(156,4,FALSE,'Aggregating field values'),
(157,1,TRUE, 'Searching within the content of text fields rather than by exact value'),
(157,2,FALSE,'Searching only within primary key column'),
(157,3,FALSE,'Prefix-matching only on indexed columns'),
(157,4,FALSE,'Case-insensitive sorting'),
(158,1,TRUE, 'Enabling users to filter results by multiple attribute categories simultaneously'),
(158,2,FALSE,'Keyword auto-completion'),
(158,3,FALSE,'Synonym-based result expansion'),
(158,4,FALSE,'Fuzzy string matching'),
(159,1,TRUE, 'Skipping a fixed number of records to retrieve a specific page'),
(159,2,FALSE,'Using a cursor pointer for stable navigation'),
(159,3,FALSE,'Loading all data at once'),
(159,4,FALSE,'Filtering by a date range'),
(160,1,TRUE, 'A collection of documents optimised for full-text search and analytics'),
(160,2,FALSE,'A SQL index on a relational table'),
(160,3,FALSE,'A CDN configuration file'),
(160,4,FALSE,'A deployment manifest'),
(161,1,TRUE, 'Using a stable pointer to track position, avoiding offset shifting'),
(161,2,FALSE,'Skipping fixed page offsets'),
(161,3,FALSE,'Sorting by a random key'),
(161,4,FALSE,'Caching page results indefinitely'),
(162,1,TRUE, 'Ranking results by how closely they match the query using algorithms like TF-IDF'),
(162,2,FALSE,'Showing results in insertion order'),
(162,3,FALSE,'Filtering by a minimum match percentage'),
(162,4,FALSE,'Grouping results by category'),
(163,1,TRUE, 'A named value set in the OS environment and read by the application at runtime'),
(163,2,FALSE,'A Java local variable'),
(163,3,FALSE,'A CSS variable'),
(163,4,FALSE,'A SQL column'),
(164,1,TRUE, 'Externalized configuration file for a Spring Boot application'),
(164,2,FALSE,'Maven dependency definition'),
(164,3,FALSE,'Docker container configuration'),
(164,4,FALSE,'Test data file'),
(165,1,TRUE, 'A named set of configuration properties activated for a specific environment'),
(165,2,FALSE,'A user preference file'),
(165,3,FALSE,'A deployment artifact'),
(165,4,FALSE,'A test fixture'),
(166,1,TRUE, 'Keeping configuration values outside the deployable application artifact'),
(166,2,FALSE,'Encrypting all configuration files'),
(166,3,FALSE,'Hardcoding all constants in the source code'),
(166,4,FALSE,'Deleting unused configuration files'),
(167,1,TRUE, 'Activating different beans and properties per environment'),
(167,2,FALSE,'Defining user roles'),
(167,3,FALSE,'Managing application versions'),
(167,4,FALSE,'Configuring build variants'),
(168,1,TRUE, 'A sensitive value (password, API key) that must not be stored in plain text'),
(168,2,FALSE,'A hidden configuration option'),
(168,3,FALSE,'A debug-only parameter'),
(168,4,FALSE,'A test environment variable'),
(169,1,TRUE, 'Centralised configuration management for all microservices'),
(169,2,FALSE,'An authentication service'),
(169,3,FALSE,'An API gateway'),
(169,4,FALSE,'A message broker'),
(170,1,TRUE, 'Store configuration in the environment, not in the codebase'),
(170,2,FALSE,'Use exactly 12 configuration properties'),
(170,3,FALSE,'Configuration should be defined in 12 separate files'),
(170,4,FALSE,'Share configuration between all application instances'),
(171,1,TRUE, 'A configuration toggle enabling or disabling features without redeployment'),
(171,2,FALSE,'A database schema permission flag'),
(171,3,FALSE,'A network routing rule'),
(171,4,FALSE,'A test environment setup toggle');
