ALTER TABLE sign_questions
  MODIFY COLUMN question_type ENUM(
    'IS_IT_ALLOWED',
    'WHAT_DOES_IT_MEAN',
    'WHAT_MUST_YOU_DO',
    'WHICH_SIGN',
    'HAZARD_IDENTIFICATION',
    'DRIVER_ACTION',
    'SIGN_PLACEMENT_DISTANCE'
  ) NOT NULL;
