-- Phase 4: Learning System - Create Tables for Lessons and Questions

-- Lessons Table
CREATE TABLE lessons (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    title_ar TEXT NOT NULL,
    title_en TEXT NOT NULL,
    title_nl TEXT NOT NULL,
    title_fr TEXT NOT NULL,
    content_ar TEXT NOT NULL,
    content_en TEXT NOT NULL,
    content_nl TEXT NOT NULL,
    content_fr TEXT NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    estimated_minutes INT NOT NULL DEFAULT 5,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    INDEX idx_category (category_id),
    INDEX idx_display_order (display_order),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Practice Questions Table (linked to lessons)
CREATE TABLE practice_questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lesson_id BIGINT NOT NULL,
    question_ar TEXT NOT NULL,
    question_en TEXT NOT NULL,
    question_nl TEXT NOT NULL,
    question_fr TEXT NOT NULL,
    option1_ar TEXT NOT NULL,
    option1_en TEXT NOT NULL,
    option1_nl TEXT NOT NULL,
    option1_fr TEXT NOT NULL,
    option2_ar TEXT NOT NULL,
    option2_en TEXT NOT NULL,
    option2_nl TEXT NOT NULL,
    option2_fr TEXT NOT NULL,
    option3_ar TEXT NOT NULL,
    option3_en TEXT NOT NULL,
    option3_nl TEXT NOT NULL,
    option3_fr TEXT NOT NULL,
    option4_ar TEXT NOT NULL,
    option4_en TEXT NOT NULL,
    option4_nl TEXT NOT NULL,
    option4_fr TEXT NOT NULL,
    correct_answer INT NOT NULL,
    explanation_ar TEXT,
    explanation_en TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
    INDEX idx_lesson (lesson_id),
    INDEX idx_display_order (display_order),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Exam Questions Table (for random 50-question exams)
CREATE TABLE exam_questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    question_ar TEXT NOT NULL,
    question_en TEXT NOT NULL,
    question_nl TEXT NOT NULL,
    question_fr TEXT NOT NULL,
    option1_ar TEXT NOT NULL,
    option1_en TEXT NOT NULL,
    option1_nl TEXT NOT NULL,
    option1_fr TEXT NOT NULL,
    option2_ar TEXT NOT NULL,
    option2_en TEXT NOT NULL,
    option2_nl TEXT NOT NULL,
    option2_fr TEXT NOT NULL,
    option3_ar TEXT NOT NULL,
    option3_en TEXT NOT NULL,
    option3_nl TEXT NOT NULL,
    option3_fr TEXT NOT NULL,
    option4_ar TEXT NOT NULL,
    option4_en TEXT NOT NULL,
    option4_nl TEXT NOT NULL,
    option4_fr TEXT NOT NULL,
    correct_answer INT NOT NULL,
    explanation_ar TEXT,
    explanation_en TEXT,
    explanation_nl TEXT,
    explanation_fr TEXT,
    image_url VARCHAR(500),
    difficulty ENUM('EASY', 'MEDIUM', 'HARD') NOT NULL DEFAULT 'MEDIUM',
    is_important BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    INDEX idx_category (category_id),
    INDEX idx_difficulty (difficulty),
    INDEX idx_important (is_important),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
