-- ============================================================================
-- V90: Seed E-category (parking/stationnement) traffic signs
-- ============================================================================
-- These 20 signs were missing from the original seeding migrations.
-- They represent Belgian E-category parking regulation signs (category_id = 5).
-- Canonical source: readyroad/src/main/resources/data/signs.json
-- Safe to re-run: each INSERT uses WHERE NOT EXISTS to skip existing sign_code rows.
-- ============================================================================

-- E1
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E1', 5, 'No parking', 'Parkeerverbod', 'Interdiction de stationnement', 'ممنوع الوقوف', 'No parking', 'Parkeerverbod', 'Interdiction de stationnement', 'ممنوع الوقوف', 'This traffic sign indicates that parking is prohibited at this location, but temporary stopping to let passengers in or out is allowed.', 'Dit verkeersbord geeft aan dat parkeren verboden is op deze plaats, maar tijdelijk stilstaan om passagiers te laten in- of uitstappen is wel toegestaan.', 'Ce panneau indique que le stationnement est interdit à cet endroit, mais un arrêt temporaire pour faire monter ou descendre des passagers est autorisé.', 'تشير هذه العلامة المرورية إلى أن وقوف السيارات محظور في هذا الموقع، ولكن يسمح بالتوقف المؤقت للسماح للركاب بالدخول أو الخروج.', 'images/signs/parkeren/E1 Parkeerverbod.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E1');

-- E3
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E3', 5, 'No stopping and parking', 'Stilstaan en parkeren verboden', 'Arrêt et stationnement interdits', 'لا توقف ومواقف السيارات', 'No stopping and parking', 'Stilstaan en parkeren verboden', 'Arrêt et stationnement interdits', 'لا توقف ومواقف السيارات', 'This traffic sign indicates that stopping and parking are completely prohibited at this location for any reason. Violation results in a traffic fine.', 'Dit verkeersbord geeft aan dat stilstaan en parkeren volledig verboden zijn op deze plaats, om welke reden dan ook. Overtreding leidt tot een verkeersboete.', 'Ce panneau indique que l arrêt et le stationnement sont totalement interdits à cet endroit, quelle que soit la raison. Une infraction entraîne une amende.', 'تشير هذه العلامة المرورية إلى أن التوقف والوقوف ممنوع تماماً في هذا الموقع لأي سبب من الأسباب. المخالفة تؤدي إلى غرامة مرورية.', 'images/signs/parkeren/E3 Stilstaan en parkeren verboden.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E3');

-- E5
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E5', 5, 'No parking from the 1st to the 15th of the month', 'Parkeerverbod van de 1e tot de 15e van de maand', 'Interdiction de stationnement du 1er au 15 du mois', 'ممنوع ركن السيارات من 1 إلى 15 من الشهر', 'No parking from the 1st to the 15th of the month', 'Parkeerverbod van de 1e tot de 15e van de maand', 'Interdiction de stationnement du 1er au 15 du mois', 'ممنوع ركن السيارات من 1 إلى 15 من الشهر', 'This traffic sign indicates that parking is prohibited during the first half of each month on this side of the road. This regulation aims to maintain traffic flow and prevent the road from tilting to one side.', 'Dit verkeersbord geeft aan dat parkeren verboden is gedurende de eerste helft van elke maand aan deze kant van de weg. Deze regeling is bedoeld om de doorstroming van het verkeer te behouden en te voorkomen dat de weg naar één kant helt.', 'Ce panneau indique que le stationnement est interdit pendant la première moitié de chaque mois de ce côté de la route. Cette réglementation vise à maintenir la fluidité du trafic et à éviter que la route ne penche d''un seul côté.', 'تشير هذه العلامة المرورية إلى منع الوقوف خلال النصف الأول من كل شهر على هذا الجانب من الطريق. وتهدف هذه اللائحة إلى المحافظة على انسيابية حركة المرور ومنع الطريق من الميل إلى أحد الجانبين.', 'images/signs/parkeren/E5 Parkeerverbod van de 1e tot de 15e van de maand.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E5');

-- E7
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E7', 5, 'No parking from the 16th to the end of the month', 'Parkeerverbod van de 16e tot het einde van de maand', 'Interdiction de stationnement du 16 à la fin du mois', 'ممنوع ركن السيارات من يوم 16 حتى نهاية الشهر', 'No parking from the 16th to the end of the month', 'Parkeerverbod van de 16e tot het einde van de maand', 'Interdiction de stationnement du 16 à la fin du mois', 'ممنوع ركن السيارات من يوم 16 حتى نهاية الشهر', 'This traffic sign indicates that parking is prohibited during the second half of each month (from the 16th to the 31st) on this side of the road. This regulation aims to maintain traffic flow.', 'Dit verkeersbord geeft aan dat parkeren verboden is gedurende de tweede helft van elke maand (van de 16e tot de 31e) aan deze kant van de weg. Deze regeling is bedoeld om de doorstroming van het verkeer te behouden.', 'Ce panneau indique que le stationnement est interdit pendant la deuxième moitié de chaque mois (du 16 au 31) de ce côté de la route. Cette réglementation vise à maintenir la fluidité du trafic.', 'تشير هذه العلامة المرورية إلى منع الوقوف خلال النصف الثاني من كل شهر (من اليوم 16 إلى يوم 31) على هذا الجانب من الطريق. وتهدف هذه اللائحة إلى الحفاظ على تدفق حركة المرور.', 'images/signs/parkeren/E7 Parkeerverbod van de 16e tot het einde van de maand.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E7');

-- E9a
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a', 5, 'Parking for electric vehicles', 'Parkeerplaats voor elektrische voertuigen', 'Parking pour véhicules électriques', 'مواقف للسيارات الكهربائية', 'Parking for electric vehicles', 'Parkeerplaats voor elektrische voertuigen', 'Parking pour véhicules électriques', 'مواقف للسيارات الكهربائية', 'This traffic sign indicates that parking is only allowed for electric vehicles. This space is exclusively intended for cars that run on electric energy and is often equipped with a charging point.', 'Dit verkeersbord geeft aan dat parkeren alleen is toegestaan voor elektrische voertuigen. Deze plek is exclusief bestemd voor auto''s die op elektrische energie rijden en vaak voorzien van een laadpunt.', 'Ce panneau de signalisation indique que le stationnement est uniquement autorisé pour les véhicules électriques. Cet emplacement est exclusivement destiné aux voitures fonctionnant à l''énergie électrique et souvent équipé d''une borne de recharge.', 'تشير هذه العلامة المرورية إلى أنه يسمح بوقوف السيارات الكهربائية فقط. هذه المساحة مخصصة حصريًا للسيارات التي تعمل بالطاقة الكهربائية وغالبًا ما تكون مجهزة بنقطة شحن.', 'images/signs/parkeren/E9a - Parkeren toegelaten.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a');

-- E9a-v2
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a-v2', 5, 'Parking allowed', 'Parkeren toegelaten', 'Stationnement autorisé', 'وقوف السيارات مسموح به', 'Parking allowed', 'Parkeren toegelaten', 'Stationnement autorisé', 'وقوف السيارات مسموح به', 'This traffic sign indicates that parking is allowed for all types of vehicles without exception. It is not limited to a specific type of vehicle.', 'Dit verkeersbord geeft aan dat parkeren is toegestaan voor alle soorten voertuigen zonder uitzondering. Het is niet beperkt tot een specifiek type voertuig.', 'Ce panneau de signalisation indique que le stationnement est autorisé pour tous les types de véhicules sans exception. Il n''est pas limité à un type de véhicule spécifique.', 'تشير هذه العلامة المرورية إلى السماح بوقوف جميع أنواع المركبات دون استثناء. ولا يقتصر على نوع معين من المركبات.', 'assets/signs/parkeren/E9a - Parkeren toegelaten.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a-v2');

-- E9a-v3
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a-v3', 5, 'Parking space for electric charging', 'Parkeerplaats voor elektrisch opladen', 'Place de stationnement pour recharge électrique', 'مكان لوقوف السيارات للشحن الكهربائي', 'Parking space for electric charging', 'Parkeerplaats voor elektrisch opladen', 'Place de stationnement pour recharge électrique', 'مكان لوقوف السيارات للشحن الكهربائي', 'This traffic sign indicates that the parking space is reserved for electric vehicles that need to charge. The car must be connected to the charging station while parked.', 'Dit verkeersbord geeft aan dat de parkeerplaats is gereserveerd voor elektrische voertuigen die moeten opladen. De auto moet aangesloten zijn op de laadpaal tijdens het parkeren.', 'Ce panneau indique que la place de stationnement est réservée aux véhicules électriques qui doivent se recharger. La voiture doit être branchée à la borne de recharge pendant le stationnement.', 'تشير إشارة المرور هذه إلى أن مكان ركن السيارة مخصص للسيارات الكهربائية التي تحتاج إلى الشحن. يجب أن تكون السيارة متصلة بمحطة الشحن أثناء وقوفها.', 'assets/signs/parkeren/E9a Elektrisch opladen.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a-v3');

-- E9a-v6
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a-v6', 5, 'Time-limited parking with parking disc', 'Parkeren beperkt in tijd met parkeerschijf', 'Stationnement limite dans le temps avec disque de stationnement', 'وقوف السيارات لفترة محدودة مع قرص وقوف السيارات', 'Time-limited parking with parking disc', 'Parkeren beperkt in tijd met parkeerschijf', 'Stationnement limite dans le temps avec disque de stationnement', 'وقوف السيارات لفترة محدودة مع قرص وقوف السيارات', 'Parking is allowed here for a limited time (maximum 30 minutes). A parking disc is required. Extending parking time is not allowed; if you wish to stay longer, you must leave the parking spot and return later.', 'Parkeren is hier toegestaan voor een beperkte tijd (maximaal 30 minuten). Een parkeerschijf is verplicht. Verlenging van de parkeertijd is niet toegestaan; als u langer wilt blijven, moet u de parkeerplaats verlaten en later terugkeren.', 'Le stationnement est autorise ici pour une duree limitee (30 minutes maximum). Un disque de stationnement est obligatoire. La prolongation du temps de stationnement n est pas autorisee; si vous souhaitez rester plus longtemps, vous devez quitter la place et revenir plus tard.', 'يُسمح بوقوف السيارات هنا لفترة محدودة (بحد أقصى 30 دقيقة). مطلوب قرص وقوف السيارات. لا يسمح بتمديد وقت وقوف السيارات. إذا كنت ترغب في البقاء لفترة أطول، يجب عليك مغادرة مكان وقوف السيارات والعودة في وقت لاحق.', 'assets/signs/parkeren/E9a parkeerschijf Parkeren beperkt in tijd, parkeerschijf verplicht.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a-v6');

-- E9a-v7
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a-v7', 5, 'Parking for disabled persons', 'Parkeren voor mindervaliden', 'Stationnement pour personnes handicapees', 'مواقف سيارات للأشخاص ذوي الإعاقة', 'Parking for disabled persons', 'Parkeren voor mindervaliden', 'Stationnement pour personnes handicapees', 'مواقف سيارات للأشخاص ذوي الإعاقة', 'This parking space is reserved for persons with an official disability card issued by the government. Other vehicles are not allowed to park here. Temporary stopping is only allowed if the driver remains behind the wheel.', 'Deze parkeerplaats is gereserveerd voor personen met een officiele gehandicaptenkaart uitgegeven door de overheid. Andere voertuigen mogen hier niet parkeren. Tijdelijk stilstaan is alleen toegestaan als de bestuurder achter het stuur blijft zitten.', 'Cette place de stationnement est reservee aux personnes detenant une carte de handicap officielle delivree par l etat. Les autres vehicules ne peuvent pas stationner ici. Un arret temporaire n est autorise que si le conducteur reste au volant.', 'مكان ركن السيارات هذا مخصص للأشخاص الذين يحملون بطاقة إعاقة رسمية صادرة عن الحكومة. لا يُسمح للمركبات الأخرى بالوقوف هنا. لا يُسمح بالتوقف المؤقت إلا في حالة بقاء السائق خلف عجلة القيادة.', 'assets/signs/parkeren/E9a mindervaliden Parkeren enkel toegelaten voor mindervaliden.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a-v7');

-- E9a-v10
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9a-v10', 5, 'E9a Parking allowed', 'E9a - Parkeerzone speciale bestemming', 'E9a Stationnement autorisé', 'E9a مسموح بوقوف السيارات', 'E9a Parking allowed', 'E9a - Parkeerzone speciale bestemming', 'E9a Stationnement autorisé', 'E9a مسموح بوقوف السيارات', 'Parking sign: follow the indicated parking rules.', 'Parkeerbord: Parkeren toegelaten. Volg de aangegeven parkeerregels.', 'Panneau de stationnement : suivez les règles de stationnement indiquées.', 'علامة وقوف السيارات: اتبع قواعد وقوف السيارات المشار إليها.', NULL, TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9a-v10'); -- image removed

-- E9b
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9b', 5, 'Parking for cars only', 'Parkeren uitsluitend voor auto''s', 'Stationnement reserve aux voitures', 'مواقف للسيارات فقط', 'Parking for cars only', 'Parkeren uitsluitend voor auto''s', 'Stationnement reserve aux voitures', 'مواقف للسيارات فقط', 'This traffic sign indicates that this parking space is exclusively for small private cars with a maximum weight of 3.5 tons. Trucks or buses heavier than 3.5 tons are not allowed to park here.', 'Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor kleine personenauto''s met een maximaal gewicht van 3,5 ton. Vrachtwagens of bussen zwaarder dan 3,5 ton mogen hier niet parkeren.', 'Ce panneau indique que cette place de stationnement est exclusivement reservee aux petites voitures particulieres d un poids maximal de 3,5 tonnes. Les camions ou bus de plus de 3,5 tonnes ne peuvent pas stationner ici.', 'تشير هذه العلامة المرورية إلى أن هذا المكان مخصص حصراً للسيارات الخاصة الصغيرة التي يبلغ وزنها الأقصى 3.5 طن. لا يُسمح للشاحنات أو الحافلات التي يزيد وزنها عن 3.5 طن بالوقوف هنا.', 'images/signs/parkeren/E9b Parkeren uitsluitend voor auto''s.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9b');

-- E9c
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9c', 5, 'Parking for trucks only', 'Parkeren uitsluitend voor vrachtwagens', 'Stationnement réservé aux camions', 'مواقف للشاحنات فقط', 'Parking for trucks only', 'Parkeren uitsluitend voor vrachtwagens', 'Stationnement réservé aux camions', 'مواقف للشاحنات فقط', 'This traffic sign indicates that this parking space is exclusively for light trucks for transporting goods. All other vehicles are not allowed to park here.', 'Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor lichte vrachtwagens voor het vervoer van goederen. Alle andere voertuigen mogen hier niet parkeren.', 'Ce panneau indique que cette place de stationnement est exclusivement réservée aux camionnettes légères pour le transport de marchandises. Tous les autres véhicules ne peuvent pas stationner ici.', 'تشير إشارة المرور هذه إلى أن مكان ركن السيارات هذا مخصص حصراً للشاحنات الخفيفة لنقل البضائع. لا يُسمح لجميع المركبات الأخرى بالوقوف هنا.', 'images/signs/parkeren/E9c Parkeren uitsluitend voorvrachtwagens.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9c');

-- E9d
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9d', 5, 'Parking for coaches only', 'Parkeren uitsluitend voor autocars', 'Stationnement réservé aux autocars', 'مواقف للسيارات للحافلات فقط', 'Parking for coaches only', 'Parkeren uitsluitend voor autocars', 'Stationnement réservé aux autocars', 'مواقف للسيارات للحافلات فقط', 'This traffic sign indicates that this parking space is exclusively for public transport buses or tourist coaches. All other vehicles are prohibited from parking here.', 'Dit verkeersbord geeft aan dat deze parkeerplaats uitsluitend is bestemd voor bussen van het openbaar vervoer of touringcars. Het is voor alle andere voertuigen verboden hier te parkeren.', 'Ce panneau indique que cette place de stationnement est exclusivement réservée aux bus de transport public ou aux autocars touristiques. Il est interdit à tout autre véhicule de stationner ici.', 'تشير هذه الشاخصة المرورية إلى أن هذا المكان لوقوف السيارات مخصص حصراً لحافلات النقل العام أو الحافلات السياحية. يحظر على جميع المركبات الأخرى الوقوف هنا.', 'images/signs/parkeren/E9d Parkeren uitsluitend voor autocars.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9d');

-- E9e
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9e', 5, 'Mandatory parking on the verge or sidewalk', 'Verplicht parkeren op de berm of op het trottoir', 'Stationnement obligatoire sur l accotement ou le trottoir', 'وقوف السيارات الإلزامي على حافة أو الرصيف', 'Mandatory parking on the verge or sidewalk', 'Verplicht parkeren op de berm of op het trottoir', 'Stationnement obligatoire sur l accotement ou le trottoir', 'وقوف السيارات الإلزامي على حافة أو الرصيف', 'This traffic sign indicates that drivers must park their vehicle completely on the sidewalk. Partial parking on the road or in the middle is not allowed, as indicated on the sign.', 'Dit verkeersbord geeft aan dat bestuurders hun voertuig volledig op het trottoir moeten parkeren. Gedeeltelijk parkeren op de rijbaan of in het midden ervan is niet toegestaan, zoals aangegeven op het bord.', 'Ce panneau indique que les conducteurs doivent garer leur vehicule entierement sur le trottoir. Le stationnement partiel sur la chaussee ou au milieu n est pas autorise, comme indique sur le panneau.', 'تشير هذه العلامة المرورية إلى أنه يجب على السائقين ركن سيارتهم بشكل كامل على الرصيف. يمنع الوقوف بشكل جزئي على الطريق أو في وسطه كما هو موضح في الشاخصة.', 'images/signs/parkeren/E9e Verplicht parkeren op de berm of op het trottoir.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9e');

-- E9f
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9f', 5, 'Mandatory partial parking on the verge or sidewalk', 'Verplicht parkeren deels op de berm of op het trottoir', 'Stationnement obligatoire partiellement sur l accotement ou le trottoir', 'ركن السيارة بشكل جزئي على الحافة أو الرصيف', 'Mandatory partial parking on the verge or sidewalk', 'Verplicht parkeren deels op de berm of op het trottoir', 'Stationnement obligatoire partiellement sur l accotement ou le trottoir', 'ركن السيارة بشكل جزئي على الحافة أو الرصيف', 'This traffic sign requires drivers to park their vehicle partially on the sidewalk, with some wheels on the sidewalk and the rest on the road. This method is usually used on narrow roads to facilitate traffic.', 'Dit verkeersbord verplicht bestuurders om hun voertuig gedeeltelijk op het trottoir te parkeren, waarbij enkele wielen op het trottoir staan en de rest op de rijbaan. Deze methode wordt meestal gebruikt op smalle wegen om het verkeer te vergemakkelijken.', 'Ce panneau oblige les conducteurs a garer leur vehicule partiellement sur le trottoir, avec certaines roues sur le trottoir et le reste sur la chaussee. Cette methode est generalement utilisee sur les routes etroites pour faciliter la circulation.', 'تتطلب هذه العلامة المرورية من السائقين ركن سيارتهم جزئيًا على الرصيف، مع وضع بعض العجلات على الرصيف والباقي على الطريق. وعادة ما تستخدم هذه الطريقة على الطرق الضيقة لتسهيل حركة المرور.', 'images/signs/parkeren/E9f Verplicht parkeren deels op de berm of op het trottoir.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9f');

-- E9g
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9g', 5, 'Mandatory parking on the roadway', 'Verplicht parkeren op de rijbaan', 'Stationnement obligatoire sur la chaussee', 'وقوف السيارات الإلزامية على الطريق', 'Mandatory parking on the roadway', 'Verplicht parkeren op de rijbaan', 'Stationnement obligatoire sur la chaussee', 'وقوف السيارات الإلزامية على الطريق', 'This traffic sign requires drivers to park their vehicle completely on the roadway. It is absolutely forbidden to go up on the sidewalk, even partially. This is intended to protect sidewalks for pedestrians and ensure their safety.', 'Dit verkeersbord verplicht bestuurders om hun voertuig volledig op de rijbaan te parkeren. Het is absoluut verboden om op het trottoir te rijden, zelfs gedeeltelijk. Dit is bedoeld om de trottoirs voor voetgangers te beschermen en hun veiligheid te garanderen.', 'Ce panneau oblige les conducteurs a garer leur vehicule entierement sur la chaussee. Il est absolument interdit de monter sur le trottoir, meme partiellement. Cela vise a proteger les trottoirs reserves aux pietons et a garantir leur securite.', 'تتطلب هذه العلامة المرورية من السائقين ركن سياراتهم بشكل كامل على الطريق. يمنع منعاً باتاً الصعود على الرصيف ولو جزئياً. ويهدف ذلك إلى حماية الأرصفة للمشاة وضمان سلامتهم.', 'images/signs/parkeren/E9g - Verplicht parkeren op de rijbaan.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9g');

-- E9g-v1
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9g-v1', 5, 'E9g Mandatory parking on the road', 'E9g - Verplicht parkeren op de rijbaan variant 2', 'E9g Stationnement obligatoire sur la route', 'E9g وقوف السيارات الإلزامي على الطريق', 'E9g Mandatory parking on the road', 'E9g - Verplicht parkeren op de rijbaan variant 2', 'E9g Stationnement obligatoire sur la route', 'E9g وقوف السيارات الإلزامي على الطريق', 'Parking sign: follow the indicated parking rules.', 'Parkeerbord: Parkeren uitsluitend voor fietsen en bromfietsen. Volg de aangegeven parkeerregels.', 'Panneau de stationnement : suivez les règles de stationnement indiquées.', 'علامة وقوف السيارات: اتبع قواعد وقوف السيارات المشار إليها.', NULL, TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9g-v1'); -- image removed

-- E9h
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9h', 5, 'Parking for camper vans only', 'Parkeren uitsluitend voor kampeerauto''s', 'Stationnement reserve aux camping-cars', 'موقف سيارات لعربات الكارافانات فقط', 'Parking for camper vans only', 'Parkeren uitsluitend voor kampeerauto''s', 'Stationnement reserve aux camping-cars', 'موقف سيارات لعربات الكارافانات فقط', 'This parking space is exclusively for camper vans and caravans intended for camping and long trips. Regular vehicles are not allowed to park here.', 'Deze parkeerplaats is uitsluitend bestemd voor kampeerauto''s en caravans die bedoeld zijn voor kamperen en lange reizen. Het is niet toegestaan voor gewone voertuigen om hier te parkeren.', 'Cette place de stationnement est exclusivement reservee aux camping-cars et caravanes destines au camping et aux longs voyages. Il n est pas permis aux vehicules ordinaires de stationner ici.', 'مساحة وقوف السيارات هذه مخصصة حصريًا لعربات الكارافانات والكرفانات المخصصة للتخييم والرحلات الطويلة. لا يُسمح للمركبات العادية بالوقوف هنا.', 'images/signs/parkeren/E9h Parkeren uitsluitend voor kampeerauto''s.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9h');

-- E9i
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E9i', 5, 'Parking for motorcycles only', 'Parkeren uitsluitend voor motorfietsen', 'Stationnement reserve aux motos', 'مواقف للدراجات النارية فقط', 'Parking for motorcycles only', 'Parkeren uitsluitend voor motorfietsen', 'Stationnement reserve aux motos', 'مواقف للدراجات النارية فقط', 'This parking space is exclusively for motorcycles. It is strictly prohibited for cars or other vehicles to park here.', 'Deze parkeerplaats is exclusief bestemd voor motorfietsen. Het is strikt verboden voor auto''s of andere voertuigen om hier te parkeren.', 'Cette place de stationnement est exclusivement reservee aux motos. Il est strictement interdit aux voitures ou autres vehicules de stationner ici.', 'مساحة وقوف السيارات هذه مخصصة للدراجات النارية حصريًا. يمنع منعا باتا وقوف السيارات أو المركبات الأخرى هنا.', 'images/signs/parkeren/E9i Parkeren uitsluitend voor motorfietsen.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E9i');

-- E11
INSERT INTO traffic_signs (sign_code, category_id, name_en, name_nl, name_fr, name_ar, description_en, description_nl, description_fr, description_ar, long_description_en, long_description_nl, long_description_fr, long_description_ar, image_url, is_active, created_at, updated_at) SELECT 'E11', 5, 'Half-monthly parking', 'Halfmaandelijks parkeren', 'Stationnement semi-mensuel', 'مواقف سيارات نصف شهرية', 'Half-monthly parking', 'Halfmaandelijks parkeren', 'Stationnement semi-mensuel', 'مواقف سيارات نصف شهرية', 'This traffic sign regulates parking according to the date of the month. From the 1st to the 15th, parking is allowed on the side with odd house numbers, and from the 16th to the end of the month only on the side with even numbers.', 'Dit verkeersbord regelt het parkeren volgens de datum van de maand. Van de 1e tot de 15e is parkeren toegestaan aan de kant met oneven huisnummers, en van de 16e tot het einde van de maand alleen aan de kant met even huisnummers.', 'Ce panneau réglemente le stationnement selon la date du mois. Du 1er au 15, le stationnement est autorisé du côté des numéros impairs, et du 16 à la fin du mois uniquement du côté des numéros pairs.', 'تنظم هذه العلامة المرورية وقوف السيارات حسب التاريخ من الشهر. من اليوم 1 إلى اليوم 15، يُسمح بالوقوف على الجانب الذي به أرقام فردية، ومن اليوم 16 إلى نهاية الشهر فقط على الجانب الذي يحتوي على أرقام زوجية.', 'images/signs/parkeren/E11 Halfmaandelijks parkeren in gans de bebouwde kom.png', TRUE, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM traffic_signs WHERE sign_code = 'E11');
