package com.readyroad.readyroadbackend.dto.response;

public record TrafficSignResponse(
                Long id,
                String signCode,
                String categoryCode,
                String routeCode,
                Integer exam1TotalQuestions,
                Integer exam1PassingScore,
                String nameAr,
                String nameEn,
                String nameNl,
                String nameFr,
                String descriptionAr,
                String descriptionEn,
                String descriptionNl,
                String descriptionFr,
                String meaningAr,
                String meaningEn,
                String meaningNl,
                String meaningFr,
                String longDescriptionEn,
                String longDescriptionNl,
                String longDescriptionFr,
                String longDescriptionAr,
                String guidanceAr,
                String guidanceEn,
                String guidanceNl,
                String guidanceFr,
                boolean isLongDescriptionComplete,
                String imageUrl) {
}
